### ISSUE TITLE
Move clang-format back to main tests

### ISSUE THREAD

**Issue by Sumith1896** [symengine/symengine#1000]
http://apt.llvm.org/ is back up. 
`clang-format` was moved to allowed failures temporarily, revert the commit.
Refer to https://github.com/symengine/symengine/pull/970

**Comment by parsoyaarihant** [comment]
I am working on this issue. Any tips are welcome.

**Comment by Sumith1896** [comment]
Great @parsoyaarihant 
Ping me once you put in a PR

**Comment by Sumith1896** [comment]
Fixed via https://github.com/symengine/symengine/pull/1004
