### ISSUE TITLE
2**(x+1) is not expanded

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1021]
When expanded this should give `2*2**x`, but it returns `2**(x+1)`

**Comment by srajangarg** [comment]
Should `expand(2**(x +(1/2)))` give `2**(1/2) * 2**x`?

**Comment by isuruf** [comment]
Yes to both. See how SymPy does it

**Comment by certik** [comment]
I don't think we can represent `2*2^x` in SymEngine, can we? How would you represent it using the Mul's dictionary? Well, you could put `2` into a coeff. But this would then fail: `2**(x+y+1)`, since you can put `2` into a coeff, but you can't store the rest (`2^x * 2^y`) in the dictionary.

**Comment by isuruf** [comment]
You are right. We can only do it for the specific case of `2**(x+1)`, but not for `2**(x+y)`

**Comment by certik** [comment]
So I wouldn't do that for any case.
