### ISSUE TITLE
Canoncialize should be called on constructing `rational_class` from two `integer_class`

### ISSUE THREAD

**Issue by srajangarg** [symengine/symengine#1030]
[`mpq_wrapper`](https://github.com/symengine/symengine/blob/master/symengine/mp_wrapper.h#L358]) and [`fmpq_wrapper`](https://github.com/symengine/symengine/blob/master/symengine/flint_wrapper.h#L322)

I'm assuming `piranha::rational` and `gmp::mpz_class` already do canonicalize on construction.

**Comment by isuruf** [comment]
`piranha::rational` and `mpq_class` already does canonicalization.
