### ISSUE TITLE
Implement fast C code generation

### ISSUE THREAD

**Issue by certik** [symengine/symengine#1038]
Including Piecewise functions (#1037).

This would work similarly to our other printers.

This would be very useful for @richardotis's https://github.com/pycalphad/pycalphad/.

**Comment by moorepants** [comment]
Any way that this could work such that it speeds up SymPy's printers in the same way symengine symbolics speeds up SymPy's mathematical operations.

**Comment by richardotis** [comment]
Benchmarking SymEngine's string printing of complex expressions (from pycalphad) suggests you can achieve 20-30x speedups over SymPy's printers.

**Comment by isuruf** [comment]
This is implemented now
