### ISSUE TITLE
MinGW Release build fails

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1042]
Fails with the error message, 

   The procedure entry point _ZSt24__throw_out_of_range_fmtPKcz could not be located in the dynamic link library.

Searching in stackoverflow tells me that the error is because of mismatch in compiler versions, but libgmp.dll used is from mingw-get and should be the same.

Dependency walker seems to suggest that libstdc++-6.dll is the problem.

What's confusing is that there doesn't seem to be any changes to the build environment and the appveyor build started giving this error without any change at all.

**Comment by certik** [comment]
Thanks for figuring it out. We'll have to dig into it more to see how to fix it. Perhaps something changed on AppVeyor.

**Comment by isuruf** [comment]
This upgrade http://www.appveyor.com/updates/2016/07/16 changed MinGW version from 4.8.1 to 4.9.3

**Comment by isuruf** [comment]
Even though the date says July 16th, for some projects this update happened earlier, which explain the dates we started seeing the appveyor issues.

Issue is probably with the gmp libraries we use that are incompatible. We install gmp via `mingw-get install mingw32-gmp`, but `gmp` libraries haven't been updated in a long while and probably not binary compatible with gcc 4.9.3

**Comment by certik** [comment]
Right, I think that's what it is. We'll have to recompile them.

Do you know what Windows configurations are supported by conda-forge? Perhaps we can just support those configurations with symengine as well. And we can just use Conda to install the dependencies.

**Comment by isuruf** [comment]
Conda doesn't support MinGW yet, but it'll be supported soon. (Only MSVC is supported)

**Comment by isuruf** [comment]
Fixed in #1070
