### ISSUE TITLE
Wrap LU Factorization into SymEngine.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [symengine/symengine#1082]
I don't know if I just couldn't find it in the code (I found a QR factorization), but it would be nice to be able to find symbolic LU factorizations. One reason why this would be preferred to the QR factorization is because, although it's less numerically stable, LU factorized forms have faster calculations of the inverse (since both matrices are triangular). 

[I am specifically looking to use this (the Julia wrapped version) with DifferentialEquations.jl. Right now I am changing my code from SymPy to SymEngine and I am using it to silently create functions which calculate Jacobian matrices from the expressions for the ODE functions. The reason is because the Jacobian is used in solvers for stiff equations, and inverting the Jacobian is a high cost. If I could factorize this equation symbolically, then I could build an in-place function for computing the Jacobian which is pre-factorized, making implicit equations explicit and quick to compute]

**Comment by isuruf** [comment]
There is a LU factorization and it is wrapped into C [here](http://github.com/symengine/symengine/blob/9f75c4f167fcda9c709075de3e72cdb4948e166c/symengine/cwrapper.h#L426)

**Comment by ChrisRackauckas** [comment]
I see. Then my issue changes to wrapping it for SymEngine.jl 👍 .

**Comment by ChrisRackauckas** [comment]
(Maybe it should be opened up on the other repository?)

**Comment by isuruf** [comment]
Yes. Opened it here, symengine/SymEngine.jl#41

**Comment by jverzani** [comment]
I just added a pull request exposing SymEngine's `dense_matrix_LU` method, but want to point out that you can already call the generic LU decomposition (without pivoting) in Julia through  `lufact(A, Val{false})` where `A` is an `Array{Basic, 2}`.

**Comment by ChrisRackauckas** [comment]
I see. You guys overloaded the operators and so the generic LU does indeed work for Arrays of Basic. That's cool. Do those operators also simplify after each step?

**Comment by isuruf** [comment]
No in sympy sense, but yes in Calculus.jl sense. From that I mean, trivial and cheap simplifications like `sin(0) == 0`, `x + 2 * x == 3 * x` are done automatically. More complicated simplifications are not implemented in SymEngine yet. Eg: `y*sin(x)^2 + y*cos(x)^2 == y` is not implemented. SymPy has a `simplify` method that does this, but SymEngine doesn't have that yet.
