### ISSUE TITLE
Problem building with Piranha (2)

### ISSUE THREAD

**Issue by jppelteret** [symengine/symengine#1085]
A follow up issue after #1083 is fixed with #1084 . [Build log](https://github.com/symengine/symengine/files/504503/spack-build.txt) attached.

I should mention that this is built against the development version of `Piranha` on `OSX 10.11 El Capitan`.

```
/private/var/folders/lc/b4bjrtcn69d279m6rf4f42y00000gn/T/jp/spack-stage/spack-stage-QwVtWj/symengine/symengine/polys/uintpoly_piranha.h:115:25: error: 'container_type' is a protected member of 'piranha::series<piranha::mp_integer<0>, piranha::monomial<unsigned int, std::__1::integral_constant<unsigned long, 0> >, piranha::polynomial<piranha::mp_integer<0>, piranha::monomial<unsigned int, std::__1::integral_constant<unsigned long, 0> > > >'
    typename Container::container_type::const_iterator ptr_;
```

**Comment by certik** [comment]
Which exact git commit of piranha are you using? This build on linux https://travis-ci.org/symengine/symengine/jobs/164288991 seems to be using the latest git version, and it works, on linux. Are you using the same version?

I think we only test Piranha with GNU compilers, and only on linux. So I wonder if this is caused by using AppleClang on OS X.

@bluescarni any ideas?

**Comment by certik** [comment]
#1084 might fix this.

**Comment by bluescarni** [comment]
@certik @jppelteret It seems like the first error appearing in the log is:

```
error: 'container_type' is a protected member of 'piranha::series
```

which seems to be triggered from here:

https://github.com/symengine/symengine/blob/master/symengine/polys/uintpoly_piranha.h#L115

Which seems kind of reasonable. I can't recall changing the visibility of the ``container_type`` typedef recently, so I am not exactly sure what is going on.  @isuruf any idea?

(Piranha's CI tests against GCC/clang, Apple Clang should be ok apart from the fact that it does not support the ``thread_local`` keyword).

**Comment by bluescarni** [comment]
(I can change the visibility of the typedef if needed, I am just curious about how this is not showing up on the CIs)

**Comment by jppelteret** [comment]
@certik It would have been the latest git version on the master branch.

**Comment by jppelteret** [comment]
@certik This issue is one that arises after the patch #1084 is applied.

**Comment by isuruf** [comment]
@bluescarni, I think gcc doesn't care about the visibility of that typedef. Clang apparently does.

**Comment by isuruf** [comment]
@bluescarni, in symengine, we only test piranha on linux, that's why this bug was not discovered early.
