### ISSUE TITLE
Rename UndefinedError to DomainError

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1089]
Also throw `DomainError` in places like these, https://github.com/symengine/symengine/blob/master/symengine/real_mpfr.cpp#L800

**Comment by ShikharJ** [comment]
Can I work on this issue?

**Comment by certik** [comment]
@ShikharJ of course! You can work on any issue you want. Let us know if you need any help.

**Comment by ShikharJ** [comment]
@certik Should I keep the SymEngineException or just throw DomainError exception?

**Comment by ShikharJ** [comment]
@certik I have made the changes as specified, though I am clueless about running the tests (that the development workflow page recommends to run). How can I run the tests?

**Comment by isuruf** [comment]
Run `ctest` from the build directory. (`ctest -v` for more verbosity)

**Comment by ShikharJ** [comment]
It returns No Tests Were Found

**Comment by isuruf** [comment]
@ShikharJ, are you running it from the directory that you built symengine? Can you post the commands you used when building symengine?

**Comment by ShikharJ** [comment]
Actually I didn't specifically build symengine. I accessed the files using CLion and looked for the above issue manually.

**Comment by ShikharJ** [comment]
I see my mistake. Thanks @isuruf !

**Comment by ShikharJ** [comment]
@isuruf @certik I've run cmake ., make and ctest. They all run fine. What should I do next?

**Comment by isuruf** [comment]
Send a pull request with your changes.
