### ISSUE TITLE
Travis: Install a specific Piranha version

### ISSUE THREAD

**Issue by certik** [symengine/symengine#1091]
Currently we always install the latest version, which then sometimes breaks things, e.g. here:

https://travis-ci.org/symengine/symengine/jobs/167098984#L382

the failure is caused by Piranha now requiring cmake 3.0.

The solution is to checkout a specific git version, so that our tests are reproducible and don't change. Then from time to time we upgrade to a newer Piranha version and fix tests if needed.

**Comment by isuruf** [comment]
Fixed in #1093
