### ISSUE TITLE
LLVM and GCC 5 ABI

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1128]
GCC 4.x and GCC 5.x have incompatible ABIs. LLVM is the only C++ library being used at the moment (piranha is header only). Using LLVM compiled with gcc 4 ABI with gcc 5 gives weird errors. Two options to handle this,

1. Detect whether the 2 ABIs are incompatible and raise an error in CMake
2. Use LLVM's C API

**Comment by certik** [comment]
The rule with C++, as well as Fortran, is that you have to use the same compiler (version) to compile the whole project. So you can't mix GCC 4 and 5.

Why do we compile LLVM with GCC 4 and then symengine with GCC 5? We have to choose a GCC version (4, 5, or 6), and then use that for both LLVM and symengine.

I don't know if these things can be detected in CMake. But the rule of thumb, for both developers and users, is that you just don't mix different C++ compilers. You can mix C compilers, but not C++ or Fortran compilers.

**Comment by isuruf** [comment]
Compiling with gcc 5 is fine if we use the gcc 4 abi.
Since we are using dependencies from conda-forge which were compiled with gcc 4.8.2, we can't use llvmdev package from conda-forge when compiling with a newer gcc compiler

**Comment by certik** [comment]
@isuruf we can create our own Conda channel compiled with a newer gcc compiler.
