### ISSUE TITLE
MacOS and rpath

### ISSUE THREAD

**Issue by jppelteret** [symengine/symengine#1148]
Hi all!

Apologies in advance for the lengthy message.

I'm trying to integrate `SymEngine` (shared library) into another project. I've managed to get `CMake` to detect and configure against `SymEngine` but have hit some linking errors when compiling an executable. 

So I've gone back to basics and have built a minimal `SymEngine` on `MacOS 10.11` using the following options
```
cmake \
-DCMAKE_BUILD_TYPE=Debug \
-DINTEGER_CLASS:STRING=boostmp \
-DBoost_INCLUDE_DIR=$SPACK_VIEW_DIR/include \
-DBUILD_SHARED_LIBS:BOOL=on \
-DCMAKE_INSTALL_PREFIX=<PATH>/SymEngine/install \
../symengine
```
This leads to this warning
```
Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
--help-policy CMP0042" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.

MACOSX_RPATH is not specified for the following targets:

 symengine
 symengine_unity
```
and the paths of the shared libraries are consequently
```
 $ otool -L ../install/lib/libsymengine.dylib
../install/lib/libsymengine.dylib:
	libsymengine.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```
I think that this explains why by executable couldn't load the `SymEngine` library the relative/absolute location of `libsymengine.dylib` is not specified.

So I tried to add this to `CMakeLists.txt` before`add_subdirectory(symengine)`
```
if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  ## References:
  ## cmake  --help-policy CMP0042
  set(CMAKE_MACOSX_RPATH ON)
endif()

if(CMAKE_INSTALL_RPATH_USE_LINK_PATH)
  ## References:
  ## https://cmake.org/Wiki/CMake_RPATH_handling#Mac_OS_X_and_the_RPATH
  set(CMAKE_SKIP_BUILD_RPATH FALSE)
  set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
  # set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
  list(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
  if("${isSystemDir}" STREQUAL "-1")
     set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
  endif("${isSystemDir}" STREQUAL "-1")
endif()
``` 
which is what is recommended to suppress the original `CMake` warning and to configure `rpath` at install time. 
With the addition of an extra command during configuration
```
cmake \
-DCMAKE_BUILD_TYPE=Debug \
-DINTEGER_CLASS:STRING=boostmp \
-DBoost_INCLUDE_DIR=$SPACK_VIEW_DIR/include \
-DBUILD_SHARED_LIBS:BOOL=on \
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=on \  // <----------
-DCMAKE_INSTALL_PREFIX=<PATH>/SymEngine/install \
../symengine
```
this half fixes the problem
```
$ otool -L ../install/lib/libsymengine.dylib
../install/lib/libsymengine.dylib:
	@rpath/libsymengine.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```
but the full install directory for `rpath` is not filled out. I would have expected this to result in something like `<PATH>/SymEngine/install/lib/libsymengine.dylib`.

I'm by no means an expert on `CMake`, and cannot work out if I'm doing something wrong or whether there's some more complex interaction between these settings and the rest of the build system. Can anyone offer some advice/insight as to how to correct this issue?

**Comment by isuruf** [comment]
Can you try `cmake -DCMAKE_INSTALL_NAME_DIR=<PATH>/SymEngine/install/lib`?

**Comment by jppelteret** [comment]
Thanks a lot @isuruf, that did the trick! I'll embed it in what I'd added to `CMakeLists.txt` and will open a PR shortly for you to inspect.
