### ISSUE TITLE
`subs(1/x, x, 0)` is 0

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1154]
From symengine/SymEngine.jl#22

**Comment by srajangarg** [comment]
This has to deal with how `pow(0, <anything>)` is currently handled in SymEngine. It is directly taken to be zero.

Sympy does this
```
>>> Pow(0, <positive number>)
0
>>> Pow(0, 0)
1
>>> Pow(0, x)
0**x
>>> Pow(0, <negative number>)
zoo
```

whereas SymEngine reduces to `0` in all cases (`0**x` is a non-canonical `Pow` according to the current code). I think we should shift to how Sympy does it. @certik

**Comment by ranjithkumar007** [comment]
@srajangarg  edit: pow(0,0) is reducing to 1 in SymEngine . 
rest are reducing to zero as you pointed out.
