### ISSUE TITLE
Use `down_cast<>().` instead of `rcp_static_cast<>()->`

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1155]
For eg: `static_cast<const Integer &>(*i).as_integer_class()` instead of `rcp_static_cast<const Integer>(i).as_integer_class()`

**Comment by ShikharJ** [comment]
@isuruf I'd like to take this up.

**Comment by certik** [comment]
@isuruf I think we should use `down_cast`, not `static_cast`. I would like all these conversions to be checked in Debug mode to make sure that they are safe. I am hoping that no matter what you put in XXX in `down_cast<XXX>(*i).as_integer_class()`, that it will either not compile, or raise an exception in Debug mode.

**Comment by isuruf** [comment]
@certik, I agree.

**Comment by aneesh2312** [comment]
If noone took this up yet, I would like to start on it.

**Comment by ShikharJ** [comment]
@aneesh2312 I am working on it.

**Comment by ShikharJ** [comment]
Fixed via #1156.
