### ISSUE TITLE
pow(Constant, RealDouble) is not evaluated automatically

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1174]
Neither is `pow(RealDouble, Constant)`. This is because `Constant` is not inheriting from `Number`.

**Comment by jppelteret** [comment]
@isuruf If you're willing to give me a few hints at where this fix should be implemented, I'd be happy to take a shot at implementing it.

**Comment by ShikharJ** [comment]
@jppelteret Are you working on this issue? If not, I'd like to take this up.

**Comment by jppelteret** [comment]
@ShikharJ I haven't started working on it yet, but I'm invested in getting it sorted out. If you have a good idea as to what needs to be done then please feel free to take it up!

**Comment by jppelteret** [comment]
Oh, its just struck me. One probably needs to extend the [definition of pow](https://github.com/symengine/symengine/blob/master/symengine/pow.cpp#L90), right? I'd only be able to start working on this this afternoon, so @ShikharJ if you are going to work on this right away then I won't get in the way :-)

**Comment by ShikharJ** [comment]
@jppelteret Thanks for the quick reply :) I'll get on it right away.

**Comment by jppelteret** [comment]
Thanks very much @ShikharJ . I appreciate it 😀
