### ISSUE TITLE
Move log to functions.h

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1176]
Currently `log` is in `pow.h`, but it doesn't make much sense as `log` is a `Function` while `pow` is not.

**Comment by ranjithkumar007** [comment]
+1 .
@isuruf  I would like to do this within  PR #1172

**Comment by isuruf** [comment]
Let's get #1172 ready first and we can fix this in another PR.

**Comment by kvmanohar22** [comment]
@isuruf, @ranjithkumar007   I have moved log into functions.h, here's the PR [#1191](https://github.com/symengine/symengine/pull/1191)

**Comment by ranjithkumar007** [comment]
Fixed via #1195
