### ISSUE TITLE
Compilation error: get_mpq_t, get_mpz_t

### ISSUE THREAD

**Issue by jppelteret** [symengine/symengine#1186]
I'm building `SymEngine` against `boost`, rather than `Flint` etc. On the master branch I'm currently getting some compilation errors like 
```bash
.../symengine/symengine/real_mpfr.cpp:299:17: error: use of undeclared identifier 'get_mpq_t'
                get_mpq_t(other.imaginary_), MPFR_RNDN);
                ^
.../symengine/symengine/real_mpfr.cpp:349:16: error: use of undeclared identifier 'get_mpz_t'
               get_mpz_t(other.as_integer_class()), MPFR_RNDN);
```

[Build log attached.](https://github.com/symengine/symengine/files/725873/spack-build.out.txt)

**Comment by isuruf** [comment]
This is because `INTEGER_CLASS=boostmp` and `WITH_MPFR=true` are incompatible. We should disable `WITH_MPFR=true` if  `INTEGER_CLASS=boostmp` is set.

**Comment by jppelteret** [comment]
Thanks for the explanation. So this is clearly a misconfiguration on my part. I'll update the [spack package](https://github.com/LLNL/spack/pull/2919) accordingly.
