### ISSUE TITLE
Functions "erf" and "erfc" missing in Evaluate class

### ISSUE THREAD

**Issue by jppelteret** [symengine/symengine#1187]
As the title says, `erf` and `erfc` functions are missing in the `Evaluate` class. Without these (and their automatic evaluation) its not possible to evaluate the result of these functions called with a custom number class derived from `NumberWrapper`.

Relates to #1185

**Comment by ranjithkumar007** [comment]
@jppelteret  i would like to have a swing on this !!

**Comment by jppelteret** [comment]
Thanks @ranjithkumar007, that would be great! If I'm not mistaken, the approach used in #1185 to implement the `exp` function is relevant here.

**Comment by jppelteret** [comment]
I think that there might be more  functions that also cannot be evaluated with `NumberWrapper` derived numbers, but I'm not 100% certain (I haven't yet created a test case for these that demonstrate failure):
- [ ] `sqrt`
- [ ] `atan2`
- [ ] `min`
- [ ] `max`

@isuruf Do you any comment about which functions from [`functions.h`](https://github.com/symengine/symengine/blob/master/symengine/functions.h) you would expect to be mimicked in the `Evaluate` class? I haven't looked at `zeta, LogGamma, etc.`.

**Comment by isuruf** [comment]
`min` and `max` should also work, even though it's not the most efficient implementation.
For other one argument functions, yes. For two args, we have to have some coercion for the two args.

**Comment by jppelteret** [comment]
Ok, thanks for the clarification once again! So if I understand correctly only `erf` and `erfc` and the other one argument functions `zeta, LogGamma, etc.`  need implementation.
