### ISSUE TITLE
Function "asech" missing in Evaluate class 

### ISSUE THREAD

**Issue by jppelteret** [symengine/symengine#1188]
As the title says, `asech` function [is missing](https://github.com/symengine/symengine/blob/fc581dccc33556c407d240f5353a7c7c818da10e/symengine/number.h#L180) in the `Evaluate` class. Without this (and its automatic evaluation) its not possible to evaluate the result of these functions called with a custom number class derived from `NumberWrapper`.

Relates to #1185 and #1187

**Comment by aditodkar** [comment]
Hi, I am new to symengine and would like to work on this can you tell me how to get started.

**Comment by jppelteret** [comment]
Hi @aditodkar! A fix is already in progress for this (see  #1189). Thanks very much for being willing to implement this though! There are a couple of outstanding functions to be implemented that you could take a go at (see #1187). I'm not really familiar with the low-level working of `SymEngine`, so I would recommend that you look at patches that are being, and have been, developed for #1185 and  #1189 to start to understand what needs to be done.

**Comment by isuruf** [comment]
Fixed in #1189
