### ISSUE TITLE
Function "abs" is crashing for me

### ISSUE THREAD

**Issue by poke1024** [symengine/symengine#1197]
This might be a problem with my build, but the following code keeps crashing for me:

SymEngine::abs(SymEngine::add(SymEngine::mul(SymEngine::integer(-1), SymEngine::symbol("a")), SymEngine::symbol("b")));

The stacktrace looks like an infinite recursion:

<img width="498" alt="stacktrace" src="https://cloud.githubusercontent.com/assets/11859538/22349925/06c84044-e412-11e6-9aac-974e1e433be7.png">

Here's a full demo project:

[demo-abs.zip](https://github.com/symengine/symengine/files/733556/demo-abs.zip)

**Comment by isuruf** [comment]
I can reproduce this.
