### ISSUE TITLE
Version libsymengine.so

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1226]
Here's an example of gmp,
```
isuru@isuru:~/projects/symengine.py$ ls -l  ~/miniconda3_2/lib/libgmp.so*
lrwxrwxrwx  1 isuru isuru     16 පෙබ   7 14:01 /home/isuru/miniconda3_2/lib/libgmp.so -> libgmp.so.10.3.2
lrwxrwxrwx  1 isuru isuru     16 පෙබ   7 14:01 /home/isuru/miniconda3_2/lib/libgmp.so.10 -> libgmp.so.10.3.2
-rwxr-xr-x 48 isuru isuru 802914 ජන    3 13:47 /home/isuru/miniconda3_2/lib/libgmp.so.10.3.2
```
the libraries are versioned. We should do the same for `libsymengine.so` and also have a soname for the library. 

http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html
https://cmake.org/cmake/help/v3.0/prop_tgt/SOVERSION.html

**Comment by ranjithkumar007** [comment]
@isuruf , Is this the complete list of shared libraries ? 

/lib64/ld-linux-x86-64.so.2
/lib/x86_64-linux-gnu/libc.so.6
/lib/x86_64-linux-gnu/libgcc_s.so.1
/lib/x86_64-linux-gnu/libm.so.6
/usr/lib/x86_64-linux-gnu/libgmp.so.10
/usr/lib/x86_64-linux-gnu/libstdc++.so.6

Command that generated list of shared libraries used by the executables is : 
```
find symengine/ -type f -perm /a+x -exec ldd {} \; | grep so | sed -e '/^[^\t]/ d' | sed -e 's/\t//' | sed -e 's/.*=..//' | sed -e 's/ (0.*)//' | sort | uniq
```
Source : [StackOverflow](http://stackoverflow.com/questions/50159/show-all-libraries-used-by-executables-on-linux)

**Comment by isuruf** [comment]
This is about versioning `libsymengine.so`
see,
http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html
https://cmake.org/cmake/help/v3.0/prop_tgt/SOVERSION.html

**Comment by ranjithkumar007** [comment]
I interpreted the title wrongly. 
thanks for clarifying.
