### ISSUE TITLE
Where is Pow?

### ISSUE THREAD

**Issue by BlackTeaAndCoffee** [symengine/symengine#1232]
I use symengine in python3 and it's great. Cudos for that. But i would like to use Pow for exponentiating. Currently is use symengine to construct a function, which i then let transform into c code using the printing module of sympy. Then i use ctypes to integrate the function. The bottle neck is currently the printing of the c code. If i could use Pow, i could avoid the printing and things would get a lot faster.

Best Wishes 
Your doing a great job

**Comment by isuruf** [comment]
I'm not sure I understand what you want. Can you explain more?

**Comment by BlackTeaAndCoffee** [comment]
Of course, 

first of all, i can not use symengine.pow(2,2) for example. That does not work, because there is no function pow in symengine, atleast if i do help(symengine) in the python console there is no mention of the pow function.  

Ok now to the c code part. I'm using ctypes to integrate a function, because this way it's much faster. For this i need to convert the function that i constructed symbolically into c code. This takes a lot of time. When i was searching for a faster way to do symbolic computation i ran into you guys. Symengine is build on cpp so the code is similar. For example, when i do sympy.exp(2) in the python console it gives exp(2), but with symengine.exp(2) it's E**(2). So thats already very similar to what a c function should look like. 

For faster integration i need the pow() function. With it i would not need the c code printer from sympy, i just could use the output of the function. 

I'm only a scientist and do not know the technical terms required here, sorry for that.

Best wishes

**Comment by isuruf** [comment]
- You can use python's builtin pow `pow(x, 2)`  or just `x**2`.
- FYI, we moved from printing `E**2` to `exp(2)` in symengine master :worried: to make it compatible with sympy
- For generating c-code for symengine, we have a work in progress here, https://github.com/symengine/symengine.py/pull/90
- I'm not sure what you mean by "you are using ctypes to integrate", but if it means generating code for a C function, compiling it and using it in a numerical integrator like scipy, then you can also use `lambdify`. We also recently added a feature to compile symengine expressions to machine code using LLVM as well.

**Comment by BlackTeaAndCoffee** [comment]
Hi, I used lambdfiy before in sympy, but this was when i used typical scipy to integrate. There is this extension, where you can use ctypes to make your integration with scipy.integrate faster. For that i need the function i want to integrate in c. I know that i can use the built in function pow(x,2) or x**2, t, but converting every x**2 to pow(x,2),(x**2 + x)**2 to pow(pow(x,2)+x,2) and much more complicated functions takes a lot of time, but pow is apperantly the way to go in c. Well i'll look up your c-code generator in the future.

**Comment by isuruf** [comment]
`Lambdify` is just a C function pointer with the signature `void func(double* input, double *output)`. You can create a ctypes function using `ctypes.cast` if there is an API to get the address of this function pointer, right?

**Comment by BlackTeaAndCoffee** [comment]
I don't know. I really just look at how fast different methods are.
Maybe the way you are doing things with lambdify is faster. I'll try it out.

Best wishes

Am 25.03.2017 um 04:48 schrieb Isuru Fernando:

**Comment by isuruf** [comment]
Can you send a benchmark so that I can run and see?

**Comment by BlackTeaAndCoffee** [comment]
Of course,

i'll do that.

Best Wishes
Musta

Am 25.03.2017 um 16:24 schrieb Isuru Fernando:

**Comment by isuruf** [comment]
ccode is implemented now
