### ISSUE TITLE
Introduction of "number_is_zero" in C wrappers?

### ISSUE THREAD

**Issue by rdbyk** [symengine/symengine#1254]
Hi,

I am asking, whether it would be a good idea to replace the following two functions

```
int real_mpfr_is_zero(const basic s);
int complex_mpc_is_zero(const basic s);
```
by just the following one?
```
int number_is_zero(const basic s)
{
    SYMENGINE_ASSERT(is_a_Number(*(s->m)));
    return (int)((down_cast<const Number &>(*(s->m))).is_zero());
}
```

This would allow to check all numbers with the same function for being zero or not. Do you think
this is a good idea, or are there any drawbacks?

Thank you,

Dirk

**Comment by isuruf** [comment]
I think that's a good idea. Would you be able to send a PR?

**Comment by rdbyk** [comment]
I will happily try to do so, give me a couple of days ... I am total git(hub) newbie!

**Comment by isuruf** [comment]
Great. Let me know if you need any help with git and github.
