### ISSUE TITLE
Relationals passed to functions should throw

### ISSUE THREAD

**Issue by ShikharJ** [symengine/symengine#1303]
`sin(x < y)` should ideally raise an error as the value of a `Relational` cannot be obtained. One needs to check with `SymPy`'s  output for other functions as well. Refer #1298.

**Comment by isuruf** [comment]
I don't think this is necessary. SymPy throws unintentionally, not because it checks for the value explicitly.
This would lead to code bloat.

**Comment by ShikharJ** [comment]
@srajangarg What would be your take on this?

**Comment by srajangarg** [comment]
Let's stick to what @isuruf said. We can add it whenever it's need is required.
