### ISSUE TITLE
Use dist:trusty in travis-ci

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1307]
Travis-ci will move to trusty in a week. See this announcement, https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

**Comment by ShikharJ** [comment]
Doesn't this require the use of `dist: trusty` tag? `image: trusty` in `travis.yml` doesn't seem to change the distribution to `trusty` from `precise`.

**Comment by isuruf** [comment]
Yes, corrected it.
