### ISSUE TITLE
Respect cmake's CMAKE_INSTALL_LIBDIR

### ISSUE THREAD

**Issue by toddrme2178** [symengine/symengine#1321]
cmake provides a `CMAKE_INSTALL_LIBDIR` variable that lets you define where libraries are installed. From what I can see, symengine doesn't support it. Instead, on non-windows platforms it hard-codes libraries as being installed in `${CMAKE_INSTALL_PREFIX}/lib`. This is usually not the correct place on 64bit Linux systems. It would make installation and packaging much easier if there was some variable to define this, ideally a standard CMAKE one like `CMAKE_INSTALL_LIBDIR`.

**Comment by isuruf** [comment]
If you send a PR I'll merge it. I'll add this for the next release milestone

**Comment by toddrme2178** [comment]
I have been looking into it, but haven't been able to figure out how to get it working yet.

**Comment by certik** [comment]
@toddrme2178 thanks for reporting it, thanks @isuruf for fixing it.
