### ISSUE TITLE
Fast numerical evaluation

### ISSUE THREAD

**Issue by scarrazza** [symengine/symengine#1328]
I have a question concerning the numerical evaluation of symbolic expressions in SymEngine. 
If I understand correctly the `n()` method is the only available method to obtain the numerical output of an expression. 

I would like to know if there is some faster approach already in the code or if you are planning to implement a fast method similar to `autowrap` in Sympy directly in SymEngine.

**Comment by isuruf** [comment]
Have a look at `lambda_double.h` and `llvm_double.h`. `LLVMDoubleVisitor` should be similar to `autowrap`.

If you are using python have a look at `lambdify`

**Comment by scarrazza** [comment]
Thanks for the reply. 

If I understand correctly the symengine.Lambdify function with backend='llvm' uses the `LLVMDoubleVisitor`. Do you provide some benchmark code in pure C++ similar to the python https://github.com/symengine/symengine.py/blob/master/benchmarks/Lambdify.py ?

Do you have some notes/docs explaining both approaches?

Thank you.

**Comment by isuruf** [comment]
You can have a look at this, https://github.com/symengine/symengine/blob/master/symengine/tests/eval/test_lambda_double.cpp#L188

I'll try to explain here. `Lambda` takes more time than `LLVM` for evaluation, but has lower setup cost. Overall, LLVM is faster only if you do more than a specific number of evaluations which depends on your expression. Also LLVM can do common subexpression elimination. So if you have multiple expressions, use one LLVMDoubleVisitor for all of them to get the benefit of that.

**Comment by scarrazza** [comment]
Thank you very much for the explanation.

**Comment by ShikharJ** [comment]
@scarrazza Would you mind if I close this issue, if your concerns have been resolved?

**Comment by scarrazza** [comment]
Sure, thanks.On Sep 28, 2017 20:02, Shikhar Jaiswal <notifications@github.com> wrote:@scarrazza Would you mind if I close this issue, if your concerns have been resolved?
