### ISSUE TITLE
Jacobian calculation benchmark

### ISSUE THREAD

**Issue by certik** [symengine/symengine#133]
Here is a real life problem (by @moorepants): https://gist.github.com/certik/10342153. Run `b.py` from that gist:
```
$ python b.py 
Reading
Done
Jacobian
Done
Time:  28.4419150352
```
It takes 28s on my laptop using SymPy. The benchmark reads the matrices from the file `A.txt`. You can generate the formulas in this file using `a.py` if you wish (you need to install https://github.com/pydy/pydy-code-gen/ for that), but for this benchmark, just the Jacobian calculation is important.

**Comment by isuruf** [comment]
This benchmark is now in Python repo
