### ISSUE TITLE
Implement assumptions handling

### ISSUE THREAD

**Issue by certik** [symengine/symengine#1334]
For this, we should implement the "new assumptions" style as is done in SymPy. We should write down the details first and consult with other SymPy devs, to ensure that we don't run into some dead ends, or some problems later.

**Comment by amcostant** [comment]
@certik I have no C++ experience otherwise, I would have liked to help out with this. I use the Julia libraries of SymEngine. It has been very beneficial to my research, thank you for all your work on SymEngine.

**Comment by rikardn** [comment]
A first version of assumptions is now implemented. See the `assumptions.h` and `test_visitors.h` for a use case.
