### ISSUE TITLE
Implement functions in C Code printer

### ISSUE THREAD

**Issue by Wrzlprmft** [symengine/symengine#1341]
It would be really great if the C-code printer supported functions, i.e., the following would work (in the Python wrapper):

``` Python
from symengine.printing import ccode
from symengine import Function, Symbol
f = Function("f")
x = Symbol("x")
ccode(f(x))
```

As far as I can tell, this is the only (major) missing piece missing for my modules [JiTCODE](https://github.com/neurophysik/jitcode), [JiTCDDE](https://github.com/neurophysik/jitcdde), and [JiTCSDE](https://github.com/neurophysik/jitcdde) to switch from SymPy to SymEngine, which I expect to yield a considerable speed-up.

**Comment by isuruf** [comment]
I think it's only a matter of deleting the lines https://github.com/symengine/symengine/blob/master/symengine/codegen.h#L167-L170
Can you try that and if it works send a PR with a test?

**Comment by Wrzlprmft** [comment]
> I think it's only a matter of deleting the lines …

I haven’t tested it, but I would guess that this would cause functions to be ignored instead of rendered, i.e., you would get something like `ccode(f(x))=="x"`.

**Comment by isuruf** [comment]
> I haven’t tested it, but I would guess that this would cause functions to be ignored, not rendered

When that method is deleted, it should fallback to the method in `StrPrinter` which the `CCodePrinter` inherits from and `f(x**2)` would be printed as `f(pow(x, 2))`

**Comment by Wrzlprmft** [comment]
Ah, great. I will test this in the next few days.

**Comment by ShikharJ** [comment]
@Wrzlprmft I created a PR [here](https://github.com/symengine/symengine/pull/1343). Could you confirm it's what you require?

**Comment by Wrzlprmft** [comment]
@ShikharJ: Yes, thanks. I actually tested removing those lines earlier and it does what I want. I just didn’t have the time to write a test and pull request yet.
