### ISSUE TITLE
Update Ruby for Homebrew

### ISSUE THREAD

**Issue by ShikharJ** [symengine/symengine#1344]
The last two `OSX` jobs are currently failing with the following error:
```
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)
```
@isuruf Can you point out how can this be done? I couldn't find the code for installing `Ruby` in `travis` .

**Comment by isuruf** [comment]
You just need to do `brew update` before using brew install.
