### ISSUE TITLE
Move to a higher clang-format version?

### ISSUE THREAD

**Issue by ShikharJ** [symengine/symengine#1346]
I recently installed the new `Ubuntu 17.10`. On this system, `clang-format-3.7` is unavailable (the default being `clang-format-4.0.1`).

**Comment by ShikharJ** [comment]
@isuruf @certik Thoughts?

**Comment by certik** [comment]
That is fine. Hopefully we don't need to modify our source code. Let's send a PR and see what changes we need to make.

**Comment by isuruf** [comment]
`conda-forge` has 3.8 in `clangdev` package.

**Comment by isuruf** [comment]
Ubuntu 17.10 has https://launchpad.net/ubuntu/artful/+package/clang-format-3.7

**Comment by ShikharJ** [comment]
Closed vis #1348
