### ISSUE TITLE
If a sum is subtracted, merge it into the resulting sum

### ISSUE THREAD

**Issue by Wrzlprmft** [symengine/symengine#1347]
It seems that subtracting `expr` is realised as and addition of `Mul(-1,expr)`, which in turn does not means that if the subtrahend is a sum, it will not be merged in the sum resulting from the subtractions. This yields an overcomplication of certain terms that do not get simplified automatically. For example `x - (1 + x)` stays like this and does not get automatically reduced to `-1`.

**Comment by isuruf** [comment]
Duplicate of https://github.com/symengine/symengine/issues/207
