### ISSUE TITLE
Potential bug in lambda double CSE symbol substitution

### ISSUE THREAD

**Issue by jppelteret** [symengine/symengine#1365]
The [comment made here](https://github.com/symengine/symengine/blob/master/symengine/lambda_double.h#L70) and clearing of the `cse_intermediate_fns_map` does not seem to agree with the later attempted [use of this map here](https://github.com/symengine/symengine/blob/master/symengine/lambda_double.h#L110). I don't have a test case, but this looks like it may lead to a case that an eliminated subexpression may not be able to be evaluated.

**Comment by isuruf** [comment]
It's not later. Later use would be in `call` and `cse_intermediate_fns_map` is not used anymore. All the `bvisit` methods are called here, https://github.com/symengine/symengine/blob/master/symengine/lambda_double.h#L68 which is before the map is cleared.

**Comment by jppelteret** [comment]
Right, that makes sense. I didn't see that flow path at the time, but its quite clear now. Thanks a lot for the explanation!
