### ISSUE TITLE
Pretty or latex printing

### ISSUE THREAD

**Issue by Midnighter** [symengine/symengine#1372]
I like to use the sympy feature `sympy.init_printing(use_latex=True)` in my Jupyter notebooks and I was wondering if there is anyway to achieve the same behavior with symengine?

**Comment by certik** [comment]
@Midnighter good point. This should be implemented by the Python wrappers (https://github.com/symengine/symengine.py). Alternatively, we are also trying to use SymEngine in SymPy itself, then sympy should take care of it. But the latex printing would be useful to have in symengine.py even without SymPy.

**Comment by Midnighter** [comment]
Awesome :tada:
