### ISSUE TITLE
Handling of one raised to the power of infinity (1**oo)  inconsistent with SymPy

### ISSUE THREAD

**Issue by Wrzlprmft** [symengine/symengine#1374]
``` Python
import symengine
import sympy

1**symengine.oo
# 1

1**sympy.oo
# nan
```

The same applies to `1**zoo` and `1*-oo`.

**Comment by npochhi** [comment]
Hi! I'd like to work on this! If I'm understanding this issue correctly, I only have to add a condition for checking the value of base to 1 and exponent to Inf (using `eq` function) and returning the required result in the Pow.cpp file. Is this correct?

**Comment by ShikharJ** [comment]
@npochhi You'll have to improve the check for this in `pow.cpp`.
