### ISSUE TITLE
Implement trailing whitespace check

### ISSUE THREAD

**Issue by certik** [symengine/symengine#138]
Just like in SymPy in sympy/utilities/tests/test_code_quality.py. 

Not sure yet where we should put them, since it depends on Python. But the point is to run them once in Travis, so that we catch any trailing whitespace in PRs.

**Comment by certik** [comment]
I would put this test into `bin/test_whitespace_travis.py` and just run this from Travis, that's it. It won't be run as part of a test suite, but you can run it by hand.

**Comment by YetAnotherMinion** [comment]
Is this test still desired? I would be interested in taking a crack at it.

**Comment by Sumith1896** [comment]
Go ahead @YetAnotherMinion

**Comment by YetAnotherMinion** [comment]
I took a look at [sympy/utilities/tests/test_code_quality.py](https://github.com/sympy/sympy/blob/master/sympy/utilities/tests/test_code_quality.py) and saw it had many more features than just trailing whitespace. I am going to start by porting that code because I like the structure but only check whitespace at this time. Let me know if I should port additional checks like using tabs instead of spaces, checking for carriage returns etc..

**Comment by Sumith1896** [comment]
As you wish. We can add additional sanity checks later too :)

**Comment by certik** [comment]
@YetAnotherMinion Let's start with just trailing white space for now.

Later, we can add more C++ checks, for example a check that we never use raw pointers, raw new/delete (except in specific places) etc.

Another idea is to simply require that all source code is formatted using clang-format, and simply use that as our definition of formatting.

**Comment by CodeMaxx** [comment]
Has this been resolved?

**Comment by certik** [comment]
No, it hasn't.

**Comment by Sumith1896** [comment]
@CodeMaxx Let me know if you need any help on this.

**Comment by CodeMaxx** [comment]
Made a Pull Request.

**Comment by Sumith1896** [comment]
Can close this.

**Comment by CodeMaxx** [comment]
Fixed by #743

**Comment by bollu** [comment]
Is this still open, or is it fixed

**Comment by CodeMaxx** [comment]
It is being fixed in #838

**Comment by bollu** [comment]
Ah, thanks :)

**Comment by Sumith1896** [comment]
Closed via https://github.com/symengine/symengine/pull/898
