### ISSUE TITLE
Distinguish between Basic and Symbol in C wrapper

### ISSUE THREAD

**Issue by ahumenberger** [symengine/symengine#1409]
So far, the C wrapper does not distinguish between the types `Symbol` and `Basic`, it only knows `Basic`. Is there a specific reason for that?
It might be of interest to make this distinction, as some functions need arguments of type `Symbol` or `vec_sym` (e.g. `linsolve`).

**Comment by isuruf** [comment]
That's because the type of the expression is known only at run-time. For C++ functions needing arguments of specific types, we can check that the specific type is given before casting and sending the object to the C++ function.
