### ISSUE TITLE
Strange sympifcation of symbols starting with `inf`

### ISSUE THREAD

**Issue by albop** [symengine/symengine#1413]
This doesn't look like a feature... (or it's not the same result as sympy) :-)

```
In [1]: import engine
In [2]: symengine.sympify("inflation")
Out[2]: inf.0*lation
```

**Comment by albop** [comment]
I was about to say it's in the wrong repository (should be in symengine.py), but then I checked, and the behavior is the same in SymEngine.jl so maybe it is the right repository after all:
```
julia> SymEngine.Basic(:(inflation))
inf.0*lation
```

**Comment by isuruf** [comment]
Yes, it's a bug in our parser code. Happens for `nan` as well. Basically the code checks for strings like `100x` and converts to `100*x` and `inflation` is converted to `inf*lation`. (Printing of `inf` as `inf.0` is another issue)
