### ISSUE TITLE
Symengine as static library

### ISSUE THREAD

**Issue by florian-jean** [symengine/symengine#1421]
Hello, I would like to use symengine as a static library.
As far as I can understand the process to link it to C++ code, it is used as a dynamic library.
Any easy way to do it ?
Thanks

**Comment by isuruf** [comment]
You need to compile symengine as a static library. `cmake -DBUILD_SHARED_LIBS=no`. This is the default option. If you give `cmake -DBUILD_SHARED_LIBS=yes`, it will build dynamic libraries.
