### ISSUE TITLE
[question] INTEGER_CLASS=boostmp doesn't link to boost libs, is this normal?

### ISSUE THREAD

**Issue by yurivict** [symengine/symengine#1425]
With ```INTEGER_CLASS=boostmp``` configure prints these relevant values:
```
INTEGER_CLASS : BOOSTMP
WITH_BOOST: yes
BOOST_INCLUDE_DIRS: /usr/local/include
BOOST_LIBRARIES:
```

BOOST_LIBRARIES is left empty, and ```lib/libsymengine.so``` isn't linked to boost libs.
Is this normal? Can boost really be used as a headers-only library, or something fails here?
(I just don't know boost enough.)

**Comment by isuruf** [comment]
Yeah, only need the headers.
INTEGER_CLASS=boostmp disables arbitrary precision floating point stuff, so use `gmp` or `flint` (flint is faster) if you want arbitrary precision floating point.

**Comment by yurivict** [comment]
Thanks for this information!

If ```flint``` is faster, shouldn't it be made a default then? You have ```gmp``` as a default.

**Comment by certik** [comment]
Also TCMALLOC is faster than the default malloc. What we do is that we turn the correct compiler options by default, but we only require the minimal third party libraries by default. GMP is available on all computers easily, so we only require that. For maximum performance, one has to link with more libraries like flint and tcmalloc.

**Comment by isuruf** [comment]
flint is not a hard dependency yet because there are some issues with building in windows. So symengine can be built without flint. https://github.com/symengine/symengine/issues/877

**Comment by yurivict** [comment]
Thank you for your explanations.
I am working on the FreeBSD port for ```symengine``` (and also ```piranha```). I'll make ```tcmalloc``` and ```flint``` defaults then, because there is no problem linking with them.

**Comment by isuruf** [comment]
Thanks for working on getting symengine on freebsd. If it helps, here's what I use for building symengine for distribution, https://github.com/symengine/symengine-feedstock/blob/tagged/recipe/build.sh#L6-L17 and the packages used https://github.com/symengine/symengine-feedstock/blob/tagged/recipe/meta.yaml#L21-L35

**Comment by yurivict** [comment]
Thanks! This helps with the right build options.

----

I have some more questions:
1. What is ```BFD```? Should there be an option to turn it on?
2. What about ```SYMENGINE_RCP```? Should there be an option for it?
3. ```ECM```? Does this enable extra functionality?
4. Do ```INTEGER_CLASS=piranha``` and ```INTEGER_CLASS=gmpxx``` support arbitrary precision numbers?
5. You said that setting ```INTEGER_CLASS```affects floating point precision. What about integer numbers precision? I guess, it is also affected the same way?

**Comment by certik** [comment]
1. and 2. are for a debug build (i.e., safer, but slower). If you only have one build in freebsd, I would suggest you do the default Release build. If you want to have a Debug build, then you can enable those.

**Comment by isuruf** [comment]
1. It's binutils-dev in debian which is used for stacktraces in debug mode. You probably don't need it since you are building Release
2. SymEngine's RCP can be replaced by Teuchos', for more debugging.
3. libecm-dev on ubuntu. It does enable extra functionality, but those are experimental stuff, not widely used though
4. Yes. They support arbitrary precision reals, complex reals, integers, rationals. gmpxx needs gmp compiled with C++ support.
5. INTEGER_CLASS=boostmp disables arbitrary precision reals and complex reals, but boost is used for arbitrary precision integers and rationals.
