### ISSUE TITLE
as_numer_denom yields segfault when working on -1/sqrt(2)

### ISSUE THREAD

**Issue by tgn3000** [symengine/symengine#1426]
The following produces a segmentation fault. 

RCP<const Basic> num, den;
RCP<const Basic> i1(integer(1)), i2(integer(2));
as_numer_denom(neg(sqrt(div(i1,i2))), outArg(num), outArg(den));

If I remove "neg", then num=1 and den=1/sqrt(2), which are good. Thanks!

**Comment by certik** [comment]
@tgn3000 thanks for the bug report. I can exactly reproduce the behavior that you described. Here is a minimal example:
```c++
#include <symengine/basic.h>
#include <symengine/pow.h>

using SymEngine::Basic;
using SymEngine::integer;
using SymEngine::RCP;

int main(int argc, char *argv[])
{
    SymEngine::print_stack_on_segfault();

    RCP<const Basic> num, den;
    RCP<const Basic> i1(integer(1)), i2(integer(2));

    as_numer_denom(neg(sqrt(div(i1, i2))), outArg(num), outArg(den));

    std::cout << *num << std::endl;
    std::cout << *den << std::endl;

    return 0;
}
```

**Comment by certik** [comment]
@isuruf would you have time to look at this issue? I think this is a big bug that needs to be fixed, because it gives a segfault.

**Comment by tgn3000** [comment]
Hi @certik  I also checked SymEngine's recent features just now, and am happy to see this! Thank you so much for your great work & effort! Cheers!
Gary
