### ISSUE TITLE
Parsing of multiarg functions is broken

### ISSUE THREAD

**Issue by FFroehlich** [symengine/symengine#1444]
I believe that the string `pow` is currently parsed incorrectly when combined with multiplication. Using python bindings to illustrate this issue:
---

**Steps to reproduce:**
```
import symengine as sp
sp.sympify('S4*pow(S5,-1)')
```
**Expected result:**

`S4/S5`

**Obtained result:**

`-1 + S4/S5`

---

`sp.sympify('pow(S5,-1)')` does evaluate correctly to `sp.sympify('S5**(-1)')`.

**Comment by isuruf** [comment]
Fixed in #1211
