### ISSUE TITLE
Solver function

### ISSUE THREAD

**Issue by Magalame** [symengine/symengine#1457]
There has been mention of implementing a solver function (https://github.com/symengine/symengine/issues/268 ), but it seems like symengine is still lacking one. Is it likely to have one someday? 

Thanks!

**Comment by bjodah** [comment]
@Magalame I believe there will be one as soon as someone willing & capable of writing one finds the time (there are no paid employees working on SymEngine). The lead developers are quite busy, but even then they usually manage to find time to review PRs very quickly. Feel free to try to implement it.

**Comment by certik** [comment]
I am happy to review any PRs if somebody implements this.

**Comment by Magalame** [comment]
Thanks for the answer! Unfortunately I don't think I could manage to implement it though :/
