### ISSUE TITLE
std::set_intersection called with unsorted ranges

### ISSUE THREAD

**Issue by bjodah** [symengine/symengine#1463]
A test suite in a library of mine which uses symengine is failing when using `cse` (I caught this bug when compiling using gcc with `_DGLIBCXX_DEBUG` defined).

I've tracked down the error to this line:
https://github.com/symengine/symengine/blob/b3a2159b7e6950726157626069c30712427d55b2/symengine/cse.cpp#L147

The test case is complicated and the library depends on many other 3rd party libraries and I have yet to write a minimal test case for symengine.

<details><summary>Click here to show an excerpt from my 3rd party test log:</summary>
<pre>
/usr/include/c++/8/bits/stl_algo.h:5269:
Error: elements in iterator range [__first1, __last1) are not sorted.

Objects involved in the operation:
    iterator "__first1" @ 0x0x7fffee840910 {
      type = __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<unsigned int*, std::__cxx1998::vector<unsigned int, std::allocator<unsigned int> > >, std::__debug::vector<unsigned int, std::allocator<unsigned int> > > (mutable iterator);
      state = dereferenceable (start-of-sequence);
      references sequence with type 'std::__debug::vector<unsigned int, std::allocator<unsigned int> >' @ 0x0x7fffee840c90
    }
    iterator "__last1" @ 0x0x7fffee840940 {
      type = __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<unsigned int*, std::__cxx1998::vector<unsigned int, std::allocator<unsigned int> > >, std::__debug::vector<unsigned int, std::allocator<unsigned int> > > (mutable iterator);
      state = past-the-end;
      references sequence with type 'std::__debug::vector<unsigned int, std::allocator<unsigned int> >' @ 0x0x7fffee840c90
    }
</pre>
</details>

**Comment by isuruf** [comment]
Thanks for figuring this out. (I vaguely remember symengine being slower than sympy on a huge expression that I encountered in my research.) I'll dig into this. It will help if you could just print the expressions to a file, one expression per line, so that I can read the file and parse them.

**Comment by bjodah** [comment]
Sure, this is looks to be the expressions triggering the failure:
```
-k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
-k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
2*k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
```
sorry for the wait, took a while to reproduce locally (flags, environment variables and all).

**Comment by isuruf** [comment]
@bjodah, can you do,
```
diff --git a/symengine/cse.cpp b/symengine/cse.cpp
index 99ef9042..6c2afb62 100644
--- a/symengine/cse.cpp
+++ b/symengine/cse.cpp
@@ -139,11 +139,19 @@ public:
                           const Container2 &restrict_to_funcset)
     {
         std::vector<unsigned> indices;
+        std::cout << "print ";
         for (auto f : restrict_to_funcset) {
             indices.push_back(f);
+            std::cout << f << " ";
         }
+        std::cout << std::endl;
+
         std::vector<unsigned> intersect_result;
         for (const auto &arg : argset) {
+            for (auto f : arg_to_funcset[arg]) {
+                std::cout << f << " ";
+            }
+            std::cout << std::endl;
             std::set_intersection(indices.begin(), indices.end(),
                                   arg_to_funcset[arg].begin(),
                                   arg_to_funcset[arg].end(),
```
and send me the output when you run this problem? I can't reproduce your issue.

Can you also add a sort for `indices` after https://github.com/symengine/symengine/blob/b3a2159b7e6950726157626069c30712427d55b2/symengine/cse.cpp#L144 and check?

**Comment by bjodah** [comment]
Sure, I'm running gcc-8 in case this is a new addition to their _GLIBCXX_DEBUG features.

This is the output (just before abort) with your debug patch applied:
```
exprs:-k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
-k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
2*k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
...
print 
1 
1 
1 
1 
...done
print 4 5 6 7 8 2 
2 4 5 6 7 8 
Aborted (core dumped)
```
(and the `...done`, `...` & `exprs:` parts are obviously debug prints from my lib)

Adding:
```
        std::sort(std::begin(indices), std::end(indices));
```
fixes the issue, and this is what is printed instead:
```
exprs:-k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
-k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
2*k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
...
print 
1 
1 
1 
1 
...done
print 4 5 6 7 8 2 
2 4 5 6 7 8 
2 6 7 8 
print 
1 4 5 
1 3 6 7 8 
print 7 8 
3 4 5 7 8 
3 7 8 
3 7 8 
print 




print 
6 
6 7 
PASSED
```
(and so on...)

<details><summary>My cmake config of symengine</summary><pre>
$ CXXFLAGS="-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC" cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/syme-929022f-dbg -DWITH_BFD:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DWITH_LLVM:BOOL=ON -DBUILD_TESTS:BOOL=ON -DBUILD_BENCHMARKS:BOOL=OFF -DSYMENGINE_LINK_LLVM_STATIC=yes ../symengine-929022f/
-- cotire 1.7.8 loaded.
--------------------------------------------------------------------------------

+-------------------------------+
| Configuration results SUMMARY |
+-------------------------------+

CMAKE_C_COMPILER:   /usr/bin/gcc-8
CMAKE_CXX_COMPILER: /usr/bin/g++-8
CMAKE_BUILD_TYPE: Release
CMAKE_CONFIGURATION_TYPES: 
CMAKE_CXX_FLAGS_DEBUG:   -Wall -Wextra -Wno-unused-parameter -fno-common -g -ggdb -std=c++11 -fPIC -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wno-unknown-pragmas
CMAKE_CXX_FLAGS_RELEASE: -Wall -Wextra -Wno-unused-parameter -fno-common -O3 -march=native -ffast-math -funroll-loops -std=c++11 -fPIC -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DNDEBUG -Wno-unknown-pragmas
CMAKE_INSTALL_PREFIX: /opt/syme-929022f-dbg
BUILD_SHARED_LIBS: ON
INTEGER_CLASS : GMP
HAVE_SYMENGINE_GMP: yes
WITH_SYMENGINE_ASSERT: no
WITH_SYMENGINE_RCP: yes
WITH_SYMENGINE_TEUCHOS: yes
WITH_COTIRE: yes
HAVE_GCC_ABI_DEMANGLE: yes
HAVE_C_FUNCTION_NOT_FUNC: no
HAVE_DEFAULT_CONSTRUCTORS: yes
HAVE_SYMENGINE_NOEXCEPT: yes
HAVE_SYMENGINE_IS_CONSTRUCTIBLE: yes
HAVE_SYMENGINE_RESERVE: yes
HAVE_SYMENGINE_STD_TO_STRING: TRUE
WITH_SYMENGINE_THREAD_SAFE: no
BUILD_TESTS: ON
BUILD_BENCHMARKS: OFF
BUILD_BENCHMARKS_NONIUS: no
WITH_GMP: yes
GMP_INCLUDE_DIRS: /usr/include/x86_64-linux-gnu
GMP_LIBRARIES: /usr/lib/x86_64-linux-gnu/libgmp.so
WITH_BFD: ON
BFD_INCLUDE_DIRS: /usr/include
BFD_LIBRARIES: /usr/lib/x86_64-linux-gnu/libbfd.so;/usr/lib/x86_64-linux-gnu/libiberty.a;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so
LINKH_INCLUDE_DIRS: /usr/include
EXECINFO_INCLUDE_DIRS: /usr/include
WITH_ECM: no
WITH_PRIMESIEVE: no
WITH_FLINT: no
WITH_ARB: no
WITH_MPFR: no
WITH_PIRANHA: no
WITH_LLVM: ON
LLVM_INCLUDE_DIRS: /usr/lib/llvm-6.0/include
WITH_BOOST: no
WITH_PTHREAD: no
WITH_MPC: no
WITH_TCMALLOC: no
WITH_OPENMP: no
WITH_VIRTUAL_TYPEID: no

--------------------------------------------------------------------------------

-- Configuring done
-- Generating done
-- Build files have been written to: /build/syme-929022f-dbg/build
</pre>
</details>

**Comment by bjodah** [comment]
Looking at my log again I'm not certain that the expression that I gave is the one causing the error (that "...done" part shouldn't be there), I'll look into this later tonight and I'll see if I can figure out if it's another expression causing this.

**Comment by bjodah** [comment]
I was using '\n' in my print statments instead of `std::endl` (so I wasn't flushing). This should be the problematic case:
```
-k1*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
-k1*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
2*k1*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)
k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)**2 + (-3/2)*k1*__conc__H2*sqrt(__conc__Br2)/(__conc__Br2 + k2*__conc__HBr)
k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)**2 + (-3/2)*k1*__conc__H2*sqrt(__conc__Br2)/(__conc__Br2 + k2*__conc__HBr)
-2*k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)**2 + 3*k1*__conc__H2*sqrt(__conc__Br2)/(__conc__Br2 + k2*__conc__HBr)
k2*k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)**2
k2*k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)**2
-2*k2*k1*__conc__H2*__conc__Br2**(3/2)/(__conc__Br2 + k2*__conc__HBr)**2
```
I turned this into a test case which triggers locally on my machine with _GLIBCXX_DEBUG defined. I pushed the test case and the fix with the added the sort call in gh-1465.
