### ISSUE TITLE
Segmentation fault due to undefined symbol

### ISSUE THREAD

**Issue by mardukbp** [symengine/symengine#1479]
I installed SymEngine with `conda install symengine -c symengine -c conda-forge`. Then entered `USE_SYMENGINE=1 isympy` and got 

```
$HOME/miniconda3/lib/python3.6/site-packages/symengine/lib/symengine_wrapper.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN9SymEngine17LLVMDoubleVisitor6bvisitERKNS_5GammaE
Segmentation fault
```

`nm -gC symengine_wrapper.cpython-36m-x86_64-linux-gnu.so` reveals that this symbol corresponds to 
`U SymEngine::LLVMDoubleVisitor::bvisit(SymEngine::Gamma const&)`
 
I hope this information helps.

**Comment by isuruf** [comment]
can you send the output of `conda list`

**Comment by isuruf** [comment]
Do, `conda install python-symengine -c symengine -c conda-forge`

**Comment by mardukbp** [comment]
In the end I reinstalled conda and now it works. Thanks for your help!

**Comment by certik** [comment]
@mardukbp thanks for reporting it.

@isuruf do you know what the issue was? Different compilers for symengine vs python-symengine?

**Comment by isuruf** [comment]
@certik, symengine and python-symengine in `conda-forge` channel was compiled without llvm. Using `symengine` from `symengine` channel and `python-symengine` from `conda-forge` channel will lead to errors like this

**Comment by certik** [comment]
@isuruf I see, thanks for the clarification.
