### ISSUE TITLE
.evalf() cannot evaluate when symbols are present

### ISSUE THREAD

**Issue by Melisius** [symengine/symengine#1488]
import symengine
    A = symengine.Symbol("A", real=True)
    B = symengine.Rational(3,10)*A
    B.evalf()

    RuntimeError: Symbol cannot be evaluated.

This might be the expected behavior?

This result is quite different from Sympy, that would return:

   0.3*A

**Comment by certik** [comment]
Thanks @isuruf for fixing it!
