### ISSUE TITLE
Write and test good C wrappers for CSymPy

### ISSUE THREAD

**Issue by certik** [symengine/symengine#149]
We need to figure out a good C API, which would probably just be lots of functions like `basic_diff` which would accept a pointer as a first argument, thus emulating our objects.

Then we need to test it, using C.

This will be very good for writing higher lever language wrappers, like Julia, Ruby, Matlab, ...

**Comment by Sumith1896** [comment]
I think this can be closed now.
The issue for discussion on improving C wrappers here: https://github.com/symengine/symengine/issues/494
