### ISSUE TITLE
C++ Operator overloading for arithmetic operations on symengine symbols

### ISSUE THREAD

**Issue by SylvainCorlay** [symengine/symengine#1509]
Have you considered using C++ operator overloading for arithmetic operation on symengine symbols?

This would make the C++ API much simpler to use than with e.g. `Symengine::add`...

**Comment by isuruf** [comment]
There's the expression class in expression.h and operators are overloaded there. It'll be weird to overload operators on pointer classes, so the Expression class stores the pointer and does operator overloading

**Comment by SylvainCorlay** [comment]
This would also enable the natural use of symengine symbols as a scalar type for array structures such as `xtensor`. I would find it cool to make similar experiments to e.g. [this](http://www.stochasticlifestyle.com/fun-julia-types-symbolic-expressions-ode-solver/) with `xtensor` and `symengine`.

**Comment by SylvainCorlay** [comment]
Ah, do you think that the `expression` would be a better candidate for a richer C++ notebook example?

**Comment by isuruf** [comment]
Yes, definitely.

**Comment by certik** [comment]
See the discussion here:

https://github.com/symengine/symengine/issues/1502#issuecomment-461845642

that explains why we don't use it for the core of SymEngine, but why it makes perfect sense to use it for a user facing API as well as Jupyter notebooks.
