### ISSUE TITLE
Jupyter rich mime type rendering for symengine expression

### ISSUE THREAD

**Issue by SylvainCorlay** [symengine/symengine#1510]
The Jupyter C++ kernel allows for rich mime type rendering of user-defined types.

The only thing to implement is the function `json mime_bundle_repr(const foo&)` where `foo` is the user type, in the same namespace as `foo`. This is picked up by ADL. `mime_bundle_repr` should return a JSON mime bundle repl.

See e.g. for a simple image class:

https://xeus-cling.readthedocs.io/en/latest/rich_display.html#example-image-png-representation-of-an-image-class

It could be interesting to do this for symengine expression, returning both plain text and e.g. latex representation to be rendered with mathjax.

**Comment by isuruf** [comment]
Yes, I agree we should do this, but the issue was that I couldn't find a macro like `__XEUS_CLING__` to tell if it's a xeus cling session or not.

**Comment by SylvainCorlay** [comment]
I agree such a macro could be useful.

However, do you want these functions to not exist when not running xeus-cling? They could be in a separate header.

**Comment by certik** [comment]
I would keep them there always, as they would be part of the `Expression` class, which is a user facing API anyway, so it should be as user friendly as possible by default.

**Comment by isuruf** [comment]
I meant I don't want to add a dependency on `nlohmann/json.hpp` as you need it to add the rendering.

**Comment by SylvainCorlay** [comment]
We could define it in a separate header, included in the `Expression` header when in XEUS_CLING...
