### ISSUE TITLE
Requesting implementing "simplify" method in SymPy

### ISSUE THREAD

**Issue by RWTHsniper** [symengine/symengine#1520]
Dear whom it may concern,

I am a graduate from RWTH Aachen and enjoying using SymEngine for quantitative finance.
I found it very interesting. This is the most active community of symbolic math in Julia.

I think that having "simpliy" method in SymPy available in this library will be quite useful.
(https://docs.sympy.org/latest/tutorial/simplification.html)
That is because we can have a readable mathematical expression of an expanded expression.
We can use "simplify" to check an analytic solution of an equation.
In my case, I am using SymEngine to check the solution of my ordinary-differential equation.
As I cannot have "simplify" in SymEngine, I check the residual of an equation using Monte-Carlo method.

There is no doubt that SymEngine is a great library.
I believe that having "simplify" method will be useful and make SymEngine to be loved by many people.

Regards,

Jaeyong Jung.

P.S. I attached my test code for checking the analytic solution of my equation using Monte-Carlo method.
 ```
#=
Author: Jaeyong Jung
I wrote this script to check the analytic solution of the following O.D.E.
B' = 1/2*(sig*B)^2-k*B-1
where k,sig,u are parameters, and tau is the variable of B
=#

using SymEngine
@vars k sig u tau
using Statistics

r = sqrt(k^2+2.0*sig^2) # It should be specified!!!
B_num = u*(k+r)+2.0-(u*(k-r)+2.0)*exp(r*tau)
B_deno = (sig^2*u-k-r)*(1.0-exp(r*tau))+2*r
B=B_num/B_deno
# B = (u*(k+r)+2-(u*(k-r)+2)*exp(r*tau))/((sig^2*u-k-r)*(1-exp(r*tau))+2*r)
Bt = diff(B,tau)
B_res = Bt-(0.5*(sig*B)^2-k*B-1)
B_res = expand(B_res)

# I use Monte-Carlo method to check whether B_res is zero
nums = 200 # Number of iterations for Monte-Carlo method
B_avg = mean([subs(B_res,k=>rand(),r=>rand(),
sig=>rand(),u=>0#=rand()=#,tau=>rand())] for i in 1:nums)
print("Average of the residual is ",B_avg[1])
```

**Comment by certik** [comment]
@RWTHsniper thanks for the feedback. I am very happy that SymEngine is useful in Julia. That was precisely my hope that by doing it strictly in C++, it can be exposed to all other languages and so we can all collaborate on a single code base and benefit both Python and Julia (and others).

I would definitely like `simplify` to be implemented. It's a huge task actually, there are a lot of algorithms in SymPy that are needed for `simplify` to work.

We should identify the steps that are needed to be implemented first, and try to get GSoC students working on them. Then down the road we'll eventually have `simplify` also, initially perhaps not as powerful as in SymPy, but we'll get there.

**Comment by silveiralucas** [comment]
I am current using SymPy in my master thesis in Wind Energy. However, the time take to simplify the equations is preventing to move forward and I will most likely have to move to a commercial tool. I have tried moving towards SymEngine, but the lack of the simplifying tool prevents significant running time gains.

**Comment by rikardn** [comment]
There is now both a `refine` function and a `simplify` function in symengine. Both have a similar scope to the corresponding functions in mathematica and can work with assumptions. They don't support much yet, but it should be fairly straight forward to add more refinement and simplification rules. Pull requests would be welcome!
