### ISSUE TITLE
Add support for more functions to Lambdify (with llvm backend)

### ISSUE THREAD

**Issue by ichumuh** [symengine/symengine#1521]
Hi,
would it be possible to make Lambdify, with llvm backend, support more functions?
In particular I could really use `floor`, `ceiling`, `sign` and `atan2`.

**Comment by isuruf** [comment]
Sure. PRs are welcome.
`floor, ceiling` should be the same as `sin` at https://github.com/symengine/symengine/blob/master/symengine/llvm_double.cpp#L483

`sign` and `atan2` are slightly more complicated, but I can help you with that.

**Comment by isuruf** [comment]
Fixed in #1522. Thanks for the PR
