### ISSUE TITLE
Coefficient for n^0 always zero

### ISSUE THREAD

**Issue by ahumenberger** [symengine/symengine#1523]
Applying `coeff` to some expression `b` with some arbitrary `x` and `n=0` always returns `0`.
E.g. `coeff(2 + a + a^2, a, 0) = 0`, but should be `2`.
https://github.com/symengine/symengine/blob/b3a2159b7e6950726157626069c30712427d55b2/symengine/visitor.cpp#L63

This behaviour is also required by the tests:
https://github.com/symengine/symengine/blob/95834bb8a86952ee26446220d0fac4739ec6bb1f/symengine/tests/basic/test_basic.cpp#L947

**Comment by isuruf** [comment]
PRs are welcome to fix this. If a test requires the current behaviour, the test is wrong

**Comment by isuruf** [comment]
Fixed in #1524. Thanks
