### ISSUE TITLE
Memory leak when using LLVMDoubleVisitor

### ISSUE THREAD

**Issue by bjodah** [symengine/symengine#1525]
Consider this minimal example:

```c++
#include <cstdlib>
#if defined(USE_LLVM)
#  include <symengine/llvm_double.h>
#else
#  include <symengine/lambda_double.h>
#endif

namespace se = SymEngine;

int main(int argc, char **argv) {
    if (argc != 2) {
        return 1;
    }
    const int N = std::atoi(argv[1]);

    double d;
    se::RCP<const se::Basic> x, y, r;
    x = se::symbol("x");
    y = se::symbol("y");

    for (int i=0; i<N; i++) {
        r = se::add(se::mul(se::integer(i), x), se::mul(se::integer(i), y));
#if defined(USE_LLVM)
        se::LLVMDoubleVisitor v;
#else
        se::LambdaRealDoubleVisitor v;
#endif
        v.init({x, y}, *r);
        d = v.call({1.0, 2.0});
        if (std::abs((d - 3.0*i)/(3.0*i)) > 1e-12) {
            return 2;
        }
    }
    return 0;
}
```
and running the executable as:
```shell
$ /usr/bin/time -v ./a.out 5000
```
Maximum resident set size shouldn't grow with the size of the argument, but when compiled with `-DUSE_LLVM`, it grows linearly, indicating that all resources are not being freed upon calling `~LLVMDoubleVisitor()`.

I see a bunch of raw pointers in LLVMDoubleVisitor being assigned to in `init(...)` but I don't see the corresponding calls freeing them... Am I missing something?

EDIT: I just saw that this might be well known, and still on the "TODO list" since there was an unchecked checkbox in the [original PR](https://github.com/symengine/symengine/pull/1094), anyways this issue might be useful as a reminder and a test case.

**Comment by isuruf** [comment]
I ran the same command and the maximum resident set size doesn't change (around 21000 kb) as the argument is increased

**Comment by certik** [comment]
Thanks. We should fix it.
