### ISSUE TITLE
Parsing "-a^2" yields a^2

### ISSUE THREAD

**Issue by ahumenberger** [symengine/symengine#1529]
`parse("-1**2")` yields `1`
`parse("-a**2")` yields `a^2`

As a reference, SymPy returns `-1` and `-a^2` respectively.

**Comment by isuruf** [comment]
Is this with master?

**Comment by ahumenberger** [comment]
Yes. I didn't check the official release.

**Comment by isuruf** [comment]
Thanks for the bug report. (No need to check the official release which is old now)
