### ISSUE TITLE
Implement Logic and basic Assumption classes

### ISSUE THREAD

**Issue by certik** [symengine/symengine#154]
- The basic logic classes, And, Or, Not, True, False. It may also be useful to have Implies and Equivalent. They should behave more or less exactly the way they do in SymPy.
- A version of `Q`
- The ability for things like `Q.positive(expr)` to be represented, where `expr` is a SymPy (not CSymPy) expression (see #153).

**Comment by Sumith1896** [comment]
I have going over the `boolalg` in SymPy.
So how do we do this?

My design thoughts:
Every symbol can be converted to a boolean variable.
We'll have a base class BooleanFormula similar to basic.
Then we shall have `And`, `Or` etc in a hierarchical fashion.
(Analogous to `Add`, `Mul` etc)

**Comment by asmeurer** [comment]
If you don't want to be able to represent boolean formulas in arbitrary ways there are more efficient ways to represent things (analogous to the way that polynomials can be represented more efficiently than general expressions).

**Comment by Sumith1896** [comment]
Two things:
1) Do we not support arbitrary boolean expressions or convert every expression to fixed form(this conversion may be heavy but manipulations thereon will be efficient)?
2) Are these efficient forms `SOP` or `POS` or something else?

**Comment by asmeurer** [comment]
CNF is the most important one, since that's what SAT solvers use.

**Comment by isuruf** [comment]
@asmeurer, 
What do you mean by 
> expr is a SymPy (not CSymPy) expression

There is already SymPy functions which can be used in SymEngine via `FunctionWrapper`. Are there anything else?

**Comment by akaviaLab** [comment]
Hello. Is there any progress on this issue?
Thank you

**Comment by certik** [comment]
Yes, there is an Assumption class in SymEngine now and the refine() function.

**Comment by rikardn** [comment]
Checkout the logic functions in `logic.h`. The assumptions are used by `refine`, `simplify` and the "test"-functions (like `is_real`,`is_positive` etc).

**Comment by akaviaLab** [comment]
Thank you.
Should this be closed then?
