### ISSUE TITLE
Problems with -march=native

### ISSUE THREAD

**Issue by bjodah** [symengine/symengine#1542]
`-march=native` is giving me problems on a CI server when building release version of current SymEngine master:
<details>
<pre>
+ export SYME_DIR=$(pwd)/ci_cache/syme-6847e8a-rel
+ if [ ! -d $SYME_DIR ]; then (cd /tmp; $REPO/.ci/get_symengine.sh $SYME_DIR $SYMENGINE_COMMIT); fi
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- Check for working C compiler: /usr/bin/clang-6.0
-- Check for working C compiler: /usr/bin/clang-6.0 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-6.0
-- Check for working CXX compiler: /usr/bin/clang++-6.0 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:75 (message):
  Compiler does not support C++11 constructs.

  CXX11 Error Log :

  Change Dir: /tmp/symengine-build/cxx/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_2e882/fast"

  /usr/bin/make -f CMakeFiles/cmTC_2e882.dir/build.make
  CMakeFiles/cmTC_2e882.dir/build

  make[1]: Entering directory '/tmp/symengine-build/cxx/CMakeFiles/CMakeTmp'

  Building CXX object CMakeFiles/cmTC_2e882.dir/checkcxx11.cpp.o

  /usr/bin/clang++-6.0 -Wall -Wextra -Wno-unused-parameter -O3 -march=native
  -funroll-loops -std=c++11 -fPIC -o
  CMakeFiles/cmTC_2e882.dir/checkcxx11.cpp.o -c
  /tmp/symengine-6847e8a38f3ab85d27f300bb8caeee65e8889620/cmake/checkcxx11.cpp

error: unknown target CPU 'pentium2'
</pre>
</details>

I see that `-march=native` is dropped with a string replace in `CMakeLists.txt`

My question:

* Can't we just get rid of `-march=native` from UserOverride.cmake?
* Instead we could provide an instructive example in the README how to set e.g. CMAKE_CXX_FLAGS so that it compiles with `-march=native` for those who want to do so?

xref #474

**Comment by isuruf** [comment]
@certik, what do you think?

**Comment by certik** [comment]
So I would say this is a bug on the CI host. As such, we need ways to workaround their bug, and disable `-march=native`. Is that an ok workaround?

However, to disable it by default will lead to people not enabling it. That has been my experience. And thus getting a slow performance.

**Comment by isuruf** [comment]
@bjodah, do you mind running the benchmarks with and without `-march=native`. I suspect we won't see any difference in symengine. (There aren't many floating point/integer operations to optimize.)

**Comment by certik** [comment]
I would expect to see quite a bit of difference, as `-march=native` is not specifically floating point related (that's what `-ffast-math` is for).

**Comment by isuruf** [comment]
> -march=native is not specifically floating point related 

Sure, but most of the options are floating point related. Like sse4, avx2, avx512 etc.

Here's a run with `-march=native`

```
(base) isuru@isuru:~/projects/symengine/build1$ ./benchmarks/expand2 20
2194ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build1$ ./benchmarks/expand2 20
2182ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build1$ ./benchmarks/expand2 20
2297ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build1$ ./benchmarks/expand2 20
2156ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build1$ ./benchmarks/expand2 20
2142ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build1$ ./benchmarks/expand2 20
2160ms
number of terms: 14112
```

Here's without `-march-native`
```
(base) isuru@isuru:~/projects/symengine/build2$ ./benchmarks/expand2 20
2339ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build2$ ./benchmarks/expand2 20
2157ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build2$ ./benchmarks/expand2 20
2355ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build2$ ./benchmarks/expand2 20
2140ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build2$ ./benchmarks/expand2 20
2147ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build2$ ./benchmarks/expand2 20
2184ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build2$ ./benchmarks/expand2 20
2161ms
number of terms: 14112
(base) isuru@isuru:~/projects/symengine/build2$ ./benchmarks/expand2 20
2149ms
number of terms: 14112
```

**Comment by certik** [comment]
Ok, it seems the difference is not as big as I thought. 

Still, what is a disadvantage of keeping `-march=native` the default? As long as we can easily turn it off on the problematic CI.

**Comment by isuruf** [comment]
> Still, what is a disadvantage of keeping -march=native the default?

One disadvantage is that I've seen some package managers package symengine without turning this option off.

Another is that `-march=native` generates some instructions that the assembler can't handle. Eg: https://github.com/symengine/symengine/issues/474. (This shows that `-march=native` does generate better code with new instructions for symengine, but I haven't seen any noticeable difference in benchmarks)

**Comment by certik** [comment]
@isuruf regarding #474 that is a bug in the toolchain on a Mac, that they had a linker that couldn't handle the (correct) instructions generated by the compiler.

I can see your point. I guess the default options for a library like SymEngine should be so that when somebody compiles it on one machine, it will work on another. So I am ok with making `-march=native` optional, as long as we document in the README how to compile SymEngine to obtain maximum performance.
