### ISSUE TITLE
Should `0 * 4.0` return `0` or `0.0` ?

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1559]
Since the operand on the left is exact, the result should be exact, IMO.

cc @mydatamodels

**Comment by bjodah** [comment]
FWIW I think `0` is sensible.

**Comment by certik** [comment]
Python returns 0.0:
```
>>> 0 * 4.0
0.0
>>> 4.0 * 0
0.0
```
I am fine either way, but I would make sure that `0 * 4.0` returns the same thing as `4.0 * 0`.

**Comment by isuruf** [comment]
Btw, SymPy gives `0`

> I am fine either way, but I would make sure that 0 * 4.0 returns the same thing as 4.0 * 0.

Of course. Multiplication should be commutative.

**Comment by certik** [comment]
If sympy gives 0, we should also give 0 I think.

**Comment by rikardn** [comment]
Currently this is not what symengine gives:

```python
>>> import symengine
>>> a = symengine.Integer(0)
>>> b = symengine.RealDouble(0.0)
>>> a * b
0.0
```

I'll mark this as a bug.
