### ISSUE TITLE
Wrap polygamma in C

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1560]

**Comment by mattfidler** [comment]
If you do this, you may want to use the `R` equivalent function `psigamma` which reverses the arguments (unfortunately).

**Comment by mattfidler** [comment]
With a `s4` method of course.

**Comment by isuruf** [comment]
We can do that in the R package. In the C wrappers, we should keep the same interface as the C++ interface.

**Comment by mattfidler** [comment]
Thanks @isuruf.  For some reason I thought I was still in the `R` library.

**Comment by mattfidler** [comment]
Thank you @isuruf  and @Marlin-Na 

I appreciate the support.  Let me know when it gets in the R api so I can change the code there.
