### ISSUE TITLE
parsing of doubles depends on locale

### ISSUE THREAD

**Issue by lkeegan** [symengine/symengine#1566]
### issue
The parser assumes that a double has a `'.'` as the decimal separator:
https://github.com/symengine/symengine/blob/f7e253fdde1064584ea30728dd6430fc74d596d5/symengine/parser/parser.ih#L100
and if it finds one, it uses `strtod` to convert the string into a double.

This works fine, unless the locale has been set to one where a `','` is used as the separator instead, then `strtod` will incorrectly convert e.g. `3.142` to `3`, since it uses the locale defined decimal separator:
> `strtod` Parses the C-string str interpreting its content as a floating point number (according to the current locale) and returns its value as a double
http://www.cplusplus.com/reference/cstdlib/strtod/

### to reproduce
add the line
```
    std::setlocale(LC_NUMERIC, "de_DE.UTF-8");
```
to https://github.com/symengine/symengine/blob/f7e253fdde1064584ea30728dd6430fc74d596d5/symengine/tests/basic/test_parser.cpp#L586
and the "Parsing: doubles" test will fail.

### solution
One solution might be to set the locale to the default 'C' one within the parser:
```
std::locale old_locale = std::locale::global(std::locale::classic());
// parser code here
std::locale::global(old_locale);
```
Alternatively just adding a warning that the locale should not be set to something other than the default one somewhere in the docs/wiki would be nice to avoid other users from stumbling across this problem.

Thanks for a great library!

**Comment by isuruf** [comment]
I tried reproducing, and couldn't make the test fail. Is it just the `std::setlocale(LC_NUMERIC, "de_DE.UTF-8");` that is needed?

**Comment by lkeegan** [comment]
Maybe you don't have the `de_DE.UTF-8` locale on your system? (I think an invalid setlocale call is just silently ignored)

Here is a fork with the extra line:

https://github.com/symengine/symengine/compare/master...lkeegan:master

and a simple travis build showing the failing test:

https://travis-ci.org/lkeegan/symengine/builds/561374241
