### ISSUE TITLE
Use SymPy to do the printing

### ISSUE THREAD

**Issue by asmeurer** [symengine/symengine#157]
CSymPy has (IMO) broken printing, e.g., 

```py
In [6]: x = csympy.Symbol('x')

In [7]: 2*x
Out[7]: 2x

In [8]: 2x
  File "<ipython-input-8-2e585cac9259>", line 1
    2x
     ^
SyntaxError: invalid syntax
```

Instead of reinventing printing, it should just use SymPy's printing. At the very least it should use the SymPy printing architecture, which is very extensible to different kinds of printers.

**Comment by isuruf** [comment]
`StrPrinter` follows SymPy's printing architecture and is faster than SymPy.
