### ISSUE TITLE
Implement setup.py and add CSymPy to Pypi

### ISSUE THREAD

**Issue by certik** [symengine/symengine#160]
`python setup.py install` should automatically figure out the paths to Python dev libraries, path to Cython, call proper cmake underneath, and install into the right location. 

That should make things super easy for people that want to use CSymPy from Python.

TODO:
- [x] fix #197 first.
- [x] implement `setup.py` (#247)

**Comment by isuruf** [comment]
SymEngine is in PyPI with wheels now
