### ISSUE TITLE
Lambdify with other precision?

### ISSUE THREAD

**Issue by stephweissm** [symengine/symengine#1605]
I'm wondering if it's possible to provide versions of Lambdify where backend='llvm' also takes precision as an argument? I'm asking since I'm interested in computing a reference solution using "long double". Also, being able to calculate using 32-bit precision would be interesting since I have some CUDA code which I run on consumer graphics cards (batched LU decomposition), not having to convert back and forth would probably shave off some computational time.

**Comment by bjodah** [comment]
If you're doing work using CUDA you might also be interested in exploring the possibility of using LLVM's nvptx backend.

**Comment by certik** [comment]
Thanks @isuruf for implementing it!
