### ISSUE TITLE
CMake summary report, not clear what flags are used.

### ISSUE THREAD

**Issue by bjodah** [symengine/symengine#1618]
Here's a minor thing that could(?) potentially be improved. For a debug build of mine, cmake reports:
```
+-------------------------------+
| Configuration results SUMMARY |
+-------------------------------+

CMAKE_C_COMPILER:   /usr/bin/gcc-8
CMAKE_CXX_COMPILER: /usr/bin/g++-8
CMAKE_BUILD_TYPE: Debug
CMAKE_CONFIGURATION_TYPES: 
CMAKE_C_FLAGS:           
CMAKE_CXX_FLAGS:         -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -Og -ggdb3 -UNDEBUG
CMAKE_CXX_FLAGS_DEBUG:   -Wall -Wextra -Wno-unused-parameter -fno-common -g -ggdb -std=c++11 -fPIC -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wno-unknown-pragmas
CMAKE_CXX_FLAGS_RELEASE: -Wall -Wextra -Wno-unused-parameter -fno-common -O3 -funroll-loops -std=c++11 -fPIC -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DNDEBUG -Wno-unknown-pragmas
...
```
It's not obvious what flags will get passed to the compiler:
Is it `CMAKE_CXX_FLAGS`? or `CMAKE_CXX_FLAGS_DEBUG`? (and why is `CMAKE_CXX_FLAGS_RELEASE` echoed when `CMAKE_BUILD_TYPE` is "Debug").

Perhaps I'm missing some finer detail here?

**Comment by isuruf** [comment]
If it's a single-configuration generator then `${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}` is used in debug mode which is selected when running cmake.
If it's a multi-configuration generator, then it depends on the mode selected when running the build.

**Comment by certik** [comment]
Yeah, CMake is quite complicated this way. @bjodah if you have some ideas how to improve our summary output, go ahead and let us know, I am open for improvements.

**Comment by bjodah** [comment]
I see, I suspected I was missing some CMake-ism, thank you @isuruf for making it clear.
@certik sorry, no, my CMake skills are quite limited.
