### ISSUE TITLE
license for bison parser

### ISSUE THREAD

**Issue by Marlin-Na** [symengine/symengine#1626]
It seems that that the generated bison license has copyright notice [[1](https://github.com/symengine/symengine/blob/master/symengine/parser/parser.tab.cc)], [[2](https://github.com/symengine/symengine/blob/master/symengine/parser/parser.tab.hh)] that are not
included in our `LICENSE` file.

I also realized we may not copy it as is since it is GPL, but it has the following exception:

```
/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */
```

Should we modify the terms and include it in `LICENSE`?

**Comment by Marlin-Na** [comment]
ping @certik

**Comment by certik** [comment]
Thanks for the reminder. Yes, we should add a note in our LICENSE that those two files are under GPL, but that the exception in there gives us the right to distribute SymEngine as BSD.

**Comment by certik** [comment]
Thanks!
