### ISSUE TITLE
Porting symengine to Android?

### ISSUE THREAD

**Issue by udexon** [symengine/symengine#1638]
Has anyone tried porting symengine to Android?

I added the following to `CMakeLists.txt` of the target project (using Android Studio NDK):

```
get_filename_component(SYMENGINE_ROOT_DIR
    ${CMAKE_CURRENT_SOURCE_DIR}/deps/symengine ABSOLUTE)
add_subdirectory(${SYMENGINE_ROOT_DIR}
```

The original `CMakeLists.txt` is from:

https://github.com/sfalexrog/Imgui_Android/tree/master/ImguiDemoSdl/src/main/cpp

This is an interesting port of Imgui (an OpenGL / Vulkan GUI module) to Android. If we can port symengine together with Imgui Android, then it would be a powerful (hopefully) game / 3D simulation engine complete with computer algebra functionalities.

I made the following changes to symengine  `CMakeLists.txt` as I could not find a solution to the false error (I think) due to `CXX11`:

```
if (NOT ${CXX11})
	# message(FATAL_ERROR "Compiler does not support C++11 constructs. \n"
	#	"CXX11 Error Log : \n${CXX11_ERROR_LOG}")
    message("${CMAKE_CURRENT_BINARY_DIR}/cxx" "${CMAKE_SOURCE_DIR}/cmake/checkcxx11.cpp"
	CMAKE_FLAGS "-DCOMPILE_DEFINITIONS=${CMAKE_CXX_FLAGS_RELEASE}")
endif()
```

The `cmake` terminated with the following errors:

```
CMake Error: Internal CMake error, TryCompile configure of cmake failed
  CMake Error at /home/hongwu/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
    Could NOT find GMP (missing: GMP_LIBRARIES GMP_INCLUDE_DIRS)
  Call Stack (most recent call first):
    /home/hongwu/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
    deps/symengine/cmake/FindGMP.cmake:19 (find_package_handle_standard_args)
    deps/symengine/CMakeLists.txt:214 (find_package)
  ```

I located the following GMP script for Android:

https://github.com/Rupan/gmp/blob/master/build/compile-gmp-arm.sh

I downloaded GMP source code from:

https://gmplib.org/

I am now planning to create a CMake script for GMP so that it would use the same Android toolchains as `symengine`.

Can anyone help? Any tips? Any better ideas?

**Comment by isuruf** [comment]
Try using Boost instead of GMP. You can use `-DINTEGER_CLASS=boostmp`.

**Comment by udexon** [comment]
I decided to go ahead with compiling GMP using Android NDK, as I found out Boost Multiprecision library is wrapped as libmpfr-dev in Ubuntu, which sounds like a lot of work to replicate in Android.
After a few hours of trials, the errors as as shown in the log file here:
https://github.com/udexon/PhosCloudless/tree/master/Imgui_SymEngine_Android
The screen shot shows that I successfully compiled GMP 6.1.2 using Android cross compiler tools -- I hope. The script I used is attached too, as well as the modified `CMakelists.txt` for SymEngine.
For some reasons, Android Studio Make Project terminated with errors, complaining that GMP reference could not be found, indicating possible architecture mismatch, I guess.
Any suggestions?

**Comment by certik** [comment]
@udexon, it looks like you are not linking to the GMP properly, so the linker cannot find the symbols.

What is the native arbitrary large integer library for Android? We would be happy to support any library that provides large integers that is better supported on Android if GMP or Boost is not.

**Comment by udexon** [comment]
I thought SymEngine needs GMP?
I have made some changes to `CMakelists.txt` to include `libgmp*.a` instead of `libgmp*.so`, where the former is needed during linking, and the latter is needed during run-time -- a tricky business for Android.
https://github.com/udexon/PhosCloudless/tree/master/Imgui_SymEngine_Android
So now SymEngine compiles OK with GMP on Android.
I have disabled most of the tests in SymEngine as they need libgmp*.so.

**Comment by isuruf** [comment]
If you are linking to `libgmp.a` during linking, you don't need `libgmp*.so` at runtime.

> I thought SymEngine needs GMP?

No, SymEngine can use GMP or BoostMP.

> I found out Boost Multiprecision library is wrapped as libmpfr-dev in Ubuntu

On Ubuntu, BoostMP uses GMP and MPFR, but that's optional. You can use BoostMP without GMP and MPFR and use it as header only.

**Comment by udexon** [comment]
Just to mention that, while trying to compile GMP with armv7a, the following bug appeared:
https://github.com/udexon/PhosCloudless/blob/master/Imgui_SymEngine_Android/gmp_armv7a_add_lo_bug.png
```
Making all in mpn
make[2]: Entering directory '/home/hongwu/devel/2020/Android/gmp_android/gmp-master/gmp-6.2.0/mpn'
make[2]: *** No rule to make target 'add.lo', needed by 'libmpn.la'.  Stop.
make[2]: Leaving directory '/home/hongwu/devel/2020/Android/gmp_android/gmp-master/gmp-6.2.0/mpn'
```
Not sure if this is a significant issue?
I guess this bug is irrelevant if we force all makes to 64bit with abiFilters:
https://github.com/udexon/PhosCloudless/blob/master/Imgui_SymEngine_Android/abiFilters_Imgui.png

**Comment by udexon** [comment]
An update of my motivation for doing this:
https://groups.google.com/d/msg/comp.lang.forth/fEfSc9a4--Y/_x1LzytDAgAJ

- I can now seriously start the SymForth project -- if you all agree with the name or perhaps have better suggestions?

So SymForth will be a C++ interface using Forth like Reverse Polish Notation.

The first target platform is Android Java. So you may use JNI to pass an RPN string to SymForth and get results from SymEngine.

Others are already working on interface to SymEngine in other programming languages.

If SymForth becomes successful, other programming languages can also use SymForth to call SymEngine without the downstream (caller) programming interface.

I will be trying to make Forth like interface based on symengine.py as I suspect SymEngine itself was a rewrite from SymPy and symengine.py is the reference implementation for SymEngine.

**Comment by udexon** [comment]
Managed to call SymEngine expand1.cpp from Imgui demo:
https://github.com/udexon/PhosCloudless/blob/master/Imgui_SymEngine_Android/Imgui_SymEngine_expand1.png
The result is shown next to "Button": 39711 is the number of terms in expanding (w + x + y + z)**60. 
expand1.cpp is originally located in benchmarks directory.
The Reverse Polish Notation word to invoke SymEngine expand1() is ext:, entered at "input text" field. Pressing "Button" initiates RPN evaluation.

**Comment by udexon** [comment]
Made changes to the initial code so that `N ext:` will now expand (w + x + y + z)**N
https://github.com/udexon/PhosCloudless/blob/master/Imgui_SymEngine_Android/Imgui_Symengine_6_ext.png
So I hope you can see the principles of Reverse Polish Notation -- I will proceed to create a generalized interface for (w + x + y + z)**N as `w x y z N ext:`

**Comment by udexon** [comment]
I have forked SymEngine and rename it SymForth -- as a Forth-like interface to SymEngine.

https://github.com/udexon/SymForth/blob/master/README.md

https://github.com/udexon/SymForth/blob/master/benchmarks/expandv.cpp

Input:
```
$ ./expandv x sym: y sym: add: 2 3 + pow: 3 5 +
```
Output:
```
Expanding r: 5*x*y**4 + 10*x**2*y**3 + 10*x**3*y**2 + 5*x**4*y + x**5 + y**5
```
