### ISSUE TITLE
Test failure: bad rational: non-zero singular denominator

### ISSUE THREAD

**Issue by bjodah** [symengine/symengine#1639]
I encountered this today. Reporting it here so that I don't forget the details---haven't had time to investigate in depth yet.

Configuration:
- Cent OS 6
- GCC 8
- Boost 1.72

Stand alone bash script to reproduce (requires docker): [docker_symengine_cos6.sh](https://gist.github.com/bjodah/9866f3bcf247002a26176785e8d33817)

Output from failing test follows:
<details>
<summary> Output from ctest --output-on-failure</summary>
<pre>
Test project /mount/symengine-build
      Start  1: test_rcp
 1/50 Test  #1: test_rcp .........................   Passed    0.00 sec
      Start  2: test_basic
 2/50 Test  #2: test_basic .......................***Failed    0.00 sec
2*x + 3*y
2*x + 3*y
2*x + 2*y
2*x
2*x + y
----------------------
5 + 2*x*y + x**2
5
6
11
-1
30
5/6
15625
1/15625
-5
5/6

-----------------------------------------------------------------------------------------------------
test_basic is a Catch v1.12.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
Rational: Basic
-------------------------------------------------------------------------------
/mount/symengine-master/symengine/tests/basic/test_basic.cpp:337
...............................................................................

/mount/symengine-master/symengine/tests/basic/test_basic.cpp:337: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  bad rational: non-zero singular denominator

x**2*y**3
x**2*y**3
x**2*y**2
===============================================================================
test cases:  15 |  14 passed | 1 failed
assertions: 250 | 249 passed | 1 failed

      Start  3: test_arit
 3/50 Test  #3: test_arit ........................   Passed    0.01 sec
      Start  4: test_poly
 4/50 Test  #4: test_poly ........................   Passed    0.00 sec
      Start  5: test_series
 5/50 Test  #5: test_series ......................   Passed    0.00 sec
      Start  6: test_series_generic
 6/50 Test  #6: test_series_generic ..............   Passed    0.04 sec
      Start  7: test_functions
 7/50 Test  #7: test_functions ...................   Passed    0.01 sec
      Start  8: test_subs
 8/50 Test  #8: test_subs ........................   Passed    0.00 sec
      Start  9: test_integer
 9/50 Test  #9: test_integer .....................   Passed    0.00 sec
      Start 10: test_rational
10/50 Test #10: test_rational ....................   Passed    0.00 sec
      Start 11: test_relationals
11/50 Test #11: test_relationals .................   Passed    0.00 sec
      Start 12: test_number
12/50 Test #12: test_number ......................   Passed    0.00 sec
      Start 13: test_as_numer_denom
13/50 Test #13: test_as_numer_denom ..............***Failed    0.00 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_as_numer_denom is a Catch v1.12.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
NumerDenom: Rational
-------------------------------------------------------------------------------
/mount/symengine-master/symengine/tests/basic/test_as_numer_denom.cpp:46
...............................................................................

/mount/symengine-master/symengine/tests/basic/test_as_numer_denom.cpp:46: FAILED:
due to unexpected exception with message:
  bad rational: non-zero singular denominator

===============================================================================
test cases:  6 |  5 passed | 1 failed
assertions: 35 | 34 passed | 1 failed


      Start 14: test_parser
14/50 Test #14: test_parser ......................   Passed    0.00 sec
      Start 15: test_sets
15/50 Test #15: test_sets ........................   Passed    0.00 sec
      Start 16: test_fields
16/50 Test #16: test_fields ......................   Passed    0.03 sec
      Start 17: test_infinity
17/50 Test #17: test_infinity ....................   Passed    0.00 sec
      Start 18: test_nan
18/50 Test #18: test_nan .........................   Passed    0.00 sec
      Start 19: test_solve
19/50 Test #19: test_solve .......................   Passed    0.01 sec
      Start 20: test_as_real_imag
20/50 Test #20: test_as_real_imag ................   Passed    0.00 sec
      Start 21: test_integer_class
21/50 Test #21: test_integer_class ...............   Passed    0.00 sec
      Start 22: test_cse
22/50 Test #22: test_cse .........................   Passed    0.00 sec
      Start 23: test_count_ops
23/50 Test #23: test_count_ops ...................   Passed    0.00 sec
      Start 24: test_ntheory
24/50 Test #24: test_ntheory .....................   Passed    0.00 sec
      Start 25: test_diophantine
25/50 Test #25: test_diophantine .................   Passed    0.00 sec
      Start 26: test_matrix
26/50 Test #26: test_matrix ......................   Passed    0.01 sec
      Start 27: test_printing
27/50 Test #27: test_printing ....................   Passed    0.00 sec
      Start 28: test_ccode
28/50 Test #28: test_ccode .......................***Failed    0.00 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_ccode is a Catch v1.12.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
Rational
-------------------------------------------------------------------------------
/mount/symengine-master/symengine/tests/printing/test_ccode.cpp:80
...............................................................................

/mount/symengine-master/symengine/tests/printing/test_ccode.cpp:80: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  bad rational: non-zero singular denominator

===============================================================================
test cases:  7 |  6 passed | 1 failed
assertions: 49 | 48 passed | 1 failed

      Start 29: test_uintpoly
29/50 Test #29: test_uintpoly ....................   Passed    0.00 sec
      Start 30: test_uratpoly
30/50 Test #30: test_uratpoly ....................   Passed    0.00 sec
      Start 31: test_mintpoly
31/50 Test #31: test_mintpoly ....................   Passed    0.00 sec
      Start 32: test_uexprpoly
32/50 Test #32: test_uexprpoly ...................   Passed    0.00 sec
      Start 33: test_mexprpoly
33/50 Test #33: test_mexprpoly ...................   Passed    0.00 sec
      Start 34: test_basic_conversions
34/50 Test #34: test_basic_conversions ...........   Passed    0.00 sec
      Start 35: test_evalf
35/50 Test #35: test_evalf .......................   Passed    0.00 sec
      Start 36: test_eval_double
36/50 Test #36: test_eval_double .................   Passed    0.00 sec
      Start 37: test_lambda_double
37/50 Test #37: test_lambda_double ...............   Passed    0.00 sec
      Start 38: test_cwrapper
38/50 Test #38: test_cwrapper ....................   Passed    0.00 sec
      Start 39: test_expression
39/50 Test #39: test_expression ..................   Passed    0.00 sec
      Start 40: test_logic
40/50 Test #40: test_logic .......................   Passed    0.00 sec
      Start 41: test_finitediff
41/50 Test #41: test_finitediff ..................   Passed    0.00 sec
      Start 42: test_bipartite
42/50 Test #42: test_bipartite ...................   Passed    0.00 sec
      Start 43: test_hopcroft_karp
43/50 Test #43: test_hopcroft_karp ...............   Passed    0.00 sec
      Start 44: test_case001
44/50 Test #44: test_case001 .....................   Passed    0.00 sec
      Start 45: test_case002
45/50 Test #45: test_case002 .....................   Passed    0.00 sec
      Start 46: test_case003
46/50 Test #46: test_case003 .....................   Passed    0.00 sec
      Start 47: test_case004
47/50 Test #47: test_case004 .....................   Passed    0.00 sec
      Start 48: test_case005
48/50 Test #48: test_case005 .....................   Passed    0.00 sec
      Start 49: test_case006
49/50 Test #49: test_case006 .....................   Passed    0.00 sec
      Start 50: test_case007
50/50 Test #50: test_case007 .....................   Passed    0.00 sec

94% tests passed, 3 tests failed out of 50

Total Test time (real) =   0.20 sec

The following tests FAILED:
          2 - test_basic (Failed)
         13 - test_as_numer_denom (Failed)
         28 - test_ccode (Failed)
Errors while running CTest
</pre>
</details>

**Comment by isuruf** [comment]
Looks like https://github.com/boostorg/rational/issues/27

**Comment by bjodah** [comment]
Nice catch, yeah, that's it. Just tried it. I guess we can close this?

**Comment by isuruf** [comment]
We can add a workaround at https://github.com/symengine/symengine/blob/master/symengine/rational.cpp#L53 and at https://github.com/symengine/symengine/blob/master/symengine/rational.cpp#L71 depending on the boost version.

**Comment by bjodah** [comment]
Sounds good. We could make sure that at least one combination has the affected version of boost in the test matrix on the CI server.
