### ISSUE TITLE
Union of Interval with FiniteSet containing symbol drops the symbol

### ISSUE THREAD

**Issue by rikardn** [symengine/symengine#1648]
I hope that giving a reproducible example in python is fine.

```python
from symengine import var, FiniteSet, Interval

x = var('x')
A = Interval(1, 2)
B = FiniteSet(x)
u = A.union(B)
print(u)
```

The output is ```[1, 2]``` which is wrong since the value of x is unknown. It should be ```[1, 2] U {x}```

I am using the symengine python package version 0.6.0

**Comment by isuruf** [comment]
https://github.com/symengine/symengine/blob/9ef48f32501bc66c5111672b4a1964d98a9fd253/symengine/sets.cpp#L399 should return a Union object.
