### ISSUE TITLE
subs does not work for symbols containing parentheses when using symbol name as string

### ISSUE THREAD

**Issue by rikardn** [symengine/symengine#1660]
No substitution is made for the marked row below

```python
from symengine import Symbol

x = Symbol('x')
x.subs({'x': 2})       # This works

k1 = Symbol('k(1)')
k1.subs({'k(1)': 2})     # This does not work!

k1.subs({k1: 2})      # This works
```

**Comment by isuruf** [comment]
When you do `k1.subs({'k(1)': 2})`, symengine.py, automatically parses `k(1)` using symengine's parser, but `k(1)` is parsed as a function call of `k` with argument 1.
It's always better to use direct methods like your last line, instead of relying on the parser to figure out what you wanted to do.

**Comment by rikardn** [comment]
So isn't it supposed to work the way I suspected?

The same thing works fine with sympy:

```python
from sympy import Symbol

k1 = Symbol('k(1)')
k1.subs({'k(1)': 2})
```

**Comment by isuruf** [comment]
In symengine, it's equivalent to the following,
```python
from sympy import Symbol, S
k1 = Symbol('k(1)')
k1.subs({S('k(1)'): 2})
```
which doesn't work. I'm not sure how sympy is interpreting that `k(1)` is actually a symbol and not a function call.

**Comment by rikardn** [comment]
I noticed this when I was replacing sympy code with symengine and the subs didn't behave the same way. But it could then actually be that I was utilizing non-intended behaviour in sympy.

Thanks for explaining and since this is indeed the intended behaviour I will go ahead and close the issue.

**Comment by certik** [comment]
@rikardn thanks for reporting such issues. If you discover any incompatibility with going from SymPy -> SymEngine, please report it.  We want to make it as compatible as possible.
