### ISSUE TITLE
How to multiply two dense matrices using mul_dense_dense() ?

### ISSUE THREAD

**Issue by hakonhagland** [symengine/symengine#1665]
According to [`test_matrix.cpp`](https://github.com/symengine/symengine/blob/master/symengine/tests/matrix/test_matrix.cpp) there should be a method `SymEngine::mul_dense_dense`  , but when I try to compile the following test program:
```
#include <symengine/matrix.h>
int main() {
    auto x = SymEngine::symbol("x");
    auto A = SymEngine::DenseMatrix {2,2};
    A.set(0,0, SymEngine::cos(x));
    A.set(0,1, SymEngine::mul(SymEngine::integer(-1), SymEngine::sin(x)));
    A.set(1,0, SymEngine::sin(x));
    A.set(1,1, SymEngine::cos(x));
    auto y = SymEngine::symbol("y");
    auto B = SymEngine::DenseMatrix {2,2};
    B.set(0,0, SymEngine::cos(y));
    B.set(0,1, SymEngine::mul(SymEngine::integer(-1), SymEngine::sin(y)));
    B.set(1,0, SymEngine::sin(y));
    B.set(1,1, SymEngine::cos(y));
    auto C = SymEngine::DenseMatrix {2, 2};
    SymEngine::mul_dense_dense(A, B, C);  
    return 0;
}
```
I get error:

```
 error: ‘mul_dense_dense’ is not a member of ‘SymEngine’
   17 |     SymEngine::mul_dense_dense(A, B, C);
      |                ^~~~~~~~~~~~~~~
```

**Comment by isuruf** [comment]
Just remove `SymEngine::`. ADL should make it work fine.

**Comment by rere317** [comment]
Can I also import mul_dense_dense when using symengine in Python? I tried to import it as a module, but it is not found. I am trying to multiply two matrices of type <class 'symengine.lib.symengine_wrapper.MutableDenseMatrix'>. At the moment I am simply using the * operator and I think it is being overloaded correctly, but I'm not sure and don't know how to check. My problem is that the multiplication takes forever. The matrices are symbolic and large (1000 x 1000). I know that symbolic computation is slow, but maybe there is room for improvement? Thanks!!!

**Comment by rikardn** [comment]
In python the `@` operator should be used for matrix multiplication. It seems as if `*` does the same thing though. Symbolic computations can be slow for many different reasons so it is hard to say in your case.

**Comment by rere317** [comment]
Thanks for the quick reply! I tried using @ and it works, but there is no difference in computation time. I also tried simplifying the matrices before multiplying, but since the expressions differ a lot there is no way to strategically simplify. Just using the simplify method makes the code much much slower.  Do you know if symengine has a multiprocessing tool or something for threading? I'm impressed with the symengine library, but I'm a little confused because I can't really find any documentation.

**Comment by rikardn** [comment]
I agree that we need more volunteers to write documentation. To know what the bottle neck is you could try either smaller matrices or matrices with simpler elements (like only integers for example) and see if the perceived slowness comes from the size of the matrix or the elements. If you find something interesting you could share it in a new issue.

**Comment by rere317** [comment]
For anyone interested: For my matrices, a simple implementation of a blocked matrix multiplication (see. [https://malithjayaweera.com/2020/07/blocked-matrix-multiplication/](url)) was able to reduce the computation time by a factor of 10!

**Comment by rikardn** [comment]
Thanks for sharing! It is really cool that the methods we know from numerical computations could also speed up symbolic computations.
