### ISSUE TITLE
Proposal: `cpplint` task

### ISSUE THREAD

**Issue by HaoZeke** [symengine/symengine#1666]
The documentation (readme) includes a link to basic patch guidelines. At least one of these (the whitespace rules) can be checked at build time using `cpplint` in the pipeline.
Actually [cpplint](https://github.com/stan-dev/math/pull/1871) defaults to enforcing a bunch of rules from the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) like:

build/header_guard -> [The #define Guard](https://google.github.io/styleguide/cppguide.html#The__define_Guard)
build/include_order -> [Names and Order of Includes](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)
build/namespaces -> [Namespaces](https://google.github.io/styleguide/cppguide.html#Namespaces)
runtime/string -> Part of [Local Variables](https://google.github.io/styleguide/cppguide.html#Local_Variables)

This is actually not a very invasive change, since most editors support directly running `cpplint` on-save; and that can be configured with a file at the repo root.

**Comment by HaoZeke** [comment]
My bad, forgot to check for `clang-format`

**Comment by certik** [comment]
@HaoZeke no worries. Yes, we use `clang-format` at the CI to enforce formatting.
