### ISSUE TITLE
Requesting  the Hadamard product for two matrices of the same dimension

### ISSUE THREAD

**Issue by mithun218** [symengine/symengine#1675]
I have a plan to use symengine for symbolic computations in python to implement my new research topic. I have seen symengine has everything to use it in my research topic without one feature which is the Hadamard product for two matrices of the same dimension. If there are any plan to develop the Hadamard product in SymEngine it would be helpful. 

![image](https://user-images.githubusercontent.com/9692622/89122781-e1db4900-d4e7-11ea-94da-1476c6ff88d8.png)

**Comment by isuruf** [comment]
Are you using C++ or python wrappers?

**Comment by mithun218** [comment]
I am using python wrapper

**Comment by isuruf** [comment]
Then it should be easy to write a python function to return the Hadamard product.

**Comment by mithun218** [comment]
But a python function implemented by user can be as fast as inbuilt  python wrapper functions?

**Comment by isuruf** [comment]
Not as fast, but it shouldn't take an unreasonable amount of time. I suggest you implement it and profile your application to see if that function is a "hotspot" (takes a considerable amount of the time in your application).

Of course, we'd love have a PR that implements it in C++ and then wrap it in python.

**Comment by mithun218** [comment]
Thanks

**Comment by rikardn** [comment]
I think that this could be closed since #1693 has been merged. I don't know if there is a procedure to get new functionality into the python wrapper.

**Comment by mithun218** [comment]
Many many thanks to implement of my requested feature in symengine.
Your implementation will help me in my future research  works.

**Comment by isuruf** [comment]
Thanks @rikardn.

> I don't know if there is a procedure to get new functionality into the python wrapper.

Code is at https://github.com/symengine/symengine.py

**Comment by rikardn** [comment]
Thanks @isuruf I will have a look.

**Comment by rikardn** [comment]
Closing, since this has been added to symengine.py via https://github.com/symengine/symengine.py/pull/329
