### ISSUE TITLE
How to do three valued logic internally in symengine?

### ISSUE THREAD

**Issue by rikardn** [symengine/symengine#1692]
After the PR https://github.com/symengine/symengine/pull/1690 I was planning to do an ```is_hermitian``` method for matrices. In sympy these types of methods use a three value logic system where ```None``` is indeterminate (i.e. that sympy doesn't know or that it cannot be known). For example

```
from sympy import Matrix, Symbol

A = sympy.Matrix([Symbol('x')])
A.is_hermitian
```

would give ```None```.

My question is how this could be implemented in symengine. I tried to find any situation like this in the code, but couldn't find any implementation.

Some suggestions:
1. The ```tribool``` of boost. Very nice syntax, supports logical operations (https://www.boost.org/doc/libs/1_59_0/doc/html/tribool.html)
2. std::option<bool> of C++17 (or from boost). This would be a "nullable" bool.  (https://en.cppreference.com/w/cpp/utility/optional)
3. An int with -1, 0 and 1  where -1 is "indeterminate". If-statements for checking would become:

```C++
if (val == -1) {
    // indeterminate
} else if (val) {
   // true
} else {
   // false
}
```

I would vote for ```tribool``` because it has everything in a nice package already.

Any other ideas or thoughts?

**Comment by isuruf** [comment]
I don't think we should go with boost. It's a big dependency.
How about,
4. A enum?

I'm okay with either 3 or 4.

**Comment by rikardn** [comment]
I tried a regular enum:

```c++
#include <iostream>

enum tribool { indeterminate=-1, trifalse=0, tritrue=1 };

int main()
{
    tribool mytri {indeterminate};
    if (mytri == indeterminate) {
        std::cout << "INDETERMINATE" << std::endl;
    } else if (mytri) {
        std::cout << "TRUE" << std::endl;
    } else {
        std::cout << "FALSE" << std::endl;
    }
    return 0;
}
```

I think that this is usable, but we run the risk of reimplementing parts of the boost tribool. For example logical operations on tribools. I don't feel that it is a big dependency. Since it is boost we can simply copy the header into the symengine code base. That being said I think we can start using an enum as above and see where it leads.

I also tried ```enum class```, but that doesn't allow implicit conversions or usage of the ```operator bool```, which means that we would need a function to convert to a regular bool. If you think it is worth the extra type safety here is what it would look like:

```c++
#include <iostream>

enum class tribool { indeterminate=-1, trifalse=0, tritrue=1 };

inline bool tritobool(tribool x)
{
    return x == tribool::tritrue;
}

int main()
{
    tribool mytri {tribool::indeterminate};
    if (mytri == tribool::indeterminate) {
        std::cout << "INDETERMINATE" << std::endl;
    } else if (tritobool(mytri)) {
        std::cout << "TRUE" << std::endl;
    } else {
        std::cout << "FALSE" << std::endl;
    }
    return 0;
}
```

We could of course wrap any of these in a class. This would get us quite close to reimplementing the boost tribool though.

**Comment by rikardn** [comment]
I have submitted an `is_zero` using an enum tribool here https://github.com/symengine/symengine/pull/1698

**Comment by rikardn** [comment]
Closing since #1698 has been merged. The added ```tribool``` type and helper functions now live in ```basic.h```
