### ISSUE TITLE
Crash for csr_binop_csr_canonical

### ISSUE THREAD

**Issue by rikardn** [symengine/symengine#1694]
The following code segfaults:

```C++
CSRMatrix A = CSRMatrix(2, 2, {0, 1, 2}, {0, 1}, {integer(1), integer(2)});
CSRMatrix B = CSRMatrix(2, 2, {0, 1, 2}, {1, 0}, {integer(3), integer(4)});
CSRMatrix C = CSRMatrix(2, 2);
csr_binop_csr_canonical(A, B, C, mul);
```

The matrices are ```A = [[1, 0], [0, 2]]``` and ```B = [[0, 3], [4, 0]]``` and the results should become ```C = [[0, 0], [0, 0]]```.

**Comment by lkeegan** [comment]
The segfault is due to this loop termination condition subtracting `1` from an `unsigned` int that in this case is `0`:
https://github.com/symengine/symengine/blob/1ada984dd8b4a8682f1faa6240d8102af5be887e/symengine/sparse_matrix.cpp#L396
