### ISSUE TITLE
ComplexDouble can end up in non-canonical form

### ISSUE THREAD

**Issue by rikardn** [symengine/symengine#1711]
The result of the following addition of two `ComplexDouble` is non-canonical since the imaginary part is zero. Perhaps it should have been converted to a `RealDouble`.

```c++
#include <iostream>
#include <symengine/expression.h>
using SymEngine::complex_double;
using SymEngine::add;

auto c1 = complex_double(std::complex<double>(1.0, 1.0));
auto c2 = complex_double(std::complex<double>(0.0, -1.0));
auto expr = add(c1, c2);
std::cout << (*expr).__str__() << std::endl;
```

Output is:

```
1.0 + 0.0*I
```

**Comment by isuruf** [comment]
This is related to https://github.com/symengine/symengine/issues/1709. A `RealDouble` is an approximation of a real number and is not an approximation of a complex number. The imaginary part of a `RealDouble` is exactly zero. The imaginary part of a `ComplexDouble` can never be exactly zero as it's an approximation.

**Comment by rikardn** [comment]
Ok, I understand. So this means that we should view the number in my example as being complex. This makes sense. Thanks for clarifying, I'll close this.
