### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1715]
We should move away from travis.

CIs to consider
- Github Actions
- Azure pipelines
- Circle CI

We could also use conda-smithy to manage CI for us

**Comment by lkeegan** [comment]
fyi I found that migrating from travis.org to travis.com improved my build wait times a lot:
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by lkeegan** [comment]
following up on my previous comment, travis are deprecating the travis.org site (and reducing server capacity there), so I would suggest migrating the builds to the travis.com site (someone with admin access could do this here: https://travis-ci.com/organizations/symengine/migrate)

symengine builds wait ~2hrs on average before running this week on travis.org:
https://travis-ci.org/github/symengine?tab=insights&timeInterval=week

for comparison, my builds on travis.com wait ~2mins before running (and the migration itself took a couple of minutes and didn't break anything as far I can tell):
https://travis-ci.com/github/spatial-model-editor?tab=insights&timeInterval=week

**Comment by certik** [comment]
I would recommend to use  GitHub Actions and be done with it. It works on all platforms, integrates well with GitHub etc.

Later, we can revisit and change if needed.

**Comment by isuruf** [comment]
@lkeegan, the issue with travis-ci.com is that they no longer provide macos bulds for free. travis-ci.org does until end of this year and they'll no longer be free too. travis-ci also reduced the number of build minutes this month. Not sure if we will hit the limit

**Comment by lkeegan** [comment]
@isuruf the free plan on .com also includes macos build minutes (the free plan is "usage based" with 10k free credits/month: "https://docs.travis-ci.com/user/billing-overview/#usage---credits), and so far this limit doesn't actually seem to be enforced but once they do start limiting the build minutes I would agree Github actions is probably the best alternative

**Comment by isuruf** [comment]
We've moved to github actions now except for one test in Travis-CI, which I can't get to run on Github Actions.

**Comment by certik** [comment]
@isuruf can you open up an issue for that one test?
