### ISSUE TITLE
`is_zero()` method in `Basic` class

### ISSUE THREAD

**Issue by thilinarmtb** [symengine/symengine#172]
When working with basic types like `Number`, `Symbol`, `Add`, `Pow` and `Mul` we need to know whether a particular instance of the above types is zero or not. Recently, I came across this when trying to implement Gaussian elimination. I need to know whether an element in the Matrix is zero or not. Would it be okay to add a method `is_zero()` in `Basic` which will provide this information ?

**Comment by rwst** [comment]
Be careful with a generic `is_zero`, it opens a can of worms and will probably misused and be a performance drag. Sage for example has `is_trivial_zero` for when you need to know if the expression "is" numerical zero. In one of my Sage tickets I propose that the behaviour of `Expression.is_zero` is `is_trivial_zero` by default, and simplification only occurs with the keyword `simplify=True`. To keep `is_zero` with `Number` only sounds perfectly fine, too.

**Comment by certik** [comment]
@rwst I agree. I don't like the expensive operations either. I think the way it is implemented currently is very fast. Let me know if you find any issue with it.

**Comment by rwst** [comment]
I think the question is answered.
