### ISSUE TITLE
sympify syntax error: unary plus operator

### ISSUE THREAD

**Issue by tueda** [symengine/symengine#1720]
```python
symengine.sympify('+x')
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "symengine_wrapper.pyx", line 500, in symengine.lib.symengine_wrapper.sympify
RuntimeError: syntax error
```
(symengine-0.6.1 and Python 3.9.1)

What I expected is returning a symbol as sympy does (`sympy.sympify('+x')`).

**Comment by isuruf** [comment]
The issue is that a unary plus is not in the grammar. https://github.com/symengine/symengine/blob/master/symengine/parser/parser.yy#L89
