### ISSUE TITLE
binary wheels for ARM

### ISSUE THREAD

**Issue by danshapero** [symengine/symengine#1732]
There don't appear to be any pre-built binary wheels of SymEngine for the ARM architecture for any operating system on PyPI. I ran into this when helping a friend set up a package that depends on SymEngine on an AWS EC2 instance which is running an ARM chip. The new Apple M1 processor is also an ARM chip. So usage of ARM machines seems likely to increase in the future and having a pre-built wheel for this architecture could save a lot of people from having to build from source.

**Comment by rikardn** [comment]
Thanks for pointing this out. I think this will be a thing for all python packages depending on native code compilation. We are currently in the process of migrating some automatic builds to github actions. If anyone has information on support for running on ARM/MacOS using github actions that would be welcome.

**Comment by danshapero** [comment]
Sure thing, @certik directed me here after I asked about this on the mailing list. Is pushing binary wheels to PyPI a manual process at present? There's a [pypi-publish](https://github.com/marketplace/actions/pypi-publish) GitHub action but it seems to only work for Linux. I have no idea how this would work with ARM/MacOS.

**Comment by isuruf** [comment]
`linux-aarch64` and `macosx-arm64` wheels are available now.
