### ISSUE TITLE
Amazon triple containing

### ISSUE THREAD

**Issue by liushuangddu** [symengine/symengine#1742]
Hi, I'm very glad to find you on this website. I'm a developer from China. Now I does working on Bluetooth Sigmesh . I plan to access the Amazon echo for my device , and then I recgnized before I need the BLE Mesh Credentials- A triple containing the OOB Type (Static only for now), OOB Data (pub key), and Device UUID.
But I has clicked entire website still connot find out the documentation for how to get my triple containing.
May I get some help form you , very appreciate.

**Comment by rikardn** [comment]
Symengine is a library for symbolic mathematics. Are you sure you posted this in the right place?

**Comment by isuruf** [comment]
This is from a spam account. Reported it
