### ISSUE TITLE
zlib.dll not found (on windows)

### ISSUE THREAD

**Issue by nunupeke** [symengine/symengine#1743]
After updating to v0.7.0 using conda, I get "zlib.dll" not found when loading my recompiled C++ library on Windows. Seems like the dependencies haven't be updated for the conda package.

**Comment by isuruf** [comment]
@nunupeke, thanks for the bug report. Can you try the new package with build number `1`?

**Comment by nunupeke** [comment]
Works like charm. Thank you. Keep up the good work. :heart:
