### ISSUE TITLE
Broken binder

### ISSUE THREAD

**Issue by SylvainCorlay** [symengine/symengine#1757]
It seems that the binder build is broken at this time over the `sudo` keyword.

Would you consider a PR in which we would rely on the conda packages for xeus-cling and symengine for the binder What we typically do is point to the latest `stable` commit (see e.g. in the xtensor binder) so that can change notebooks together with the code without breaking a release-based binder.

**Comment by isuruf** [comment]
@HaoZeke, why was `sudo` added there? It should not be necessary.
