### ISSUE TITLE
When to throw and when to return NaN

### ISSUE THREAD

**Issue by rikardn** [symengine/symengine#1770]
This is a design question.

What do you think a mathematical function should do when getting an illegal input argument? For example if a function that only takes integers as argument gets a rational number. Should it create `NaN` or throw an exception? When calling the constructor it might work with raising, but what if we are doing substitution on a symbolic argument?function:

Don't know about this:

```c++
auto pn = prime(real_double(0.5));    // hypothetical n:th prime function
```

Feels like this shouldn't throw:

```c++

auto n = symbol('n');
auto pn = prime(n);   // hypothetical n:th prime function
pn->subs({n, real_double(0.5)})
```

**Comment by rikardn** [comment]
I checked sympy for example:

```python

import sympy

x = sympy.Symbol('x')
expr = sympy.bernoulli(x)
expr.subs({x: 0.5})
```

This raises on the substitution:

```
ValueError: Bernoulli numbers are defined only for nonnegative integer indices.
```

so perhaps raising is most natural.

**Comment by lkeegan** [comment]
As a user in this scenario I would also generally prefer to get an exception with an error message rather than a silent NaN.

**Comment by rikardn** [comment]
I agree!
