### ISSUE TITLE
subs missing logical operators

### ISSUE THREAD

**Issue by tbb300** [symengine/symengine#1794]
I think there are potentially methods missing in subs.h  for dealing with some logical operators? It looks like "and" is the only logical expression that is handled which leads to missing substitutions on "or" (and possibly others). Can probably submit a change but wanted to make sure I'm not missing anything...

Simple example:
~~~
StrPrinter p;
auto x = symbol("x");
auto and_expr = logical_and({Gt(x,integer(2)), Lt(x,integer(5))});
auto or_expr = logical_or({Gt(x,integer(2)), Lt(x,integer(5))});
std::cout << p.apply(and_expr->subs({{x,integer(4)}})) << std::endl;
std::cout << p.apply(or_expr->subs({{x,integer(4)}})) << std::endl;
~~~
returns the following:
~~~
True
Or(2 < x, x < 5)
~~~

**Comment by rikardn** [comment]
Thanks for reporting this. You are right. `or` and other logic operators are missing. A pull request would certainly be welcome.
