### ISSUE TITLE
Derivative by arrays?

### ISSUE THREAD

**Issue by Audrius-St** [symengine/symengine#1807]
Hello, 

I've found Symengine to be most useful in taking the derivatives of long complicated expressions. 
Very fast relative to Sympy.

Now I would like to take the derivatives of an expression with respect to an array of symbols. 
Sympy provides 
`sympy.tensor.array.derive_by_array(expr, dx) `
to do this. 
Is there an equivalent function in Symengine? 
Or a workaround besides a set of nested for loops to take the derivative element by element of the array.

As the Symengine documentation is a bit sparse, trying the following 

```
import symengine as se 
. . .
fq = se.Derivative(h_op, p, 1)
```

with h_op a Sympy Function class and p a 6x3 Sympy Matrix of symbols returns

```
File "symengine_wrapper.pyx", line 2841, in symengine.lib.symengine_wrapper.Derivative.__new__
File "symengine_wrapper.pyx", line 4018, in symengine.lib.symengine_wrapper.diff
TypeError: Cannot convert symengine.lib.symengine_wrapper.MutableDenseMatrix to symengine.lib.symengine_wrapper.Basic

```

**Comment by isuruf** [comment]
You can do `p.applyfunc(lambda x: h_op.diff(x))`

**Comment by Audrius-St** [comment]
Thank you for the suggestion. It works well with the modification

```
import symengine as se
. . . 
fq = p.applyfunc(lambda x: se.Derivative(h_op, x, 1))
```

to call the Symengine derivative instead of the Sympy one.
