### ISSUE TITLE
Series expansion in C++ is slower than python

### ISSUE THREAD

**Issue by ronald00773** [symengine/symengine#1848]
Hello All

I compiled symengine with the following flags : 

```bash
CC=gcc CXX=g++ cmake CXXFLAGS="-O3 -I/opt/local/include -std=c++11 -I/Users/local/include " -DWITH_BOOST=on  -DCMAKE_INSTALL_PREFIX:PATH="some_where" -DWITH_FLINT:BOOL=ON -DINTEGER_CLASS=flint -DWITH_SYMENGINE_THREAD_SAFE=no -DWITH_PIRANHA:BOOL=on -DWITH_COTIRE=no -DWITH_PTHREAD=ON -DWITH_MPFR=on -DWITH_MPC=on ..
```

When I try to expand a series, the python wrapper is way faster than C++, which is strange. Why does this happen? What is causing the bottle neck during expansion in C++? Here is a sample code (Ran on mac M1):

#C++ Code

Compiled with -O3 flag with gcc-11, 
```C++
#include <symengine/symengine_config.h>

#include <symengine/series_piranha.h>

#include <iostream>
#include <chrono>

#include <symengine/functions.h>
#include <symengine/symbol.h>
#include <symengine/mul.h>
#include <symengine/series.h>

using SymEngine::add;
using SymEngine::Basic;
using SymEngine::cos;
using SymEngine::integer;
using SymEngine::mul;
using SymEngine::pow;
using SymEngine::RCP;
using SymEngine::rcp_dynamic_cast;
using SymEngine::series;
using SymEngine::sin;
using SymEngine::Symbol;
using SymEngine::symbol;

int main(int argc, char *argv[])
{
    SymEngine::print_stack_on_segfault();

    RCP<const Symbol> x = symbol("x");
    int N = 200;
    auto arg = add(x, pow(x, integer(2)));
    auto ex = mul(sin(arg), cos(arg));

    auto t1 = std::chrono::high_resolution_clock::now();
    auto res = SymEngine::series(ex, x, N);
    auto t2 = std::chrono::high_resolution_clock::now();
    // std::cout << *res[N-1] << std::endl;
    std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1)
                     .count()
              << "ms" << std::endl;

    return 0;
}


```

#Python  :  

```python
from symengine import *
x = var("x")
p = x+x**2
ex = sin(p)*cos(p)
%timeit series(ex,x,200)


```

I am interested to know why is this happening and what is causing the bottleneck

Thank you

**Comment by lkeegan** [comment]
That's interesting  - what numbers do you get?

On an x86-64 cpu (with the last python line changed to `%timeit series(ex,x,n=200)` so that both examples are doing the same expansion) I get

- `1 ms` for the c++ version (with `-DINTEGER_CLASS=flint`)
- `1.77 ms ± 3.91 µs per loop` for the python version
- `137 ms` for c++ (with `-DINTEGER_CLASS=gmp`)
- `2272 ms` for c++ (with `-DINTEGER_CLASS=boostmp`)

**Comment by ronald00773** [comment]
Thanks for the reply, I looped 10000 times, these are results that I get on M1 cpu

`1.57928ms` for C++ version (Gcc-11.2, using the following flags `(-O3 -march=native -std=c++11)`
Symengine compiled with the following configuration:
`CC=gcc CXX=g++ cmake DWITH_MPFR=on -DWITH_MPC=on -DINTEGER_CLASS=flint CXXFLAGS="-O3 -std=c++11 -I/opt/local/include " -DWITH_FLINT:BOOL=on -DWITH_COTIRE=off`

`0.181284 ms` for python3.9 version. Symengine.py installed from pip

C++:

```
#include <symengine/symengine_config.h>

#include <symengine/series_piranha.h>

#include <iostream>
#include <chrono>

#include <symengine/functions.h>
#include <symengine/symbol.h>
#include <symengine/mul.h>
#include <symengine/series.h>

using SymEngine::add;
using SymEngine::Basic;
using SymEngine::cos;
using SymEngine::integer;
using SymEngine::mul;
using SymEngine::pow;
using SymEngine::RCP;
using SymEngine::rcp_dynamic_cast;
using SymEngine::series;
using SymEngine::sin;
using SymEngine::Symbol;
using SymEngine::symbol;

int main(int argc, char *argv[])
{   int num;
    std::cin>>num;
    SymEngine::print_stack_on_segfault();

    RCP<const Symbol> x = symbol("x");
    int N = 200;
    auto arg = add(x, pow(x, integer(2)));
    auto ex = mul(sin(arg), cos(arg));

    auto t1 = std::chrono::high_resolution_clock::now();
    for(int ii=0; ii<num; ++ii){
    auto res = SymEngine::series(ex, x, N);}
    auto t2 = std::chrono::high_resolution_clock::now();
    // std::cout << *res[N-1] << std::endl;
    std::cout << std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1)
                     .count() *pow(10,-3) /num 
              << "ms" << std::endl;

    return 0;
}

```
Python:
```
from symengine import *
from time import time
x = var("x")
p = x+x**2
ex = sin(p)*cos(p)
def fun(num):
    t1 = time()
    for i in range(num):
        pp = series(ex,x,200)
    return 10**3 * (time()-t1)/num


print(fun(100))
print(fun(1000))
print(fun(10000))
```

**Comment by lkeegan** [comment]
Thanks for the numbers - if I copy your code samples I get similar timings, but looking at the ouput the two are not doing the same expansion.

I think the python call should be:

```
series(ex,x,n=200)
```

to match the c++ code, otherwise as written the python code is expanding around `x0=200` using the default `n=6` instead of `n=200` terms. (see https://github.com/symengine/symengine.py/blob/master/symengine/lib/symengine_wrapper.pyx#L1161)

When I make this change then the python code is a bit slower than the c++ version.

**Comment by ronald00773** [comment]
Yeah. Now python numbers changed. 

Thanks @lkeegan
