### ISSUE TITLE
Substitutions giving wrong results when numerator and denominator are zero

### ISSUE THREAD

**Issue by johanbluecreek** [symengine/symengine#1852]
I noticed that some expressions, when evaluated at points where the denominator is zero, can yield wrong results when the numerator is zero at that same point. For example:

```julia
julia> using SymEngine
julia> @vars x
julia> subs(x/sin(x), x => 0)
0
julia> subs(x/(1-cos(x)), x => 0)
0
```

and actual result would be (from Mathematica)

```Mathematica
In[1] := Limit[x/Sin[x] -> x]
Out[1] := 1
In[2] := Limit[x/(1-Cos[x]) -> x]
Out[2] := Indeterminate
```

A better result than a zero as the result here would probably be that some domain error is thrown or that one get an inf, as one also would get in e.g. Mathematica (sort of) if proper limits were not used

```Mathematica
In[3] := x/Sin[x] /. x -> 0
... Infinity: Indeterminate expression 0 ComplexInfinity encountered.
Out[3] := Indeterminate
```

meaning it would probably be best to have these kinds of expressions give infinities or something else indicating a problem in the expression, like this would be more expected than the current result:
```julia
julia> subs(x/sin(x), x => 0)
zoo
julia> subs(x/(1-cos(x)), x => 0)
zoo
julia> subs(x/sin(x), x => 0.0)
inf.0
julia> subs(x/(1-cos(x)), x => 0.0)
inf.0
```

**Comment by isuruf** [comment]
Can confirm. The shortcut at https://github.com/symengine/symengine/blob/2eb109a0e554b62683662cc5559fccf2ea0c0348/symengine/subs.h#L96-L99 seems to be the issue. Maybe we should remove that shortcut.
