### ISSUE TITLE
Please help me, c++ test code error !

### ISSUE THREAD

**Issue by symengineboy** [symengine/symengine#1858]
Hi, 

I have trouble with c++ test code in symengine library.

![image](https://user-images.githubusercontent.com/92733216/137739757-a161e486-eac1-4a6c-af38-4f28b4645d48.png)

How to use test code in linux?

And, I want to correct catch.hpp error.

Thany you all.

**Comment by rikardn** [comment]
The easiest way to run the unit tests of symengine is to:

```
cd symengine
mkdir build
cd build
cmake ..
make -j8   # Use j for parallel build
ctest
```
