### ISSUE TITLE
No such header file

### ISSUE THREAD

**Issue by symengineboy** [symengine/symengine#1859]
Hi, 

I have a problem with header file because my linux cannot search header file.

I wonder if I install "symengine" well.

Github code download -> mkdir build && cd build -> cmake .. -> make -> make install -> ctest

Any errors do not happen in the installation. But, I cannot use a "symengine" because of header paths.

Please help me.

Thanks.

**Comment by rikardn** [comment]
The default installation prefix is `/usr/local` meaning that headers will be installed into `/usr/local/include/symengine`. Even though this should be in the default search path of the compiler perhaps this is not the case on your installation. You could try the `-I` option like for example `-I/usr/local/include/symengine` to tell the compiler where to look.
