### ISSUE TITLE
Matrix lambdification in C++

### ISSUE THREAD

**Issue by bsbretly** [symengine/symengine#1866]
Hello,

I am performing operations on symbolic matrices, using the `using SymEngine::DenseMatrix` class. I now would like to evaluate the output of these operations with numeric values substituted for the symbolic variables. After a bit of digging, I found the `SymEngine::LambdaRealDoubleVisitor` class, which has the functionality to output a numeric result of type `double` from a symbolic equation .

Using `SymEngine::LambdaRealDoubleVisitor` as a building block to numerically evaluate an object of type `SymEngine::DenseMatrix`, I defined the following function: 

```c++
Eigen::MatrixXd evalSymMatrix(const DenseMatrix& symbolic_matrix,
                              const vec_basic symbolic_variables,
                              const std::vector<double> numeric_values) {
    //in: symbolic matrix, symbolic variables, numeric values
    //out: numeric matrix N
    Eigen::MatrixXd N(symbolic_matrix.nrows(),symbolic_matrix.ncols());
    for (int i = 0; i < symbolic_matrix.nrows(); i++) {
        for (int j = 0; j < symbolic_matrix.ncols(); j++) {
            double num;
            LambdaRealDoubleVisitor l;
            RCP<const Basic> r;
            r = symbolic_matrix.get(i, j);
            l.init(symbolic_variables, *r); //want to init in the constructor once
            num = l.call(numeric_values);;
            N(i, j) = num;
        }
    }
    return N;
}
```

The above function works to lambdify a symbolic matrix element-by-element, but I would like to come to a solution which functions in the same way the `SymEngine::LambdaRealDoubleVisitor` class functions, but for a `Eigen::Matrix` type instead of a `double` type. My solution above creates a new `SymEngine::LambdaRealDoubleVisitor` object for every element of the matrix, which is not ideal. 

Specifically, I would like to create my own class `MyClass` which defines a symbolic matrix and then lambdifies and initializes that symbolic matrix in the constructor of `MyClass`. This will then allow me to lambdify the symbolic matrix once in the `MyClass` constructor, then call that lambdified matrix function within different methods of `MyClass` with my numeric variables of choice. Any suggestions on how I might approach this problem?

Thanks!

**Comment by isuruf** [comment]
LambdaRealDoubleVisitor and LLVMDoubleVisitor are fast only if you call them multiple times with different numerical values as the setup cost (`init`) is higher. If you only need to evaluate the matrix once, you can use `xreplace`.

**Comment by isuruf** [comment]
Are you evaluating the matrix once or many times?

**Comment by bsbretly** [comment]
Thanks for the reply @isuruf - I will be evaluating the matrix many times.

**Comment by isuruf** [comment]
You can do,

```
LambdaRealDoubleVisitor l;
l.init(symbolic_variables, symbolic_matrix.as_vec_basic());
```

and then change your function to,
```
Eigen::MatrixXd evalSymMatrix(LambdaRealDoubleVisitor l,
                              const std::vector<double> numeric_values, unsigned nrows, unsigned ncols) {
    Eigen::MatrixXd N(nrows, ncols);
    std::vector<double> out(nrows*ncols);
    l.call(out);
    for (int i = 0; i < nrows; i++) {
        for (int j = 0; j < ncols; j++) {
            N(i, j) = out[i*ncols + j];
        }
    }
    return N;
}
```

**Comment by bsbretly** [comment]
Thanks @isuruf! Though I think I should `call()` the `numeric_values` vector and not the `out` vector and assign the result to `out`, resulting in something more like this:
```
Eigen::MatrixXd evalSymMatrix(LambdaRealDoubleVisitor &l,
                              const std::vector<double> &numeric_values, unsigned nrows, unsigned ncols) {
    Eigen::MatrixXd N(nrows, ncols);
    std::vector<double> out(nrows*ncols);
    out = l.call(numeric_values);
    for (int i = 0; i < nrows; i++) {
        for (int j = 0; j < ncols; j++) {
            N(i, j) = out[i*ncols + j];
        }
    }
    return N;
}
```
Or am I incorrect?

**Comment by isuruf** [comment]
Yes, your code looks correct.

**Comment by isuruf** [comment]
Ignore my last comment. Here's the correct code,
```C++
Eigen::MatrixXd evalSymMatrix(LambdaRealDoubleVisitor &l,
                              const std::vector<double> &numeric_values, unsigned nrows, unsigned ncols) {
    Eigen::MatrixXd N(nrows, ncols);
    std::vector<double> out(nrows*ncols);
    l.call(out.data(), numeric_values.data());
    for (int i = 0; i < nrows; i++) {
        for (int j = 0; j < ncols; j++) {
            N(i, j) = out[i*ncols + j];
        }
    }
    return N;
}
```

**Comment by isuruf** [comment]
Note that depending on the storage order (Row major vs column major), the matrix might have to be transposed before returning.

**Comment by bsbretly** [comment]
Awesome! Thanks so much @isuruf. As you mentioned, I did have to slightly adjust the storage order to get my function to work as intended:

```c++
Eigen::MatrixXd evalLambdaFunction(LambdaRealDoubleVisitor &lambdaFunc,
                              const std::vector<double> &numeric_values, unsigned nrows, unsigned ncols) {
    Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> N;
    N.resize(nrows, ncols);
    lambdaFunc.call(N.data(), numeric_values.data());
    return N;
}
```

**Comment by isuruf** [comment]
Sounds good. If you need Eigen matrices that are in column major, you can transpose the symengine Matrix before sending to LambdaRealDoubleVisitor.

**Comment by isuruf** [comment]
For more performance you can use `cse=True` argument  to `init` and also try using `LLVMDoubleVisitor`
