### ISSUE TITLE
Conditional Symbolic Diff

### ISSUE THREAD

**Issue by fknfilewalker** [symengine/symengine#1877]
I want to use symengine to generate some derivative c code that I can use on a gpu. Sometimes there is a case like this

foo = z;
if(val > 0.5)  foo *= x;
else foo *= y;

Is it possible to let symengine generate code for the derivative which contains this condition?

dfoo/dx:
if(val > 0.5) z
else 0

**Comment by isuruf** [comment]
```
In [10]: from symengine import *

In [11]: val, z, x, y = symbols("val, z, x, y")

In [12]: foo = z * Piecewise((x, val > 0.5), (y, True))

In [13]: foo.diff(x)
Out[13]: z*Piecewise((1, 0.5 < val), (0, True))
```

**Comment by fknfilewalker** [comment]
hell yes, thats awesome thanks

I am using c++, not exacly sure how to create the PiecewiseVec there

**Comment by isuruf** [comment]
https://github.com/symengine/symengine/blob/2ad4e879359a4c19da262f5c122a7daf921a0063/symengine/tests/printing/test_ccode.cpp#L165-L178

**Comment by fknfilewalker** [comment]
I don't get it how to do something like lessthan

**Comment by isuruf** [comment]
https://github.com/symengine/symengine/blob/2ad4e879359a4c19da262f5c122a7daf921a0063/symengine/tests/basic/test_relationals.cpp#L52-L74

**Comment by fknfilewalker** [comment]
Thanks, that part was really confusing, there is an SymEngine::Equality, SymEngine::eq, and SymEngine::Eq
