### ISSUE TITLE
get_args to access one element

### ISSUE THREAD

**Issue by PerformanceCoder** [symengine/symengine#1881]
Hi!

Currently, I couldn't find a function to access only one element in a sum or product. `get_args()` allows to access *all* elements of expression, which could be ineffective in some cases. For example, if some code parses only first 10 terms of a sum and whole sum contains 1 000 000 elements, then `get_args` will allocate additional 999 990 elements. In another case, something like `get_arg(i)` could be used in parallel argument processing, where `get_args()` will be the only sequential bottleneck.

Is there any way in SymEngine to access an element without allocating a vector containing all elements?

**Comment by isuruf** [comment]
You can access the underlying container.

https://github.com/symengine/symengine/blob/master/symengine/add.h#L141-L151

**Comment by PerformanceCoder** [comment]
Thank you for the reference! Could you also show corresponding method in cwrapper?

**Comment by isuruf** [comment]
I don't think there's any method in `cwrapper`.

Btw, there'll be other issues way before `get_args` becomes a bottleneck for you as almost all operation will go through the args once or more.

**Comment by PerformanceCoder** [comment]
Thank you for your reply! Then I'll experiment with direct container access.
