### ISSUE TITLE
Simplify rounds floats

### ISSUE THREAD

**Issue by Wrzlprmft** [symengine/symengine#1901]
For some reason, `simplify` rounds floats to 14 (I think) digits. This leads to inconsistent results, such as the last assertion in the following failing:

``` Python 3
from symengine import Function

f = Function("f")
expr = f(4.347249999999999)

assert expr.diff(expr) == 1
assert expr.simplify().diff(expr) == 1
```

I cannot see a way to avoid this with an argument (such as `rational=False`). If I replace SymEngine by SymPy, this does not happen.

This lead to [this issue](https://github.com/neurophysik/jitcdde/issues/43) in my module using SymEngine. For a temporary fix, I would also be curious about any way to perform the float rounding without doing any other time-consuming simplification.

**Comment by rikardn** [comment]
This line in `strprinter.cpp` is problematic:

```
s.precision(std::numeric_limits<double>::digits10);
```

The precision here is not enough to do a round trip. We need 17 and this value is 15. We need to change to:

```
s.precision(std::numeric_limits<double>::max_digits10);
```

**Comment by isuruf** [comment]
> The precision here is not enough to do a round trip. We need 17 and this value is 15. We need to change to:

That would break the roundtrip assertion that `parse(str(expr)) == expr` because `parse` would assume `expr` has more than 53bits of precision.

**Comment by isuruf** [comment]
The core issue is that in sympy, we have the following,
```
In [13]: import sympy

In [14]: sympy.Float(4.347249999999999)
Out[14]: 4.34725000000000
```

**Comment by isuruf** [comment]
Fixed in https://github.com/symengine/symengine.py/pull/399

**Comment by isuruf** [comment]
symengine's printing is consistent with sympy's printing.
```
In [27]: sympy.Float(4.347249999999999)
Out[27]: 4.34725000000000

In [28]: float(sympy.Float(4.347249999999999))
Out[28]: 4.347249999999999
```

**Comment by rikardn** [comment]
True. There are two round trips in play here. `__str__` is supposed to be used for printing, i.e. preserve the string->binary->string round trip. I was thinking about the binary->string->binary round trip that is needed for this issue. The solution suggested above is the right way to fix this so I'll close this issue.
