### ISSUE TITLE
python-symengine  0.9.2 | recent symengine.cse() error

### ISSUE THREAD

**Issue by Audrius-St** [symengine/symengine#1902]
Hello,

I've been using symengine.cse() for some time now for common subexpression elimination in a set of rather long expressions. However, it has recently started to return an error message.

Recent upgrades are
python-symengine   0.9.1 to python-symengine   0.9.2; and
python 3.9.11 to python 3.9.12

A minimal example:

```
import symengine as se
import sympy as sp


def h_HH(x, px, y, py):

    h = (px**2 + py**2)/2 + (x**2 + y**2)/2 + (y*x**2 - (y**3)/3)
    return h


def main():
    # Canonical symbolic variables
    px, x, py, y = sp.symbols('px, x, py, y')

    h_HH_sp_cse = sp.cse(h_HH(x, px, y, py))
    print('Sympy | h_HH_sp_cse:', h_HH_sp_cse, '\n')

    h_HH_se_cse = se.cse(h_HH(x, px, y, py))
    print('Symengine | h_HH_se_cse:', h_HH_se_cse)


if __name__ == "__main__":
    main()
```

returns

```
Sympy | h_HH_sp_cse: ([(x0, x**2)], [px**2/2 + py**2/2 + x0*y + x0/2 - y**3/3 + y**2/2])

Traceback (most recent call last):
  File "/home/audrius/projects/hamiltonian/test/test_symengine_cse.py", line 23, in <module>
    main()
  File "/home/audrius/projects/hamiltonian/test/test_symengine_cse.py", line 18, in main
    h_HH_se_cse = se.cse(h_HH(x, px, y, py))
  File "symengine_wrapper.pyx", line 5476, in symengine.lib.symengine_wrapper.cse
TypeError: 'Add' object is not iterable
```

Ananconda Python installation
python-symengine   0.9.2   py39ha82a1ba_0    conda-forge
symengine   0.9.0  hc116c36_0    conda-forge

python 3.9.12

Ubuntu 20.04
WSL version: 0.56.2.0
Kernel version: 5.10.102.1
WSLg version: 1.0.30

Thank you.

**Comment by isuruf** [comment]
Did this ever work? symengine's cse expects an iterable of expressions, not a single expression.

**Comment by Audrius-St** [comment]
> Did this ever work? 

Yes it did.
I had assumed that one could use symengine.cse() as a drop-in replacement for sympy.cse()

> symengine's cse expects an iterable of expressions, not a single expression.

Would you please elaborate on the correct use of symengine.cse(), as in my minimal example,
as the Symengine documentation is, well, a bit sparse.

Thank you.

**Comment by isuruf** [comment]
Following should work
```
h_HH_se_cse = se.cse([h_HH(x, px, y, py)])
```
SymPy supports that interface too.
```
h_HH_sp_cse = sp.cse([h_HH(x, px, y, py)])
```

**Comment by Audrius-St** [comment]
Yes, the above works.

Thank you.
