### ISSUE TITLE
Printing mpz numbers uses the normal free function

### ISSUE THREAD

**Issue by gbaraldi** [symengine/symengine#1939]
While experimenting with different allocators for malloc in julia, we found a bug in symengine where you call free on a GMP allocation, and that isn't correct, because one can override the allocators there. The correct way of doing it is to use their memory functions. 
This stackoverflow post gives a short example of what should happen https://stackoverflow.com/questions/15691477/c-mpir-mpz-t-to-stdstring. Another option would be to pass a string to gmp instead of using their own allocator.

I don't know if this pattern is done in other places but here is an example https://github.com/symengine/symengine/blob/2ad4e879359a4c19da262f5c122a7daf921a0063/symengine/mp_wrapper.cpp#L24-L30

**Comment by rikardn** [comment]
Thanks for reporting this. Nice catch!

**Comment by rikardn** [comment]
Fixed via #1940
