### ISSUE TITLE
LLVM: Attribute 'uwtable' should have an Argument

### ISSUE THREAD

**Issue by bjodah** [symengine/symengine#1943]
During runtime using our llvm_double JIT I see messages like this:
```
Attribute 'uwtable' should have an Argument                                                                                               
ptr @0
```
https://github.com/symengine/symengine/blob/c01c65f7cdac1d740b56457ee8fb522bc678fc4b/symengine/llvm_double.cpp#L133

I guess this should take a `sync` or `async` argument?
https://llvm.org/docs/LangRef.html

Having both "nounwind" and "uwtable" feels counter-intuitive for me, but perhaps it should be that way, there's probably guidance in the LLVM docs somewhere.

**Comment by lkeegan** [comment]
@bjodah the docs you linked say this about the `uwtable`:
```
This attribute indicates that the ABI being targeted requires that an unwind table entry be produced for this function even if we can show that no exceptions passes by it.
This is normally the case for the ELF x86-64 abi, but it can be disabled for some compilation units.
```
So apparently this is normal, although it also feels counter-intuitive to me!
