### ISSUE TITLE
Design question: should `exp(x)` be its own type/function?

### ISSUE THREAD

**Issue by certik** [symengine/symengine#1984]
A question arose here: https://github.com/lcompilers/lpython/pull/2386 if `exp(x)` should be its own type in SymEngine, or always internally represented as Pow.

In SymPy, `exp(x)` seems to be its own class. In Mathematica `Exp[x]` seems to be just a syntactic sugar for a Pow `E^x`: https://reference.wolfram.com/language/ref/Exp.html

> Literal matchings may fail because exponential functions evaluate to powers with base [E](https://reference.wolfram.com/language/ref/E.html):
In[1]:=MatchQ[Exp[x + y], HoldPattern[Exp[_ + _]]]
Out[1]=false
In[2]:=Exp[x] // FullForm
Power[E, x]

So Mathematica seems to follow the same design as SymEngine, where `exp(x)` just evaluates to `Pow` with base `E`.

Given that, I would keep our current design and not introduce a special `exp(x)` as an alternative to `Pow(E, x)`. I am opening this issue so that we can discuss this and document the decision. Then we can close it.

**Comment by rikardn** [comment]
If there are no good arguments for changing I would vote for staying with the current implementation. There might be some speedups to be found for some cases using a separate function `exp(x)`, but it will also increase complexity.

**Comment by asmeurer** [comment]
We are trying to change this in SymPy https://github.com/sympy/sympy/issues/4898. Currently there's an internal flag you can set to make exp() give a Pow https://github.com/sympy/sympy/pull/20843, but it's hard to completely change. 

Try not to make the same design mistakes as SymPy. Just because SymPy is doing something doesn't mean it was a good idea.

**Comment by certik** [comment]
@asmeurer awesome, thanks! It looks like `exp(x)` should internally just use `E^x`, like SymEngine and Mathematica, and SymPy is moving to this design as well. I think this documents the design, so we can close this issue.

So far I am happy with SymEngine's design choices.

@anutosh491, let's use the internal flag in SymPy introduced in https://github.com/sympy/sympy/pull/20843, then it should behave exactly like in LPython.

**Comment by anutosh491** [comment]
Nice, I like the approach above where we could use some kind of prompt or internal flag to convey that the `exp` class can be treated as `Pow` class
