### ISSUE TITLE
Supporting basic_as_two_terms() through the cwrapper

### ISSUE THREAD

**Issue by anutosh491** [symengine/symengine#2018]
Not sure what's the best way to design this. Should this be addressed similar to how the `basic_as_numer_denom` has been done for the cwrapper ?
https://github.com/symengine/symengine/blob/2b575b9be9bb499d866dc3e411e6368ca0d1bb42/symengine/cwrapper.cpp#L1819-L1826

**Comment by anutosh491** [comment]
cc @rikardn

**Comment by bjodah** [comment]
I think what you propose is the right approach: make it analogous to `basic_as_numer_denom` (the position of the out arguments varying is what it is, hard to unify due to backcomp).

**Comment by anutosh491** [comment]
Sure, if we're looking for a similar approach, we would like to introduce a file just like `symengine/numer_denom.cpp` (maybe `symengine/two_terms.cpp` ?? ) cause we might need something like `SymEngine::as_two_terms` for the same.

**Comment by isuruf** [comment]
What's the use-case for `as_two_terms`? It's only defined for Add and Mul and is used only in internal methods AFAIK.

**Comment by anutosh491** [comment]
Well my use case here was that I was porting the gruntz algorithm from sympy using symengine's c wrapper 
https://github.com/sympy/sympy/blob/8519e0f78a274be5aeabf6d8236f4c7cecd999c3/sympy/series/gruntz.py#L260-L265
```
    elif e.is_Mul or e.is_Add:
        i, d = e.as_independent(x)  # throw away x-independent terms
        if d.func != e.func:
            s, expr = mrv(d, x)
            return s, e.func(i, expr)
        a, b = d.as_two_terms()
```

**Comment by anutosh491** [comment]
@bjodah what are your thoughts on this comment https://github.com/symengine/symengine/issues/2018#issuecomment-2119127722

**Comment by certik** [comment]
Does SymEngine's Mul's `as_two_terms` return the constant number as first element of the tuple, and the rest in the second element?

We probably can expose it in the C API. 

The question is if this operation is needed, or if there is another way to do that. Cannot you get the same thing using "args" or "get_args" ?

**Comment by anutosh491** [comment]
> Does SymEngine's Mul's as_two_terms return the constant number as first element of the tuple, and the rest in the second element?

Yes, this might be something we might want to discuss. So if we have `e = 2*x**3*y**4`. Sympy gives
```
>>> e
2*x**3*y**4
>>> e.as_two_terms()
(2, x**3*y**4)
```
But symengine returns `(2*x**3, y**4)` and hence there is some difference between the two.

But I've raised a PR exposing the `as_two_terms` (#2024), I would say even with the difference it is a start and we might want to go ahead with it.
