### ISSUE TITLE
what():  powint: 'exp' does not fit unsigned long.

### ISSUE THREAD

**Issue by zhongjingjogy** [symengine/symengine#2035]
Segmentation fault is encountered, and the error message is 
```
terminate called after throwing an instance of 'SymEngine::SymEngineException'
  what():  powint: 'exp' does not fit unsigned long.
```

Symengine version 0.9.0 and 0.12.0 are both tested. I use symengine to build an symbolic expression and then convert it to LambdaRealDoubleVisitor. It is seems that the code produce correct evalution results, though it sometime comes out with the error above. The implementation looks like as following, and this code is placed in loop of the `#pragma omp parallel for`. It works fine when thread number is 1, and it fails with thread number larger than 1.
```
std::vector<double> vec(/*size*/);
LambdaRealDoubleVisitor *lambda_func = new LambdaRealDoubleVisitor();
lambda_func->init(com_syms, *expr);
lambda_func->call(vec);
```

I would be very appreciated if any useful hints could be provided. Thanks a lot!

**Comment by isuruf** [comment]
Is there a way to reproduce this?

**Comment by zhongjingjogy** [comment]
The code was not easily to be separated, and I was not able to reproduce the issue with a simplified case. I might try to come back here when I find a solution.
