### ISSUE TITLE
rcp nullptr assertion failure with global constants

### ISSUE THREAD

**Issue by oliverlee** [symengine/symengine#2057]
Here's a simplified example:

```cpp
#include <symengine/expression.h>

const auto a = ::SymEngine::Expression{1};
const auto b = -a;
const auto c = -a;

auto main() -> int
{}
```

output:
```sh
SYMENGINE_ASSERT failed: external/symengine/symengine/symengine_rcp.h
function operator->(), line number 147 at
ptr_ != nullptr
```

This is with release 0.12 and the following settings:

<details>

```cpp
/* Define if you want to enable ASSERT testing in SymEngine */
#define WITH_SYMENGINE_ASSERT

/* Define if you want to enable SYMENGINE_RCP support in SymEngine */
#define WITH_SYMENGINE_RCP

/* Define if you want to enable SYMENGINE_THREAD_SAFE support in SymEngine */
#define WITH_SYMENGINE_THREAD_SAFE

/* Define if you want to enable BOOST support in SymEngine */
#define HAVE_SYMENGINE_BOOST

/* Define if you want to enable PTHREAD support in SymEngine */
#define HAVE_SYMENGINE_PTHREAD

/* Define if the C++ compiler supports default constructors */
#define HAVE_DEFAULT_CONSTRUCTORS

/* Define if the C++ compiler supports noexcept specifier */
#define HAVE_SYMENGINE_NOEXCEPT

/* Define if the C++ compiler supports std::is_constructible */
#define HAVE_SYMENGINE_IS_CONSTRUCTIBLE

/* Define if the C++ compiler supports std::unordered_map<>::reserve() */
#define HAVE_SYMENGINE_RESERVE

/* Define if the C++ compiler has std::to_string */
#define HAVE_SYMENGINE_STD_TO_STRING
```

</details>

**Comment by bjodah** [comment]
You're experiencing [Static Initialization Order Fiasco](https://en.cppreference.com/w/cpp/language/siof). More precisely from the fact that we use a global `one` here: 
https://github.com/symengine/symengine/blob/0ccc20fea491ba0939768a2d74e590df2c1c2a74/symengine/mul.cpp#L355

we should probably add to the documentation that globals that are set to expressions need to be wrapped in a singleton-like structure.

**Comment by bjodah** [comment]
I guess, I've never used that idiom. If my understanding is correct, adding such initializers to all globals defined in SymEngine's namespace would allow for code such as yours to work. Albeit, at a small(?) extra overhead paid by all translation units including some core header of SymEngine. It looks to me like there would need to one "nifty counter" for each global in use? (`zero`, `one`, `pi`, `miunx_one`, .... I count 37 `DEFINE_CONSTANT(...)` in constants.cpp)

So if it is important for us to allow users to create "unprotected" globals of arbitrary expressions, I think that this Nifty Counter looks like a clever solution. Though, my feeling is that the better trade-off would be to require users not to create bare globals, but instead create (singleton) context objects to hold such global variables. (I'm not a fan of globals personally unless those are strictly required).

**Comment by oliverlee** [comment]
What I see as the larger issue is an instantiation order dependency is introduced without an identifier. The expression `Expression{1}` specifies a type `Expression` and a literal `1` -- it does not include references to other global variables. The abstraction is leaky if awareness is necessary and makes it hard to reason about: https://en.wikipedia.org/wiki/Action_at_a_distance_(computer_programming)

In my use case, I specialize a variable template to provide a library information on a foreign type:
```cpp
template <>
inline const auto identity<
  ::SymEngine::Expression,
  std::multiplies<>
> = ::SymEngine::Expression{1};
```
Generally when this constant is used, a copy is created.

In general, singletons are used to create only a single instance of a specific type. I don't see how it would make sense in this situation.
https://stackoverflow.com/questions/86582/singleton-how-should-it-be-used

**Comment by bjodah** [comment]
It's not the `1` that's causing the issue, if you look at the stacktrace you'll see that it's the use of functions such as `mul` that's triggering the bug (unary `operator-` of `Expression` makes use of it).

**Comment by oliverlee** [comment]
> It's not the `1` that's causing the issue, if you look at the stacktrace you'll see that it's the use of functions such as `mul` that's triggering the bug (unary `operator-` of `Expression` makes use of it).

The point I'm trying to make is that there is no explicit reference to other globals in the expression. Introducing hidden dependencies should be encapsulated by the library. 

> `Expression{-1}` should still work I think (untested).

Sure but that's not the multiplicative identity. 

Irrespective of the implementation details, `-Expression{1}` and `Expression{-1}` should be equivalent in some sense and neither should segfault. 

Or do you see those as partial functions with preconditions?

**Comment by bjodah** [comment]
I agreee. We could try encapsulating globals used by the library using the nifty counter.

**Comment by rikardn** [comment]
I would also count this as a bug. Would one solution be to let `one` etc be `inline` functions in the hope that the compiler could optimize the call away, or is that hoping too much?

**Comment by oliverlee** [comment]
Compiler optimizations are not intended to change program semantics except in specific cases (e.g. -funsafe-math), see the [as-if rule](https://en.cppreference.com/w/cpp/language/as_if).

Declaring the constant as `inline` would allow multiple definitions, one in each translation unit, and static initialization order would no longer be an issue. However, the definition needs to be available in the header and `inline` variables require C++17. Given that there exist preprocessor defines for declaring that the compiler supports C++11 features, I assume the minimum standard target is a prerelease of C++11.

**Comment by isuruf** [comment]
This was supposed to be fixed in https://github.com/symengine/symengine/pull/1849. I wonder if we added a new constant or if that PR was insufficient

**Comment by isuruf** [comment]
Opened a PR at https://github.com/symengine/symengine/pull/2059
