### ISSUE TITLE
`subs` is slow in sympy

### ISSUE THREAD

**Issue by jcrist** [symengine/symengine#216]
In `sympy.physics.mechanics` we sometimes generate expressions that have operation counts > 100,000. Some of the code relys on subbing in 0 for certain symbols to partition the equations into different matrices. For shorter expressions, this is fine, but for longer `subs` ends up being far too slow to be practical.

Attached is a benchmark file with an example expression and `subs` operation. Could be useful for testing improvements to `subs` made in csympy.

[benchmark file](https://gist.github.com/jcrist/152a68d6d0115b086284)

**Comment by isuruf** [comment]
`benchmarks/pydy_pendulum.py` in python repo implements this
