### ISSUE TITLE
Implement abs(x) and exp(x)

### ISSUE THREAD

**Issue by certik** [symengine/symengine#297]
And wrap it into Python. Implement and test `.diff()`.

Fix is provided in the following PRs. TODO:

* [x] merge #323
* [x] merge #325 
* [x] merge #333

**Comment by Sumith1896** [comment]
@certik What remains here?

**Comment by Sumith1896** [comment]
@certik Can this be closed?

**Comment by certik** [comment]
I think it's done. Thanks.
