### ISSUE TITLE
New benchmark

### ISSUE THREAD

**Issue by certik** [symengine/symengine#298]
Here is a great benchmark for SymPy: https://github.com/sympy/sympy/issues/8191

Here is a script that loads the expressions into SymPy, converts to CSymPy and then benchmarks SymPy and CSymPy side by side:
```python
print "Import"
from timeit import default_timer as clock
import sympy
from csympy import *
print "SymPy sympify"
print "A"
A_sympy = sympy.sympify(open("/tmp/dis_eom.txt").read())
print "x"
x_sympy = sympy.sympify(open("/tmp/partials.txt").read())
print "CSymPy sympify"
print "A"
A = sympify(A_sympy)
print "x"
x = sympify(x_sympy)
print "Benchmark SymPy:"
t1 = clock()
A_diff = A_sympy[9].diff(x_sympy[9])
t2 = clock()
print "  time:", t2-t1
print "Benchmark CSymPy:"
t1 = clock()
A_diff = A.get(9, 0).diff(x[9])
t2 = clock()
print "  time:", t2-t1
```
It produces:
```
Import
SymPy sympify
A
x
CSymPy sympify
A
x
Benchmark SymPy:
  time: 6.99376392365
Benchmark CSymPy:
  time: 0.0134890079498
```

However, currently the csympy benchmark is not equivalent to the sympy one, see below.

TODO:
* [x] Fix #295, otherwise this script doesn't even run
* [ ] Fix #297. Without it, the csympy expression contains unknown functions `exp` and `abs`, and then csympy doesn't know how to differentiate them, so `exp(x).diff(x)` doesn't become `exp(x)` but rather `Derivative(exp(x), x)`, so this is a problem.
* [ ] Make sure that the two final expressions from sympy and csympy are equal.

**Comment by isuruf** [comment]
I ran 
```
a = A_sympy[9].diff(x_sympy[9])
b = A.get(9, 0).diff(x[9])
(sympify(a) - b).expand()
```
and it gives the output `0` after 30 seconds.

**Comment by isuruf** [comment]
To check for correctness of the csympy expression, I should have used sympy to expand, but sympy's `expand` function takes forever to expand.

**Comment by isuruf** [comment]
This benchmark is in Python repo
