### ISSUE TITLE
Building on OS X

### ISSUE THREAD

**Issue by sushant-hiray** [symengine/symengine#344]
I recently shifted to OS X and since then I'm having problems compiling the project.

By default CMAKE was using Apple's Clang and while compiling it was throwing tons of warnings and errors:

```
/Users/sushanthiray/Documents/csympy/src/rational.h:230:36: error: a space is required between consecutive right angle brackets
      (use '> >')
        const Ptr<RCP<const Integer>> &den);
                                   ^~
                                   > >
```

```
#error <atomic> is not implemented
 ^
```

So I figured that clang is perhaps to be blamed.

Next I tried shifting to GNU version. I installed gcc/g++ via homebrew.

```
export CC=/usr/local/bin/gcc-4.8
export CXX=/usr/local/bin/g++-4.8
```

In this case `cmake .` works fine. However, `make` throws a tons of errors.

```
sushanthiray@osx ~/Documents/csympy (master)$ make
Scanning dependencies of target csympy
[  2%] Building CXX object src/CMakeFiles/csympy.dir/csympy_rcp.cpp.o
[  4%] Building CXX object src/CMakeFiles/csympy.dir/basic.cpp.o
/var/folders/kd/2cn941c55c58_9yddmh90nvc0000gn/T//ccBYz3qd.s:67:no such instruction: `vzeroupper'
/var/folders/kd/2cn941c55c58_9yddmh90nvc0000gn/T//ccBYz3qd.s:79:no such instruction: `vzeroupper'
/var/folders/kd/2cn941c55c58_9yddmh90nvc0000gn/T//ccBYz3qd.s:445:no such instruction: `vzeroupper'
/var/folders/kd/2cn941c
```

There was a minor discussion regarding this issue on gitter. But I guess, they did not pursue this further.

I found the fix for this on this [SO answer](http://stackoverflow.com/questions/10327939/erroring-on-no-such-instruction-while-assembling-project-on-mac-os-x-lion)
So I removed `'-march=native'` from the `UserOverride.cmake` file.
However it throws a linking error:

```
Undefined symbols for architecture x86_64:
  "operator<<(std::basic_ostream<char, std::char_traits<char> >&, __mpq_struct const*)", referenced from:
      CSymPy::Complex::__str__() const in libcsympy.a(complex.cpp.o)
...
...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

```

I found a couple of fixes such as explicitly using `-lstdc++` but those haven't worked for me yet.
So I'm still looking for the fix for this.

**Comment by certik** [comment]
@sushant-hiray would you mind checking the latest git version on OS X? Does it compile now?

**Comment by certik** [comment]
@sushant-hiray one more thing --- how do we enable OS X testing on Travis? I think it should be relatively simple now with our updated Travis test files.

**Comment by sushant-hiray** [comment]
I'll look into it and get back to you

**Comment by sushant-hiray** [comment]
I just had a look into the building of current master. It builds fine for AppleClang.
However a couple of printing tests are failing:

`assert(r2->__str__() == "(y + x)^(2/3)*x" );` . It actually prints `x*(y + x)^(2/3)`
`assert(r->__str__() == "1/((y + x)*x)");` It actually prints `1/(x*(y + x))`
`assert(r1->__str__() == "-y/((y + x)*x)");` It actually prints `-y/(x*(y + x))`

The only issue with all of them is the order of `x` in printing.

**Comment by isuruf** [comment]
See #355

**Comment by isuruf** [comment]
@sushant-hiray, do you still get the error, `no such instruction: vzeroupper` while building with `g++-4.8`?

**Comment by sushant-hiray** [comment]
I'll test it first thing morrow and revert back.

**Comment by isuruf** [comment]
Closing this now that we have CI running in travis-ci OSX images.
