### ISSUE TITLE
Build a shared library

### ISSUE THREAD

**Issue by certik** [symengine/symengine#360]
For example, the Julia wrappers will require a shared library. One can enable shared library by adding the `-DBUILD_SHARED_LIBS:BOOL=ON` option to the cmake command line. Alternatively, one can apply the following patch:

``` diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index fdfe053..34f5164 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -46,7 +46,7 @@ configure_file(csympy_config.h.in csympy_config.h)
 # Include the config file:
 include_directories(BEFORE ${csympy_BINARY_DIR}/src)

-add_library(csympy ${SRC})
+add_library(csympy SHARED ${SRC})

 install(TARGETS csympy
             RUNTIME DESTINATION bin
```

What we need to decide is:
- should we only build static libraries (answer is no, for example Julia requires a shared library)
- should we only build shared libraries? (if yes, then we just apply the patch above)
- should we build static and shared libraries? If yes, then:
  - should we allow the user to choose one or the other, in which case the `-DBUILD_SHARED_LIBS:BOOL=ON` does it
  - should we build static and dynamic libraries at the same time? (One can use [this](http://stackoverflow.com/a/2152157/479532) approach)

**Comment by isuruf** [comment]
I tried the patch and `PYTHON_INSTALL` tests fail when csympy is built as a shared library.
Btw, we should apply this patch to call from julia easily.
```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index fdfe053..225b675 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -46,7 +46,7 @@ configure_file(csympy_config.h.in csympy_config.h)
 # Include the config file:
 include_directories(BEFORE ${csympy_BINARY_DIR}/src)
 
-add_library(csympy ${SRC})
+add_library(csympy SHARED ${SRC})
 
 install(TARGETS csympy
             RUNTIME DESTINATION bin
@@ -55,5 +55,6 @@ install(TARGETS csympy
         )
 install(FILES ${HEADERS} "${csympy_BINARY_DIR}/src/csympy_config.h"
     DESTINATION include)
+target_link_libraries(csympy teuchos ${LIBS})
 
 add_subdirectory(tests)
```

**Comment by pbrady** [comment]
very cool.  I'll try this out at some point this weekend.

**Comment by isuruf** [comment]
I think we should allow the user to decide and make shared library the default

**Comment by certik** [comment]
That makes sense. If we put `SHARED` there, then I think `-DBUILD_SHARED_LIBS:BOOL=ON` will not work, will it? Another option might be to somehow make the `BUILD_SHARED_LIBS` variable `ON` as default, if the user doesn't specify it.

**Comment by thilinarmtb** [comment]
What about creating both dynamic and static libraries? What are the cons? My concern is that whether the average user be able to decide which type of library he wants.

**Comment by certik** [comment]
Currently I don't know. We need to see what the "standard" is, i.e. whether to always build both, or just one and which one.

**Comment by pbrady** [comment]
I haven't conducted any kind of survey but for most of the packages I compile, (i.e. MPI, hdf5 and so forth) they do not build shared libraries by default.

**Comment by isuruf** [comment]
Option is `-DBUILD_SHARED_LIBS=yes`, but defaults to static. Generally, CMake projects don't build both static and shared at the same time.
