### ISSUE TITLE
Add series expansion

### ISSUE THREAD

**Issue by certik** [symengine/symengine#362]
And compare against other codes. 

Here is one example from sympy: https://github.com/sympy/sympy/issues/2635

**Comment by thilinarmtb** [comment]
+1

**Comment by rwst** [comment]
Both `sympy.series` and the internal `rs_series` will need `Expr` member functions (because `Symbol` and `Function` subclasses from it). Currently everything in symengine subclasses from `Basic` not `Expression` so nothing will work that needs `Expr` functionality.

**Comment by certik** [comment]
In SymEngine, we don't even have an Expr. In fact, it looks like we'll be able to implement all of the functionality using the visitor pattern or single dispatch, so the Basic class itself doesn't need many methods. However, in the Python wrappers, we certainly should make it work with both SymPy and Sage, so if it means we need to subclass Expr, then we should do it there.

**Comment by rwst** [comment]
Another part would be a port of the `Order` function.

**Comment by certik** [comment]
The `Order` function/class can be added in the higher level api. In the low level `rs_*` functions, the order is specified by the user and the function returns that many terms, so that things are fast.

**Comment by rwst** [comment]
Univariate series expansion is now in symengine, so this can be closed.
