### ISSUE TITLE
Idea: Make RCP always non-null

### ISSUE THREAD

**Issue by certik** [symengine/symengine#378]
Pros: it simplifies (speeds up) code in the `RCP` class

Cons: now every single `RCP<const Basic>` declaration must be assigned to something, e.g. `zero`, even if later you assign something else to it.

The PR #125 implements that. It seems to work, but no noticeable change in benchmarks.

**Comment by rwst** [comment]
Can this be closed?

**Comment by rikardn** [comment]
Since this was tested 6 years ago without any improvement I'll do some spring cleaning and close the issue.

**Comment by certik** [comment]
Yes, let's close it.
