### ISSUE TITLE
Implement single dispatch

### ISSUE THREAD

**Issue by certik** [symengine/symengine#381]
Currently, the `expand` functionality is doing linear search over all classes, see here:

https://github.com/sympy/csympy/blob/368de67cec408d6fe57adf1c33dc812c93b0c5c6/src/basic.cpp#L35

We should rather implement single dispatch --- ask the object type using `Basic::get_type_code` (https://github.com/sympy/csympy/blob/368de67cec408d6fe57adf1c33dc812c93b0c5c6/src/basic.h#L105) and lookup the function to call directly in some kind of an array. We have to figure out some nice API, so that the user can register his or her own functions easily.

Then `expand`, `diff`, later series expansion, printing, all the things we currently use the visitor pattern for and any other functionality should start using it. If it works, we should then retire the visitor pattern.

**Comment by shivamvats** [comment]
I'll try to summarize what I've understood. 
We'll store pointers to different functions in an array indexed according to its `TypeID`. When `expand` gets called on a class, we figure out its type using `get_type_code` and call the appropriate function from the array.
Am I correct?

Is there any project that uses something similar? We could use that for reference.

**Comment by certik** [comment]
That's correct.

Julia has single and multiple dispatch for example. So do C++ virtual methods (virtual method table). I wouldn't try to over design this --- just take the current `diff` or `expand` implementation and port it to use single dispatch. Once we have the code working, we'll see what the most efficient and comfortable way is.

**Comment by isuruf** [comment]
This may be useful http://members.gamedev.net/sicrane/articles/dispatch.html

**Comment by certik** [comment]
Here is initial implementation: #384.

**Comment by isuruf** [comment]
This can be closed now. Visitor pattern is better than single dispatch in benchmarks.

**Comment by certik** [comment]
Ok, that works.
