### ISSUE TITLE
Python install prefix confusion

### ISSUE THREAD

**Issue by certik** [symengine/symengine#393]
When you install csympy like this, you get an error:
```
$ CC=gcc CXX=g++ cmake -DCOMMON_DIR=$HASHSTACK -DWITH_PYTHON=yes -DCMAKE_INSTALL_PREFIX:PATH="some_dir" .
...
Installation prefix: some_dir
...
Python install path: /home/certik/repos/hashstack/default/lib/python2.7/site-packages
...
-- Installing: /home/certik/repos/csympy/some_dir/include/cwrapper.h
-- Installing: /home/certik/repos/csympy/some_dir/include/csympy_config.h
-- Installing: /home/certik/repos/csympy/some_dir/lib/libteuchos.a
CMake Error at csympy/cmake_install.cmake:44 (FILE):
file cannot create directory:
/home/certik/repos/hashstack/default/lib/python2.7/site-packages/csympy.
Maybe need administrative privileges.
Call Stack (most recent call first):
cmake_install.cmake:39 (INCLUDE) 
```
Full log here: https://gist.github.com/certik/dad5626bebf708d6d2c7

As you can see the problem is that the "Python install path" (`PYTHON_INSTALL_PATH` variable) is wrong. It can be fixed like this:
```
$ CC=gcc CXX=g++ cmake -DCOMMON_DIR=$HASHSTACK -DWITH_PYTHON=yes -DCMAKE_INSTALL_PREFIX:PATH="some_dir" -DPYTHON_INSTALL_PATH="lib/python2.7/site-packages" .
...
Installation prefix: some_dir
...
Python install path: lib/python2.7/site-packages
...
-- Installing: /home/certik/repos/csympy/some_dir/include/cwrapper.h
-- Installing: /home/certik/repos/csympy/some_dir/include/csympy_config.h
-- Installing: /home/certik/repos/csympy/some_dir/lib/libteuchos.a
-- Installing: /home/certik/repos/csympy/some_dir/lib/python2.7/site-packages/csympy/__init__.py
-- Installing: /home/certik/repos/csympy/some_dir/lib/python2.7/site-packages/csympy/utilities.py
-- Installing: /home/certik/repos/csympy/some_dir/lib/python2.7/site-packages/csympy/lib/csympy_wrapper.so
-- Removed runtime path from "some_dir/lib/python2.7/site-packages/csympy/lib/csympy_wrapper.so"
-- Installing: /home/certik/repos/csympy/some_dir/lib/python2.7/site-packages/csympy/lib/__init__.py
```
Full log: https://gist.github.com/certik/971bbca783c097d7e6e0

But this is confusing. By default, the `PYTHON_INSTALL_PATH` should be automatically set to the right thing, so that the user can just control where to install using `CMAKE_INSTALL_PREFIX`, only if he or she wants to install the Python wrappers into a non-standard location, then `PYTHON_INSTALL_PATH` can be set directly to something else.

**Comment by benruijl** [comment]
I second this. I want to make a package for Arch Linux, which requires the installation in a package directory ~/somedir/usr instead of in /usr. The prefix CMAKE_INSTALL_PREFIX works for the regular files but not for the python files.

**Comment by certik** [comment]
For now just set the `-DPYTHON_INSTALL_PATH="lib/python2.7/site-packages"` in the installation script (or modify it using Arch's conventions).

Can you make the package and let us know if anything needs to be fixed (besides #390)? If it works, we'll make a release (0.1) so that you can package the release.

**Comment by benruijl** [comment]
@certik A small problem is that I actually cannot hardcode the python path, since it changes when the python version is updated. Unfortunately, I really have to add a prefix. Beside this point, the package seems to be working nicely.

**Comment by isuruf** [comment]
Fixed in symengine/symengine.py#8
