### ISSUE TITLE
Remove pytest dependency

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#416]
Currently we are using `pytest` to run tests from within a python shell.
Therefore it is not possible to run the tests from a python environment with no `pytest`. (Eg: sage)

**Comment by certik** [comment]
What would you use instead of pytest? Nosetests? csympy works with nosetests as well.

**Comment by thisch** [comment]
Why don't you install pytest in the sage environment?

**Comment by certik** [comment]
Right, that would be my other suggestion.

**Comment by isuruf** [comment]
I did install pytest and it works fine. I was wondering if there was a simple pure Python way to do it, without asking the sage users to install a dependency.

**Comment by pbrady** [comment]
There is `unittest` but it puts some rather stringent requirements on the tests.

**Comment by certik** [comment]
Or one can use sympy's pure python tester. I wouldn't recommend it, it's
too much code to maintain.

**Comment by rwst** [comment]
This is rather about symengine.py, right?

**Comment by isuruf** [comment]
Yes, this is about symengine.py
