### ISSUE TITLE
Overload integer method to accept signed and unsigned long

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#461]
Currently integer only accepts `int` and `mpz_class`. For `long` we have to do `integer(mpz_class(6167950454))`

**Comment by Sumith1896** [comment]
Methods are required for `long long` and `unsigned long long`, right?

**Comment by isuruf** [comment]
`gmp` does not support `long long`, so `long` is enough. (Both types are the same on my computer)

**Comment by certik** [comment]
+1.

**Comment by mafiya69** [comment]
I think this can be closed now.

**Comment by Sumith1896** [comment]
Yes, it can be closed. Thanks @mafiya69 for working on this!

**Comment by certik** [comment]
Fixed in #647.
