### ISSUE TITLE
Test `make install` includes all the headers.

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#462]
Currently `eval_arb.h` is not included in the list of headers used in `make install`, but CI does not give any errors because it is not tested.

**Comment by certik** [comment]
+1

**Comment by mafiya69** [comment]
I think this one is solved (ref : [Line 59 - CMakeLists.txt]( https://github.com/symengine/symengine/blob/master/symengine/CMakeLists.txt#L59))

**Comment by Sumith1896** [comment]
They are installed but not tested, if I am not mistaken.
