### ISSUE TITLE
Integrate gmp and related gems with the ruby bindings

### ISSUE THREAD

**Issue by abinashmeher999** [symengine/symengine#490]
The library currently uses `gmp`, `mpfr` and `mpc` libraries. Data types from these libraries, like `mpz_t`, `mpq_t` are used for the inputs to the functions in the c wrappers. Since SymEngine can accept these data types and utilise it for operations, the Ruby bindings should also be able to do it. I came to know that there are ruby bindings for these libraries([gmp](https://www.ruby-toolbox.com/projects/gmp), [ruby-mpfr](https://www.ruby-toolbox.com/projects/ruby-mpfr), [gnu_mpc](https://www.ruby-toolbox.com/projects/gnu_mpc) and [ruby-mpc](https://www.ruby-toolbox.com/projects/ruby-mpc)) as well. If #478 is addressed and same is done for other data types, then we can wrap it ourselves. Else or along with the previous approach, we should also plan on integrating these gems with the symengine gem. This would involve extracting the `c` information from objects of the classes in those gems, and then using it with the C API used in our bindings.

**Comment by rwst** [comment]
Isn't this an issue with symengine.rb only? If not, which part is symengine?
