### ISSUE TITLE
Automatically build binary packages using CI for Linux, Mac and Windows and deploy them

### ISSUE THREAD

**Issue by certik** [symengine/symengine#550]
We should use Travis and AppVeyor to do that and upload to e.g. anaconda.org.

http://www.appveyor.com/docs/deployment

Also, we should use this to create releases automatically:

http://www.appveyor.com/docs/deployment/github

E.g. master should always build our release tarballs and upload them somewhere for development testing. And when a commit is tagged, it would upload these into the github release.

**Comment by isuruf** [comment]
This is done in https://github.com/symengine/symengine-feedstock
