### ISSUE TITLE
RPath is not set when building shared libs

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#600]
When building shared libs, rpath is removed when installing. 

When the library being linked to is not a system library,
- We need to manually link with the library OR
- When building give `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes`

**Comment by certik** [comment]
Yes, that's the way cmake works. I don't know if it is a good practice to make it the default or not. In other projects I set `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes` by hand if needed.

**Comment by isuruf** [comment]
You are right. This option can be given when needed and doesn't need to be added by default.
