### ISSUE TITLE
python setup.py sdist does not include CMakeLists.txt, C++ sources etc.

### ISSUE THREAD

**Issue by bjodah** [symengine/symengine#609]
It would be nice if the tarball generated by `python setup.py sdist` was self-contained with respect to symengine sources, i.e. the only prerequisities for building from a source distribution would be a C++11 compiler, cmake and libgmp (with dev headers).

Currently the source distribution exits with a CMake error due to the lack of CMakeLists.txt files.
I think that all that needs to be done is to define include patterns in a `MANIFEST.in` file.

**Comment by certik** [comment]
See also #608.

**Comment by bjodah** [comment]
Since python bindings are provided by symengine.py I close this issue.
