### ISSUE TITLE
style: use and, or, not

### ISSUE THREAD

**Issue by rwst** [symengine/symengine#637]
(edited, reopened)
For readability at least these three should be used:
 * `and` instead of `&&`
 * `or` instead of `||`
 * `not` instead of `!`

The full set is at http://en.cppreference.com/w/cpp/language/operator_alternative
Don't forget to `#include <ciso646>` which enables it for MSVC, too.

This ticket should do a clean up of remaining usages of `&&`,`||`,`!`.

**Comment by certik** [comment]
I didn't know you can use those in C++. If MSVC supports them as well, then we should use it.

**Comment by rwst** [comment]
I thought they were C++11 but your question made me research more. These are interesting:
http://stackoverflow.com/questions/2376448/the-written-versions-of-the-logical-operators
http://stackoverflow.com/questions/555505/c-alternative-tokens/555524

So, I still don't know about MSVC++, can someone check on Windows please?

**Comment by isuruf** [comment]
It seems MSVC do not support it. https://ci.appveyor.com/project/isuruf/symengine/build/543/job/f2oe7edbvnkvqcho

**Comment by rwst** [comment]
Oh well, that was that. Thanks!

**Comment by isuruf** [comment]
Although not as a keyword, we can do `#include <ciso646>` which defines `and` to be `&&` etc.
`ciso646` is a standard header, so there are no portability issues. (On `g++`, the header is empty).

**Comment by certik** [comment]
Actually, they should work in MSVC with an option:
http://stackoverflow.com/questions/555505/c-alternative-tokens/555524#555524

I like it, it's much more readable to use them, it looks more like Python
and is less error prone.

**Comment by rwst** [comment]
OK, I added to the ticket description and reopened.

**Comment by certik** [comment]
@rwst can you try adding the `/Za` option and *not* including the `<ciso644>` header for MSVC? It looks like that should fix it.

**Comment by isuruf** [comment]
It fixes the earlier issues, but introduces new ones.

https://ci.appveyor.com/project/isuruf/symengine/build/545/job/nmbo8mg9u09uvxj3

**Comment by certik** [comment]
Ok, we can include `ciso646` then for MSVC. We can put it into some of our header files that's always included.
