### ISSUE TITLE
Include all used C++ library headers in basic.h

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#643]
C++ standard library headers used are scattered in individual files, but should be included in one place like `basic.h`

**Comment by certik** [comment]
What is the motivation to have all C++ standard library headers at one place?

**Comment by isuruf** [comment]
It was because some library headers were only included in only a few headers and changing the order of how we include the headers may lead to errors. For eg: #594.
I first thought there was a similar issue in #642, but it was not.

**Comment by certik** [comment]
I see, thanks. That's fine with me.

**Comment by CodeMaxx** [comment]
is this resolved?

**Comment by rwst** [comment]
In principle it will never be resolved because I at least put new headers in the specific cpp file. Others who will not be aware of this will too, and then we'll have a mixed state again.

**Comment by Sumith1896** [comment]
I think we can take care of this while reviewing or better add it to the style guide. Whatever seems better.
