### ISSUE TITLE
`Expression` needs to be `Basic`

### ISSUE THREAD

**Issue by rwst** [symengine/symengine#650]
This will not work:
```
    RCP<const Symbol> x = symbol("x"), y = symbol("y");
    auto z = sin(Expression(1)+cos(x));
```
because `sin` expects a `Basic`. So make `Expression` a `Basic` too.

**Comment by certik** [comment]
Basic class cannot be instantiated on stack. So this probably won't work.
But maybe there is a way to have a constructor in Basic that can accept
Expression.

**Comment by harakas** [comment]
Btw what is the purpose of Expression? And why are the following missing from symengine:
```c++
  RCP<const Basic> operator+(const RCP<const Basic> &a, const RCP<const Basic> &b) { return add(a, b); }
  RCP<const Basic> operator-(const RCP<const Basic> &a, const RCP<const Basic> &b) { return sub(a, b); }
  RCP<const Basic> operator*(const RCP<const Basic> &a, const RCP<const Basic> &b) { return mul(a, b); }
  RCP<const Basic> operator/(const RCP<const Basic> &a, const RCP<const Basic> &b) { return div(a, b); }
```
And where should I be asking questions like this (or finding answers)?

**Comment by certik** [comment]
You can use gitter, see the readme. Or a mailinglist.

**Comment by rwst** [comment]
`Expression` is not used in symengine, it just wraps `Basic` functions, I think I won't use it either. Maybe then I'll get to know why we need it.
