### ISSUE TITLE
Trigonometric functions crash or return nonsense on negative pi multiple

### ISSUE THREAD

**Issue by harakas** [symengine/symengine#652]
cos(neg(pi)) crashes or returns nonsense. I think the problem is that in functions.cpp it is assumed that operator % works as it does in Python. But in C/C++ the modulo operator returns a negative number if the first operand is negative.This results in a negative index (from eval()) that is applied to the sin_table[], resulting in garbage or crash.

**Comment by certik** [comment]
Thanks for the bug report! We need to fix it.
