### ISSUE TITLE
rational syntactic sugar

### ISSUE THREAD

**Issue by rwst** [symengine/symengine#660]
I would like to do in SymEngine:
```
auto q = Rational(2,3);
```

**Comment by certik** [comment]
Looks like currently you have to do:
```
auto q = Rational::from_two_ints(*integer(2), *integer(3));
```
or
```
auto q = Rational::from_mpq(mpq_class(2, 3));  # only if 2/3 is in canonical form !!
```
You can't do just `Rational(2, 3)`, since one has to use RCP. But we can provide an overload for integers, so that you can do:
```
auto q = Rational::from_two_ints(2, 3);
```
We can also implement a `rational` function (similar to the `integer` function):
```
auto q = rational(2, 3);
```
