### ISSUE TITLE
is_positive and is_negative in complex need to be corrected

### ISSUE THREAD

**Issue by abhinavagarwal07** [symengine/symengine#676]
Both of `is_positive` and `is_negative` always returns false because complex cannot be compared with zero. However 
```C++
inline virtual bool is_positive() const {
        return false;
    }
```
should be changed to
```C++
inline virtual bool is_positive() const {
        return (this->imaginary_ ==0 ? (this->real_>0?true:false) : false);
    }
```
and similarly for `is_positive()`
because if imaginary part of a complex number is zero it is essentially a real number and can be compared to zero

**Comment by isuruf** [comment]
In a `Complex` object, imaginary part cannot be zero. If it is, then we create a `Rational` or `Integer` depending on the real part. Therefore you are guaranteed that the imaginary part of a `Complex` is never zero. (We check that this is true in `is_canonical` and in methods like `Complex::from_two_nums`, an appropriate object is returned.)

**Comment by rwst** [comment]
I would throw an exception in `is_positive/negative`. Returning `False` may mask an error.

**Comment by abhinavagarwal07** [comment]
@isuruf 
In that case all functions like
  virtual bool is_zero() const { return ((this->real_ == 0) and (this->imaginary_ == 0)); }
    //! \return `true` if `1`
    virtual bool is_one() const { return ((this->real_ == 1) and (this->imaginary_ == 0)); }
    //! \return `true` if `-1`
    virtual bool is_minus_one() const { return ((this->real_ == -1) and (this->imaginary_ == 0)); }
    //! \return `true` if both `real_` or `imaginary_` are zero
    // This is needed while printing inside `mul`.
    inline bool is_reim_zero() const { return ((this->real_ == 0) or (this->imaginary_ == 0)); }
    //! \return `true` if `real_`  is zero
    inline bool is_re_zero() const { return (this->real_ == 0); }
    /*! Add Complex

are redundant ?

**Comment by isuruf** [comment]
@abhinavagarwal07, yes. They should be fixed.

**Comment by abhinavagarwal07** [comment]
They should be removed then ?
