### ISSUE TITLE
Implement SymPy's as_numer_denom in SymEngine

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#681]
See https://github.com/sympy/sympy/issues/5706#issuecomment-37001886 for some different ways of implementing this.

**Comment by srajangarg** [comment]
@isuruf I am trying to implement this (as the old slow way for now). Could you give me a brief about where I should start exactly, and what changes I might have to make?
I presume I should start with `Div`?

**Comment by isuruf** [comment]
What do you mean by `Div`? 
Since there are two outputs numer and denom, you can take two pointers as input. For example see `gcd_ext`.

**Comment by isuruf** [comment]
Closed via #731

**Comment by mlangiu** [comment]
Hi, I just noticed that there are still differences in Sympy / Symengine outputs for fractions expressed using exponentiation:

```python
import sympy, symengine

for backend in sympy, symengine:
import sympy, symengine

for backend in sympy, symengine:
    print(backend.__name__, backend.__version__)
    expr = backend.S('x')**0.5 * backend.S('y')**(-0.25)
    print(expr.as_numer_denom())
```

gives me 

```python
sympy 1.6.2
(x**0.5, y**0.25)
symengine 0.6.1
(1.0*x**0.5, 1.0*y**0.25)
```

**Comment by mlangiu** [comment]
Also trying to fix this manually I discovered:

```python
for backend in sympy, symengine:
    print(f'{backend.S(1) == 1 = }')
    print(f'{backend.S(1.) == 1 = }')
```    

```python
backend.S(1) == 1 = True
backend.S(1.) == 1 = True
backend.S(1) == 1 = True
backend.S(1.) == 1 = False
```

**Comment by mlangiu** [comment]
@symengine: Should I rather open a new issue instead?

**Comment by isuruf** [comment]
@mlangiu, yes please.
