### ISSUE TITLE
Test latest gcc in travis

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#684]
Issue came up here, https://github.com/symengine/symengine/pull/661

**Comment by CodeMaxx** [comment]
@isuruf Does this require changing the `.travis.yml` file?

**Comment by isuruf** [comment]
Yes

**Comment by CodeMaxx** [comment]
Do we require an additional check with gcc 5.3 or replace the gcc 4.8 check with gcc 5.3 check?

**Comment by isuruf** [comment]
Closed via #727
