### ISSUE TITLE
rationals

### ISSUE THREAD

**Issue by abhinavagarwal07** [symengine/symengine#693]
can a rational number have `den` negative ?

**Comment by isuruf** [comment]
You mean a `Rational`? Then no.

**Comment by abhinavagarwal07** [comment]
Yes, I think `Rational` should not have negative `den` rather `num` should be positive/negative.
Though in file rational.h
many function like : 
`bool is_positive() const` 
checks for sign of `den` 
similarly in functions.cpp
many function like : 
`RCP<const Basic> atan2(const RCP<const Basic> &num, const RCP<const Basic> &den)` 
also checks for sign of den

**Comment by isuruf** [comment]
Functions like `Rational::is_positive()` should be corrected.

On the other hand, functions like `RCP<const Basic> atan2(const RCP<const Basic> &num, const RCP<const Basic> &den)` should check for sign of den.

**Comment by abhinavagarwal07** [comment]
+1

`Functions like Rational::is_positive() should be corrected.`
I'm on it!

`On the other hand, functions like ... should check for sign of den`
if we are sure of `den` to be positive, then why to check it's sign again?

**Comment by isuruf** [comment]
Because we are not sure what the user input will be for `atan2`. Also the whole point of `atan2` instead of using `atan` is to identify which quadrant the angle will be in. Therefore for `atan2`, sign of `den` affects the output of the function.
