### ISSUE TITLE
increase constness 

### ISSUE THREAD

**Issue by abhinavagarwal07** [symengine/symengine#696]
Function `bool is_canonical` in some files like `rational.h`, `polynomial.h` can be made const.
`bool is_canonical(const RCP<const Basic> &arg);`
to
`bool is_canonical(const RCP<const Basic> &arg) const;`

**Comment by certik** [comment]
+1

**Comment by isuruf** [comment]
@certik, why are `is_canonical` member functions? They should be static methods of the class right?

**Comment by certik** [comment]
I think they could be static functions. It's not a big deal I think.
