### ISSUE TITLE
Add polygamma function

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#698]
See https://en.wikipedia.org/wiki/Polygamma_function

Also return a `polygamma` instant for `gamma::diff(x)`

**Comment by abhinavagarwal07** [comment]
I'll look into it

**Comment by abhinavagarwal07** [comment]
I have come up with
```
RCP<const Basic> PloyGamma::rewrite_as_zeta()
{
    // http://mathworld.wolfram.com/PolygammaFunction.html
    if(n_ & 1)
        return mul(factorial(n_),zeta(add(n_,one),arg_));
    return mul(minus_one,mul(factorial(n_),zeta(add(n_,one),arg_)));
}
```
and we can also write it in terms of Riemann zeta when arg_ is 1 or 1/2

**Comment by abhinavagarwal07** [comment]
I think we should have 2 different function `PolyGamma` and `DiGamma` function, because most of representation of `PolyGamma` require `m>0` and `m=0` is case of `DiGamma`

**Comment by isuruf** [comment]
I don't think that's necessary. SymPy returns a `PolyGamma(0, x)` when `digamma(x)` is called.

**Comment by abhinavagarwal07** [comment]
It can be closed now
https://github.com/symengine/symengine/pull/745
https://github.com/symengine/symengine/pull/752
