### ISSUE TITLE
New expand bug

### ISSUE THREAD

**Issue by cbehan** [symengine/symengine#705]
Like pull 556, I expect this to take many painful hours. But what I've noticed is this: `foo = 2*(x + 1) + 3*x*(x + 1)` now expands to `2 + 11*x + 3*x**2` instead of `2 + 5*x + 3*x**2`. Merry xmas!

**Comment by certik** [comment]
Thanks for reporting this! That's a serious bug that we need to fix soon
and add tests.

**Comment by isuruf** [comment]
Sent a PR #708 to fix this
