### ISSUE TITLE
Add tests for integer overflow

### ISSUE THREAD

**Issue by certik** [symengine/symengine#737]
I think there is a way to get an exception or abort if an integer overflows. We should enable that on Travis.

**Comment by Sumith1896** [comment]
Is there a standard way of doing this? 
I have not come across this. I think signed integer overflow needs examination after every incremental change of the value, I don't think that's how we want to test this.

**Comment by certik** [comment]
There is `-ftrapv` in gcc, here is how to use it: https://gist.github.com/mastbaum/1004768, maybe there is something easier to use in clang.

**Comment by Sumith1896** [comment]
I'm on this.

**Comment by Sumith1896** [comment]
So I have looked into this a bit. Signed integer overflows are Undefined Behaviour and can be detected by the undefined behaviour sanitiser which is included (but not default) with recent releases of Clang (clang++ -fsanitize=undefined) and GCC.
http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
Also, there is `-ftrapv` in gcc as @certik mentions. 

I didn't get time to write this up. This is open now. Anybody can pick it up.

**Comment by ShikharJ** [comment]
Fixed via #1145.
