### ISSUE TITLE
Lints in SymEngine 

### ISSUE THREAD

**Issue by Sumith1896** [symengine/symengine#764]
There has been lot of back and forth on lint scripts. Here is what I think we should eventually have:

* One single script(preferrably Python, not necessary though) that does all the checks.
* Grep code can also be called from this script.
* Have it outside travis, so that it can be executed once locally. Also have the lint check post all the other tests, so that things become easier while reviewing PRs and let travis give other errors.
* We can have multiple lints like whitespace, space after comma, space on either side of `=` and `==`. Many more C++ lints like unused header would be interesting.

Add your suggestions too!

**Comment by abinashmeher999** [comment]
I guess you might have seen this already. https://github.com/google/styleguide/tree/gh-pages/cpplint
We can modify it to our requirements.

**Comment by bollu** [comment]
We could also use [Uncrustify](http://uncrustify.sourceforge.net/), a tool for styling C++ code. It was used by the Neovim folks to rewrite a bunch of old vim code.

**Comment by CodeMaxx** [comment]
@Sumith1896 Can close this. We already have an issue for clang-format.
