### ISSUE TITLE
Add missing trigonometric functions

### ISSUE THREAD

**Issue by srajangarg** [symengine/symengine#777]
* [x] hyperbolic secant aka `sech`
* [x] hyperbolic cosecant aka `csch`
* [x] inverse hyperbolic cosecant aka `acsch`

**Comment by Sumith1896** [comment]
+1

**Comment by abinashmeher999** [comment]
+1

*Regards,*

*Abinash Meher*

**Comment by CodeMaxx** [comment]
@isuruf @certik I would like to work on this.

**Comment by certik** [comment]
@CodeMaxx go for it.

**Comment by CodeMaxx** [comment]
@srajangarg Can you update the description since #792  has been merged. Also close the issue.
