### ISSUE TITLE
minor cmake issue with setting flint=no

### ISSUE THREAD

**Issue by rwst** [symengine/symengine#788]
Setting `-DWITH_FLINT=no` with cmake will not set it to No if `WITH_ARB=yes` but it should set both to No.

Discussion in #795 showed that using `No` as default is indistinguisable to `No` as commanded. I think a solution would be to set the default to `Maybe`.

**Comment by malayaleecoder** [comment]
@rwst : I would like to work on this issue. I am very new to symengine. Please guide me through.

**Comment by rwst** [comment]
What do you not understand?

**Comment by malayaleecoder** [comment]
@rwst : Which are the files to be modified with the above changes?

**Comment by rwst** [comment]
The files that must be modified are our cmake configuration files, see https://cmake.org/

**Comment by malayaleecoder** [comment]
@rwst : Very sorry that I could not understand correctly what You are trying to convey. When I run "cmake ." I see that "WITH_ARB no". Is it this what you are referring?

**Comment by rwst** [comment]
SymEngine optionally uses arb and flint. Arb depends on flint and includes it. So, if all is No and WITH_ARB is then set to yes, WITH_FLINT is set to Yes too. That works already. Now with both Yes WITH_FLINT is set to No (because the user deinstalled it) then WITH_ARB should also be back at No. Your task is to implement that.

**Comment by CodeMaxx** [comment]
@malayaleecoder are you still working on this? Oth

**Comment by malayaleecoder** [comment]
@CodeMaxx : No, you can go ahead with it.

**Comment by CodeMaxx** [comment]
@rwst is `-DWITH_ARB=yes` by default ?

**Comment by rwst** [comment]
It depends on if arb is installed on the system.

**Comment by rwst** [comment]
Invalid as per discussion in #795
