### ISSUE TITLE
Min and Max function

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#789]
The functions should take in variable number of arguments and should automatically evaluate if all the values are numbers

**Comment by srajangarg** [comment]
@isuruf Will get this done

**Comment by Sumith1896** [comment]
@srajangarg Go ahead. You can have a look at the what we want here( [min](http://docs.sympy.org/latest/modules/functions/elementary.html?highlight=min#min) and [max](http://docs.sympy.org/latest/modules/functions/elementary.html?highlight=max#max) ).

**Comment by srajangarg** [comment]
@isuruf What will be the best file to write the declarations and definitions in?

**Comment by bjodah** [comment]
@srajangarg I was about to implement this about two weeks ago but other things got in between, I didn't get far but this was my start:
https://github.com/bjodah/symengine/commit/25e8388e5618a350c5967efb34350abdbac2d2b6

Feel free to use that commit as a starting point. Not sure if it's the optimal design, but @isuruf should know.

**Comment by srajangarg** [comment]
Thanks for the help @bjodah

**Comment by isuruf** [comment]
@srajangarg, as @bjodah did, you can implement it in `functions.h`

**Comment by srajangarg** [comment]
@isuruf should the function take only `vec_basic` as argument, or also allow variable number of `Basic` being passed to it ? (like here http://stackoverflow.com/questions/1657883/variable-number-of-arguments-in-c)

**Comment by abinashmeher999** [comment]
Why not have both? Both are equally intuitive.

**Comment by isuruf** [comment]
Just a `vec_basic`. Variable number of arguments should be used for C only.
If the function definition is `RCP<const Basic> min(vec_basic v)`, then you can pass in a `initializer_list`. eg: `min({a, b, c})`

**Comment by srajangarg** [comment]
Any suggestion on how to handle obvious 'biggers' like `2*x^2 >= x^2`. This will make the function complicated. Is it needed?
Also, as of now symengine does not have positive/negative symbols right? And how will these functions handle `Complex`?

**Comment by isuruf** [comment]
That is not needed.
If one of the elements in `vec_basic` is `Complex` throw an error.

**Comment by srajangarg** [comment]
@isuruf Please close this issue.
