### ISSUE TITLE
series_flint: catch Flint aborts before they happen

### ISSUE THREAD

**Issue by rwst** [symengine/symengine#793]
```
In [2]: from symengine import *

In [3]: x=Symbol('x')                      

In [4]: series(1/cos(x/log(x)), x, 0)
Out[4]: 
         2            4   
        x          5⋅x         ⎛ 6⎞
1 + ───────── + ────────── + O⎝x ⎠
         2            4       
    2⋅log (x)   24⋅log (x)  

In [5]: series(1/cos(x/log(x)), x, 0, method='symengine')
Exception (fmpq_poly_log_series). Constant term != 1.

Abort caught. Printing stacktrace:

Traceback (most recent call last):

Done.
Aborted
```
Synopsis: Flint's C layer does not have exceptions. It simply prints a message and calls `abort()`. The only layer aware of this is Teuchos which has installed a signal handler that tries to print a stacktrace. I don't think we can throw a `RuntimeError` at that point in time.

So this must be handled by catching all conditions in SymEngine that can lead to a Flint abort before Flint is called. So we opened a SymEngine issue.

**Comment by isuruf** [comment]
Here's a fix for this, http://stackoverflow.com/questions/8934879/how-to-handle-sigabrt-signal.

**Comment by rwst** [comment]
Works nicely, thanks!

**Comment by rwst** [comment]
OK, the new plan is to both
 * add `assert` checks to `series_flint.cpp`
 * add logic to `series()` to delegate all those cases to `UPSeriesPiranha`
