### ISSUE TITLE
Trigonometric expansions

### ISSUE THREAD

**Issue by nishnik** [symengine/symengine#802]
```
In [13]: e = sin(x+y)
In [14]: e.expand()
Out[14]: sin(x + y)
```
Should we add the functionality that this expands to
`sin(x)*cos(y) + cos(x)*sin(y)`
And similarly for other trigonometric functions.
If yes, it should be added in `expand.cpp`. Right ?

**Comment by CodeMaxx** [comment]
I'd like to work on this if this functionality is required.
