### ISSUE TITLE
Implement derivative of special functions

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#814]
- [x] KroneckerDelta
- [ ] Dirichlet_eta
- [ ] UpperGamma
- [ ] LowerGamma
- [x] Beta - Fixed in #818 
- [x] LeviCivita
- [x] PolyGamma - Fixed in #813

**Comment by nishnik** [comment]
I will like to work on this.

**Comment by CodeMaxx** [comment]
@nishnik Are you working on this? Otherwise I'll do this.

**Comment by nishnik** [comment]
@CodeMaxx I have already started it.
Have already implemented Beta derivatives [here](https://github.com/nishnik/symengine/tree/add_derivatives).

**Comment by parsoyaarihant** [comment]
@nishnik , any update?

**Comment by kvmanohar22** [comment]
@isuruf I would like to work on the remaining implementation. Could you please update the checklist on what is yet to be implemented ?

**Comment by ShikharJ** [comment]
@kvmanohar22 I am currently working on UpperGamma and LowerGamma, maybe you can contact @vishusidana95 and talk to him about his plans on implementing `Dirichlet_Eta`.

**Comment by isuruf** [comment]
Fixed via #1199 and #1151
