### ISSUE TITLE
tan function behaving unexpectedly

### ISSUE THREAD

**Issue by rajithv** [symengine/symengine#821]
I was wrapping trigonometric functions for symengine.rb and found out during testing that  `tan(pi/2)` returns `0`

**Comment by CodeMaxx** [comment]
`Infinity` class has not yet been implemented in Symengine(I'll probably do it soon.)
Thats the  reason for this output.

**Comment by isuruf** [comment]
Until `Infinity` is implemented, this should throw an exception. Not silently return a 0

**Comment by CodeMaxx** [comment]
This can be closed?

**Comment by isuruf** [comment]
Closed via #824
