### ISSUE TITLE
Compile errors on Cygwin

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#826]
From http://stackoverflow.com/questions/35576682/cygwin-gcc-compilation-of-symengine-error-using-make-variadic-templates

```
/cygdrive/c/SDPB/sym/symengine/symengine_rcp.h:294:32: warning: variadic templates only available with -std=c++11 or -std=gnu++11
template<typename T_, typename ...Args>
                        ^
/cygdrive/c/SDPB/sym/symengine/symengine_rcp.h:295:37: error: expected ‘,’ or ‘...’ before ‘&&’ token
friend inline RCP<T_> make_rcp( Args&& ...args );
                             ^
/cygdrive/c/SDPB/sym/symengine/symengine_rcp.h:295:48: error: parameter packs not expanded with ‘...’:
friend inline RCP<T_> make_rcp( Args&& ...args );
```

**Comment by isuruf** [comment]
I got an answer from the user that adding `-std=c++11` fixed this.
We should change `-std=c++0x` to `-std=c++11`. @certik, objections?

**Comment by certik** [comment]
Yes, we should use `-std=c++11`. The old compilers didn't support it, but the new ones do.

**Comment by isuruf** [comment]
Closing via #867. I haven't checked this on Cygwin, but if this does not fix the issue, I'll reopen the issue
