### ISSUE TITLE
Implement subs for special functions

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#833]
- [x] KroneckerDelta
- [ ] LeviCivita
- [x] Gamma
- [x] LowerGamma
- [x] UpperGamma
- [x] Beta
- [x] PolyGamma
- [ ] Abs
- [ ] Min
- [ ] Max

**Comment by abhinavagarwal07** [comment]
On it

**Comment by parsoyaarihant** [comment]
I want to work on the remaining functions. Any tips are welcome :)

**Comment by isuruf** [comment]
This is fixed now
