### ISSUE TITLE
Improve abs

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#834]
- [ ] `abs` should return evaluated values for all numeric types.
- [ ] `abs(-x)` should be equal to `abs(x)`

**Comment by CodeMaxx** [comment]
I'm on it

**Comment by CodeMaxx** [comment]
What all does "all" numeric types include and by evaluated values do you mean something like [this](https://github.com/symengine/symengine/blob/master/symengine/functions.cpp#L3331)?

**Comment by isuruf** [comment]
There are other numeric types like `RealDouble`.
>by evaluated values do you mean something like this?

yes

**Comment by CodeMaxx** [comment]
`Integer` and `Rational` are already handled separately. Also the 'inexact' cases are handled( which includes `RealDouble` ) and since `abs` is not meant for `Complex`... doesn't that cover all numerical types?

**Comment by isuruf** [comment]
Ah, yes. So only `Complex` is missing. `abs` is meant for `Complex`. See https://en.wikipedia.org/wiki/Complex_number#Absolute_value_and_argument

SymPy simplifies `abs(1+2*I)` to `sqrt(5)` and that's what is needed.

**Comment by CodeMaxx** [comment]
Got it.

**Comment by isuruf** [comment]
Closed via #835
