### ISSUE TITLE
[gsoc] Questions about design and refactorization

### ISSUE THREAD

**Issue by htfy96** [symengine/symengine#839]
Hi,
I read the sources in this repository and have some questions to ask:
1. Since C++11 has been used in this project, why does this project stick on `RCP` instead of builtin `shared_ptr` and `weak_ptr`? Is there any reason other than compatibility and null pointer prevention?
2. It seems that there are lots of `compare_foo` and `X.compare(Basic&)`. Would a unified `compare(const A&, const B&)` help to solve this problem?
3. I noticed that the classid is generated manually. Why is it not generated from `typeid`?

and I also found some defects:
1. Most comparators don't have `noexcept` signature
2. `xxx_print` functions shouldn't be exposed in `SymEngine` namespace, and there are lots of repeated code in them.
3. Only a few of functions provide R-value reference version

I also plan to import `assumptions` module into symengine in GSOC2016, but do we need a refactorization before that? Any suggestions would be appreciated.

**Comment by isuruf** [comment]
I'll try to address the comments one by one,

1. Advantage of a smart pointer with the reference counter in the shared object itself and inheriting from a structure like `Enable_rcp_from_this` is the performance and the ability to get a shared pointer to an object from the object itself. See http://www.codesynthesis.com/~boris/blog/2009/01/11/shared-ptr-counter/

2. `compare` method compares objects of same type. I can't think of a way to unify this approach.

3. Using an enum as a classid has several advantages. As seen in #342, it is faster. Also we can check for a set of types more efficiently. For ex we check that a type is a `Number1 by checking that the enum is between 0 and `NUMBERWRAPPER`. Also for functions like `eval_double_single_dispatch`, `__hash__` it is useful.

4. Is there any advantage to having a `noexcept` in comparators? If so, then we should do it.

5. What do you mean by `xxx_print`?

6. R-value version should be used when we are passing `std::vector`s or other containers. If there are instances where this is not true, then they should be fixed.

**Comment by htfy96** [comment]
2: 
```cpp
int unified_compare(const Basic &a, const Basic &b) {
    return a.compare(b);
}
template<typename A, typename B>
int unified_compare(const std::map<A, B> &a, const std::map<A, B> &b) {
    return map_compare(a,b);
}
```
Would this help?

4: There are two main reasons for `noexcept`: 1) semantics(like `const`) 2) tighter control flow (http://stackoverflow.com/questions/10787766/when-should-i-really-use-noexcept)

5: For example, `SymEngine::poly_print` in `expression.h` is only used internally, therefore it shouldn't be exposed to user in `SymEngine` at all. A better way is to put it in `namespace SymEngine_impl` or anything else. Moreover, functions that start with `_` in `ntheory.cpp` should have internal linkage and be put in `namespace {}`.

7: I don't think it is a good practice to define `std::ostream& operator<<(std::ostream& out, const SymEngine::vec_int& d)` in this library, which might be too intrusive, especially for such a common type.

**Comment by isuruf** [comment]
2. I still don't understand this. What would `unified_compare` replace in existing code?

4. Yes, I read that article and added `noexcept` in #825. If there are other places that should benefit fro `noexcept` let us know.

5. I agree about `SymEngine::poly_print`. It's used in `print_coefficient_impl` which can be implemented in `expression.cpp`. Can you fix it and send a PR? 
About internal functions, should they use anonymous namespaces or static keyword? Both achieve the same thing and static can be used easily inside `SymEngine` namespace. What do you think?

7. Yes, ostream operator << for `vec_int`, `map_vec_int` and `map_vec_mpz` and `umap_vec_mpz` should all be removed.

**Comment by htfy96** [comment]
@isuruf 
2: Call to `multiset_basic_compare`, `vec_basic_compare` will be replaced by `unified_compare`, while old `xxx_compare`s may still be kept for compatibility. A unified `compare` could bring much more ease when types become more complicated.

5: `static` was once deprecated for internal linkage and added back to standard in 2011, and it cannot apply to types. Therefore anonymous namespace might be a better choice.

I'll make a pull request to fix 5) and 7).

**Comment by CodeMaxx** [comment]
Can be closed?
