### ISSUE TITLE
UnivariatePolynomial::__eq__ gives (x+1) + (x-1) != 2x

### ISSUE THREAD

**Issue by myluszczak** [symengine/symengine#848]
[test.zip](https://github.com/symengine/symengine/files/159576/test.zip)
The current implementation of UnivariatePolynomial::__eq__ checks if the dictionaries of the two polynomials are exactly equal, and will return false if comparing polynomials with the dictionaries {{0,0},{1,2}} and {{1,2}} representing 0 + 2x and 2x respectively.  Since addition does not remove the entries of a dictionary corresponding to terms that have zero coefficients, this can lead to a situation where SymEngine tells us that (x+1) + (x-1) != 2x, as shown above.  

I've submitted a pull request (#847) that I believe fixes this problem, but the guidelines for contributing said that bugs should be reported here.

**Comment by certik** [comment]
@myluszczak thanks for reporting this and also fixing it. Let me review your PR.
