### ISSUE TITLE
Improve could_extract_minus for Add

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#871]
This should make `could_extract_minus(x-y) != could_extract_minus(y-x)`

**Comment by vyasgiridhar** [comment]
Why would that make any difference?

**Comment by isuruf** [comment]
This is to have automatic simplifications like `abs(x-y)-abs(y-x)==0`

**Comment by CodeMaxx** [comment]
**Note** We are aiming to differentiate between all such expressions as `x-y-z` and `z+y-x`(basically any kind of `Basic` and its negative can be differenciated) and not just for the special case of `x-y`. So the algorithm should be general.

**Comment by vyasgiridhar** [comment]
It would be easier to create a new function to check if 
```c++
bool is_negative_of();
```
rather than using could_extract_minus for this purpose.

**Comment by isuruf** [comment]
Any particular reason?

**Comment by vyasgiridhar** [comment]
for example,
```math 
-x + 2*y 
```
will fail. 
It is better to create a new function for this purpose.

**Comment by isuruf** [comment]
Why can't it be incorporated to `could_extract_minus`? When you fix `could_extract_minus`, it will improve lots of things in SymEngine including `abs(-x+2*y) == abs(x-2*y)`, `sin(-x+2*y) == -sin(x- 2*y)`, etc.
