### ISSUE TITLE
The series of (1+x)^0 appears to result in other things than 1

### ISSUE THREAD

**Issue by aaditya-thakkar** [symengine/symengine#878]
cc @rwst , 
The series of `(1+x)^0` does not result in 1.  I guess the problem might be with this https://github.com/symengine/symengine/blob/master/symengine/series_flint.cpp#L126
as it passes an `integer` directly into the fp_t().

**Comment by rwst** [comment]
This is a bug, but it does not show because `anything**0` (even `zoo**0`) is immediately expanded to 1. It should be fixed anyway.
