### ISSUE TITLE
Clang warnings 

### ISSUE THREAD

**Issue by chenchfort** [symengine/symengine#879]
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix

Generated when I make: 
[error.txt](https://github.com/symengine/symengine/files/185308/error.txt)

@isuruf @certik

**Comment by CodeMaxx** [comment]
I get the same error on compiling with `make`.

GNU Make 3.81
for i386-apple-darwin11.3.0

This happened after I upgraded to OS X 10.11.4

**Comment by irislq** [comment]
I get the same errors with the same version clang as Charles.

**Comment by chenchfort** [comment]
It's resolved now. Closing.
