### ISSUE TITLE
Method to add a vector of basic together

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#885]
This should be faster than adding one by one for large expressions.

**Comment by abinashmeher999** [comment]
Just to be clear, you are suggesting a method to add all the elements of a `vec_basic` together, right?

**Comment by isuruf** [comment]
Yes

**Comment by CodeMaxx** [comment]
@isuruf What do you mean by "faster than adding one by one" ? Can you give an example

**Comment by isuruf** [comment]
`add({a, b, c})` should be faster than `add(a, add(b, c))` which creates a temporary object `add(b, c)`

**Comment by CodeMaxx** [comment]
Can be closed

**Comment by isuruf** [comment]
Closed via #892
