### ISSUE TITLE
Clang_format changing the order of #include

### ISSUE THREAD

**Issue by CodeMaxx** [symengine/symengine#905]
`clang-format` arranges the `#include`s in lexicographic order
This causes certain tests to fail in PR #893.
See this question on stackoverflow
http://stackoverflow.com/questions/865785/why-does-the-order-of-my-includes-matter-c
 @certik @isuruf

**Comment by CodeMaxx** [comment]
Ok wait... I have clang-format 3.8 on my mac. This change has been introduced in this version.

**Comment by certik** [comment]
Yes, right now we use 3.7.

**Comment by CodeMaxx** [comment]
@certik What I want to say that, we will not be able to use version 3.8(latest) in future.

**Comment by certik** [comment]
@CodeMaxx you can use the `IncludeCategories` option (http://clang.llvm.org/docs/ClangFormatStyleOptions.html) to order header files in the right order.

**Comment by CodeMaxx** [comment]
@certik Take a look at #917

**Comment by rikardn** [comment]
This has now been fixed in `.clang-format`
