### ISSUE TITLE
Differentiation of matrix and vector expressions

### ISSUE THREAD

**Issue by mohawkjohn** [symengine/symengine#908]
For example,

```
v = MatrixSymbol('v', 3, 1)
r = MatrixSymbol('r', 3, 1)
t = Symbol('t')
f = v*t + r
df_dt = diff(f,t) # returns a Derivative object
df_dr = diff(f,r) # gives an error: 'MatrixSymbol' object has no attribute '_diff_wrt'
df_dv = diff(f,v) # same error as above
```

Is there a how-to anywhere on teaching SymEngine new patterns, and instructing it on how to solve them? I'd love to put some work into this since it'd be so useful for my job.

**Comment by isuruf** [comment]
`MatrixSymbol` is not yet implemented in SymEngine. If you can give your expected outputs, we can first implement in SymPy and then in SymEngine.

**Comment by mohawkjohn** [comment]
What do you mean by expected outputs?

[The Matrix Cookbook](http://www2.imm.dtu.dk/pubdb/views/edoc_download.php/3274/pdf/imm3274.pdf)  has most of them — see especially Section 2.4, but Chapter 2 overall (starts on page 8).

**Comment by isuruf** [comment]
Ah. This should be reported to SymPy at https://github.com/sympy/sympy

SymEngine is trying to provide a fast C++ core for SymPy and other CASs. It's written from the ground up and only includes core methods for now. SymEngine intends to be a full CAS in the future, but that's long term.

SymEngine was developed independently of SymPy and now we are trying to get SymEngine to act as SymPy's core optionally.

**Comment by mohawkjohn** [comment]
Okay, so no hope of getting this into symengine.rb in the near future?

**Comment by isuruf** [comment]
Opened sympy/sympy#10989

> Okay, so no hope of getting this into symengine.rb in the near future?

I'm not sure when this will be implemented in SymEngine. This should be simple after we figure out how to integrate Polynomials to SymEngine expressions.

**Comment by isuruf** [comment]
Opened #912 for Matrix expressions in SymEngine
