### ISSUE TITLE
Base class for Complex, ComplexDouble, ComplexMPC

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#915]
All 3 should be child classes of a base class `ComplexBase`. Also a method should be added `is_a_Complex` to figure out if a `Basic` object is a `Complex` or not

**Comment by CodeMaxx** [comment]
@isuruf We can use `is_a<Complex>`?

**Comment by isuruf** [comment]
No, `is_a<Complex>` would only be true for `Complex` and false for `ComplexDouble`, `ComplexMPC`

**Comment by ShikharJ** [comment]
@isuruf I'd like to take this up.

**Comment by ShikharJ** [comment]
Fixed via #1171.
