### ISSUE TITLE
cmake error in arch linux

### ISSUE THREAD

**Issue by vyasgiridhar** [symengine/symengine#918]
```
  make[1]: *** No rule to make target
  '/usr/lib/x86_64-linux-gnu/libgmpxx.so', needed by 'cmTC_0db36'.  Stop.
```

libgmpxx is not located at 'usr/lib/x86_64-linux-gnu/

```
/usr/lib/libgmpxx.so
```

**Comment by CodeMaxx** [comment]
Do you have `libgmp` installed on your system?

**Comment by vyasgiridhar** [comment]
i have. The location of libgmpxx.so is different

**Comment by CodeMaxx** [comment]
Did you change the default location while installing `libgmp`?

**Comment by vyasgiridhar** [comment]
No.

**Comment by certik** [comment]
@vyasgiridhar thanks for the report. I think there is a flag to cmake that makes it not search in the `x86_64-linux-gnu` subdirectory if your system doesn't use it. Let me know if you need help with this. Once we figure out how to fix it for you, let's either fix it by default, or document how to workaround it on Arch.

Btw, we should try to use Docker and install arch and other distributions in it, then we can test it on Travis.

**Comment by vyasgiridhar** [comment]
Its Solved
