### ISSUE TITLE
sec function behaves incorrectly

### ISSUE THREAD

**Issue by rajithv** [symengine/symengine#921]
`sec(0)` is returning  `2*2**(1/2)/(1 + 3**(1/2))`.

**Comment by certik** [comment]
It should be 1. Thanks for finding this.

**Comment by Nitin216** [comment]
I am new to symengine. I would like to work on this problem. Someone please guide me.

**Comment by parsoyaarihant** [comment]
@nishnik , is the issue fixed?

**Comment by isuruf** [comment]
@parsoyaarihant, it was not fixed.

**Comment by parsoyaarihant** [comment]
can I work on this? Since @nishnik isnt responding from long time.

**Comment by isuruf** [comment]
Sure.

**Comment by Sumith1896** [comment]
Fixed via https://github.com/symengine/symengine/pull/1020
