### ISSUE TITLE
What version Cython is required?

### ISSUE THREAD

**Issue by moorepants** [symengine/symengine#93]
I have the latest version of Cython from the Ubuntu repo (0.17.4) and tried this:

```
$ cmake -DCMAKE_INSTALL_PREFIX="~/bin" -DWITH_PYTHON=yes .
-- The C compiler identification is GNU 4.7.3
-- The CXX compiler identification is GNU 4.7.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmpxx.so;/usr/lib/x86_64-linux-gnu/libgmp.so  
-- Python version: 2.7
-- Python install path: /usr/lib/python2.7/dist-packages
-- Could NOT find PYTHON (missing:  PYTHON_LIBRARY) 
-- Found CYTHON: /usr/bin/cython
CMake Error at cmake/FindCython.cmake:39 (MESSAGE):
  Your Cython version is too old.  Please upgrade Cython.
Call Stack (most recent call first):
  CMakeLists.txt:94 (find_package)
```

Do I have to install a newer version of Cython? I usually keep the ubuntu repo version on my system and install Cython in virtualenvs if I need the latest and greatest, but I've always had trouble installing c/c++ apps with python wrappers in virtualenvs.

**Comment by Sumith1896** [comment]
Ubuntu trusty (14.04LTS) have Cython version 0.20.1 and later ones even higher, these versions are good for our requirements now.

**Comment by moorepants** [comment]
Maybe you all have it somewhere, but I'd say this can be closed if you have the required minimal version of Cython listed somewhere in the docs.

**Comment by Sumith1896** [comment]
Mention is here: https://github.com/sympy/symengine#python-wrappers
We can close this, if any core developer can second that.
