### ISSUE TITLE
Master coverage decreased from 78% to 68%

### ISSUE THREAD

**Issue by Sumith1896** [symengine/symengine#990]
Could somebody look into this?

**Comment by rwst** [comment]
Is it possible to determine the metric locally?

**Comment by Sumith1896** [comment]
Should be possible, `lcov` or `gcov`. Though I don't know the details

**Comment by rwst** [comment]
```
rm CMakeCache.txt
make clean
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG="-g -fprofile-arcs -ftest-coverage --std=c++11" .
make test
lcov --capture --directory . --output-file coverage.info
genhtml coverage.info --output-directory out
(point browser at out/index.html)
```
Thanks @bluescarni for the last three lines.

**Comment by Sumith1896** [comment]
Closed via https://github.com/symengine/symengine/pull/1217 
We should target https://github.com/symengine/symengine/issues/849
